# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
from baohaus.onnx.v1.TensorV1 import TensorV1
np = import_numpy()

# Result for a single batch item.
class BatchItemResultV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BatchItemResultV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBatchItemResultV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BatchItemResultV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4F\x49\x56\x31", size_prefixed=size_prefixed)

    # BatchItemResultV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Correlation ID matching BatchItemV1.id.
    # BatchItemResultV1
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Inference status for this item.
    # BatchItemResultV1
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Output tensors (when status = SUCCESS).
    # BatchItemResultV1
    def Outputs(self, j: int) -> Optional[TensorV1]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = TensorV1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BatchItemResultV1
    def OutputsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BatchItemResultV1
    def OutputsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Error message (when status != SUCCESS).
    # BatchItemResultV1
    def Error(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Latency in milliseconds for this item.
    # BatchItemResultV1
    def LatencyMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def BatchItemResultV1Start(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    BatchItemResultV1Start(builder)

def BatchItemResultV1AddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    BatchItemResultV1AddId(builder, id)

def BatchItemResultV1AddStatus(builder: flatbuffers.Builder, status: int):
    builder.PrependUint8Slot(1, status, 0)

def AddStatus(builder: flatbuffers.Builder, status: int):
    BatchItemResultV1AddStatus(builder, status)

def BatchItemResultV1AddOutputs(builder: flatbuffers.Builder, outputs: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(outputs), 0)

def AddOutputs(builder: flatbuffers.Builder, outputs: int):
    BatchItemResultV1AddOutputs(builder, outputs)

def BatchItemResultV1StartOutputsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartOutputsVector(builder, numElems: int) -> int:
    return BatchItemResultV1StartOutputsVector(builder, numElems)

def BatchItemResultV1AddError(builder: flatbuffers.Builder, error: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)

def AddError(builder: flatbuffers.Builder, error: int):
    BatchItemResultV1AddError(builder, error)

def BatchItemResultV1AddLatencyMs(builder: flatbuffers.Builder, latencyMs: int):
    builder.PrependUint32Slot(4, latencyMs, 0)

def AddLatencyMs(builder: flatbuffers.Builder, latencyMs: int):
    BatchItemResultV1AddLatencyMs(builder, latencyMs)

def BatchItemResultV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return BatchItemResultV1End(builder)
