from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.onnx.v1.InferenceStatusV1 import InferenceStatusV1
from baohaus.onnx.v1.TensorV1 import TensorV1

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class BatchItemResultV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> BatchItemResultV1: ...
  @classmethod
  def GetRootAsBatchItemResultV1(cls, buf: bytes, offset: int) -> BatchItemResultV1: ...
  @classmethod
  def BatchItemResultV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Status(self) -> typing.Literal[InferenceStatusV1.SUCCESS, InferenceStatusV1.ERROR, InferenceStatusV1.TIMEOUT, InferenceStatusV1.CANCELLED]: ...
  def Outputs(self, i: int) -> TensorV1 | None: ...
  def OutputsLength(self) -> int: ...
  def OutputsIsNone(self) -> bool: ...
  def Error(self) -> str | None: ...
  def LatencyMs(self) -> int: ...
def BatchItemResultV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def BatchItemResultV1AddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def BatchItemResultV1AddStatus(builder: flatbuffers.Builder, status: typing.Literal[InferenceStatusV1.SUCCESS, InferenceStatusV1.ERROR, InferenceStatusV1.TIMEOUT, InferenceStatusV1.CANCELLED]) -> None: ...
def BatchItemResultV1AddOutputs(builder: flatbuffers.Builder, outputs: uoffset) -> None: ...
def BatchItemResultV1StartOutputsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartOutputsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def BatchItemResultV1AddError(builder: flatbuffers.Builder, error: uoffset) -> None: ...
def BatchItemResultV1AddLatencyMs(builder: flatbuffers.Builder, latencyMs: int) -> None: ...
def BatchItemResultV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

