from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.onnx.v1.TensorV1 import TensorV1

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class BatchItemV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> BatchItemV1: ...
  @classmethod
  def GetRootAsBatchItemV1(cls, buf: bytes, offset: int) -> BatchItemV1: ...
  @classmethod
  def BatchItemV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Inputs(self, i: int) -> TensorV1 | None: ...
  def InputsLength(self) -> int: ...
  def InputsIsNone(self) -> bool: ...
def BatchItemV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def BatchItemV1AddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def BatchItemV1AddInputs(builder: flatbuffers.Builder, inputs: uoffset) -> None: ...
def BatchItemV1StartInputsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartInputsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def BatchItemV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

