# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

# Execution provider (GPU/CPU backend).
class ExecutionProviderV1(object):
    CPU = 0
    WASM = 1
    WEBGPU = 2
