# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

# Inference result status.
class InferenceStatusV1(object):
    SUCCESS = 0
    ERROR = 1
    TIMEOUT = 2
    CANCELLED = 3
