# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
from baohaus.onnx.v1.BatchItemV1 import BatchItemV1
np = import_numpy()

# Batch inference request.
class OnnxBatchRequestV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OnnxBatchRequestV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOnnxBatchRequestV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def OnnxBatchRequestV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4F\x49\x56\x31", size_prefixed=size_prefixed)

    # OnnxBatchRequestV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Correlation ID for request tracing.
    # OnnxBatchRequestV1
    def CorrelationId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ONNX model identifier.
    # OnnxBatchRequestV1
    def ModelId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Preferred execution provider.
    # OnnxBatchRequestV1
    def ExecutionProvider(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 2

    # Batch items to infer.
    # OnnxBatchRequestV1
    def Items(self, j: int) -> Optional[BatchItemV1]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = BatchItemV1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OnnxBatchRequestV1
    def ItemsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OnnxBatchRequestV1
    def ItemsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Timeout per item in milliseconds.
    # OnnxBatchRequestV1
    def TimeoutMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 30000

    # Whether to collect per-item performance metrics.
    # OnnxBatchRequestV1
    def CollectMetrics(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def OnnxBatchRequestV1Start(builder: flatbuffers.Builder):
    builder.StartObject(6)

def Start(builder: flatbuffers.Builder):
    OnnxBatchRequestV1Start(builder)

def OnnxBatchRequestV1AddCorrelationId(builder: flatbuffers.Builder, correlationId: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(correlationId), 0)

def AddCorrelationId(builder: flatbuffers.Builder, correlationId: int):
    OnnxBatchRequestV1AddCorrelationId(builder, correlationId)

def OnnxBatchRequestV1AddModelId(builder: flatbuffers.Builder, modelId: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(modelId), 0)

def AddModelId(builder: flatbuffers.Builder, modelId: int):
    OnnxBatchRequestV1AddModelId(builder, modelId)

def OnnxBatchRequestV1AddExecutionProvider(builder: flatbuffers.Builder, executionProvider: int):
    builder.PrependUint8Slot(2, executionProvider, 2)

def AddExecutionProvider(builder: flatbuffers.Builder, executionProvider: int):
    OnnxBatchRequestV1AddExecutionProvider(builder, executionProvider)

def OnnxBatchRequestV1AddItems(builder: flatbuffers.Builder, items: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(items), 0)

def AddItems(builder: flatbuffers.Builder, items: int):
    OnnxBatchRequestV1AddItems(builder, items)

def OnnxBatchRequestV1StartItemsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartItemsVector(builder, numElems: int) -> int:
    return OnnxBatchRequestV1StartItemsVector(builder, numElems)

def OnnxBatchRequestV1AddTimeoutMs(builder: flatbuffers.Builder, timeoutMs: int):
    builder.PrependUint32Slot(4, timeoutMs, 30000)

def AddTimeoutMs(builder: flatbuffers.Builder, timeoutMs: int):
    OnnxBatchRequestV1AddTimeoutMs(builder, timeoutMs)

def OnnxBatchRequestV1AddCollectMetrics(builder: flatbuffers.Builder, collectMetrics: bool):
    builder.PrependBoolSlot(5, collectMetrics, 0)

def AddCollectMetrics(builder: flatbuffers.Builder, collectMetrics: bool):
    OnnxBatchRequestV1AddCollectMetrics(builder, collectMetrics)

def OnnxBatchRequestV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return OnnxBatchRequestV1End(builder)
