# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
from baohaus.onnx.v1.BatchItemResultV1 import BatchItemResultV1
np = import_numpy()

# Batch inference response.
class OnnxBatchResponseV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OnnxBatchResponseV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOnnxBatchResponseV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def OnnxBatchResponseV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4F\x49\x56\x31", size_prefixed=size_prefixed)

    # OnnxBatchResponseV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Whether all items succeeded.
    # OnnxBatchResponseV1
    def Ok(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Total items in the batch.
    # OnnxBatchResponseV1
    def TotalItems(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Number of successful inferences.
    # OnnxBatchResponseV1
    def SuccessCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Number of failed inferences.
    # OnnxBatchResponseV1
    def FailureCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Total batch latency in milliseconds.
    # OnnxBatchResponseV1
    def TotalLatencyMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Execution provider actually used.
    # OnnxBatchResponseV1
    def ExecutionProvider(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Per-item results.
    # OnnxBatchResponseV1
    def Results(self, j: int) -> Optional[BatchItemResultV1]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = BatchItemResultV1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OnnxBatchResponseV1
    def ResultsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OnnxBatchResponseV1
    def ResultsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def OnnxBatchResponseV1Start(builder: flatbuffers.Builder):
    builder.StartObject(7)

def Start(builder: flatbuffers.Builder):
    OnnxBatchResponseV1Start(builder)

def OnnxBatchResponseV1AddOk(builder: flatbuffers.Builder, ok: bool):
    builder.PrependBoolSlot(0, ok, 0)

def AddOk(builder: flatbuffers.Builder, ok: bool):
    OnnxBatchResponseV1AddOk(builder, ok)

def OnnxBatchResponseV1AddTotalItems(builder: flatbuffers.Builder, totalItems: int):
    builder.PrependUint16Slot(1, totalItems, 0)

def AddTotalItems(builder: flatbuffers.Builder, totalItems: int):
    OnnxBatchResponseV1AddTotalItems(builder, totalItems)

def OnnxBatchResponseV1AddSuccessCount(builder: flatbuffers.Builder, successCount: int):
    builder.PrependUint16Slot(2, successCount, 0)

def AddSuccessCount(builder: flatbuffers.Builder, successCount: int):
    OnnxBatchResponseV1AddSuccessCount(builder, successCount)

def OnnxBatchResponseV1AddFailureCount(builder: flatbuffers.Builder, failureCount: int):
    builder.PrependUint16Slot(3, failureCount, 0)

def AddFailureCount(builder: flatbuffers.Builder, failureCount: int):
    OnnxBatchResponseV1AddFailureCount(builder, failureCount)

def OnnxBatchResponseV1AddTotalLatencyMs(builder: flatbuffers.Builder, totalLatencyMs: int):
    builder.PrependUint32Slot(4, totalLatencyMs, 0)

def AddTotalLatencyMs(builder: flatbuffers.Builder, totalLatencyMs: int):
    OnnxBatchResponseV1AddTotalLatencyMs(builder, totalLatencyMs)

def OnnxBatchResponseV1AddExecutionProvider(builder: flatbuffers.Builder, executionProvider: int):
    builder.PrependUint8Slot(5, executionProvider, 0)

def AddExecutionProvider(builder: flatbuffers.Builder, executionProvider: int):
    OnnxBatchResponseV1AddExecutionProvider(builder, executionProvider)

def OnnxBatchResponseV1AddResults(builder: flatbuffers.Builder, results: int):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(results), 0)

def AddResults(builder: flatbuffers.Builder, results: int):
    OnnxBatchResponseV1AddResults(builder, results)

def OnnxBatchResponseV1StartResultsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartResultsVector(builder, numElems: int) -> int:
    return OnnxBatchResponseV1StartResultsVector(builder, numElems)

def OnnxBatchResponseV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return OnnxBatchResponseV1End(builder)
