from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.onnx.v1.BatchItemResultV1 import BatchItemResultV1
from baohaus.onnx.v1.ExecutionProviderV1 import ExecutionProviderV1

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class OnnxBatchResponseV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> OnnxBatchResponseV1: ...
  @classmethod
  def GetRootAsOnnxBatchResponseV1(cls, buf: bytes, offset: int) -> OnnxBatchResponseV1: ...
  @classmethod
  def OnnxBatchResponseV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Ok(self) -> bool: ...
  def TotalItems(self) -> int: ...
  def SuccessCount(self) -> int: ...
  def FailureCount(self) -> int: ...
  def TotalLatencyMs(self) -> int: ...
  def ExecutionProvider(self) -> typing.Literal[ExecutionProviderV1.CPU, ExecutionProviderV1.WASM, ExecutionProviderV1.WEBGPU]: ...
  def Results(self, i: int) -> BatchItemResultV1 | None: ...
  def ResultsLength(self) -> int: ...
  def ResultsIsNone(self) -> bool: ...
def OnnxBatchResponseV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def OnnxBatchResponseV1AddOk(builder: flatbuffers.Builder, ok: bool) -> None: ...
def OnnxBatchResponseV1AddTotalItems(builder: flatbuffers.Builder, totalItems: int) -> None: ...
def OnnxBatchResponseV1AddSuccessCount(builder: flatbuffers.Builder, successCount: int) -> None: ...
def OnnxBatchResponseV1AddFailureCount(builder: flatbuffers.Builder, failureCount: int) -> None: ...
def OnnxBatchResponseV1AddTotalLatencyMs(builder: flatbuffers.Builder, totalLatencyMs: int) -> None: ...
def OnnxBatchResponseV1AddExecutionProvider(builder: flatbuffers.Builder, executionProvider: typing.Literal[ExecutionProviderV1.CPU, ExecutionProviderV1.WASM, ExecutionProviderV1.WEBGPU]) -> None: ...
def OnnxBatchResponseV1AddResults(builder: flatbuffers.Builder, results: uoffset) -> None: ...
def OnnxBatchResponseV1StartResultsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartResultsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def OnnxBatchResponseV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

