from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.onnx.v1.BatchItemV1 import BatchItemV1
from baohaus.onnx.v1.ExecutionProviderV1 import ExecutionProviderV1

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class OnnxBatchRequestV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> OnnxBatchRequestV1: ...
  @classmethod
  def GetRootAsOnnxBatchRequestV1(cls, buf: bytes, offset: int) -> OnnxBatchRequestV1: ...
  @classmethod
  def OnnxBatchRequestV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def CorrelationId(self) -> str | None: ...
  def ModelId(self) -> str | None: ...
  def ExecutionProvider(self) -> typing.Literal[ExecutionProviderV1.CPU, ExecutionProviderV1.WASM, ExecutionProviderV1.WEBGPU]: ...
  def Items(self, i: int) -> BatchItemV1 | None: ...
  def ItemsLength(self) -> int: ...
  def ItemsIsNone(self) -> bool: ...
  def TimeoutMs(self) -> int: ...
  def CollectMetrics(self) -> bool: ...
def OnnxBatchRequestV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def OnnxBatchRequestV1AddCorrelationId(builder: flatbuffers.Builder, correlationId: uoffset) -> None: ...
def OnnxBatchRequestV1AddModelId(builder: flatbuffers.Builder, modelId: uoffset) -> None: ...
def OnnxBatchRequestV1AddExecutionProvider(builder: flatbuffers.Builder, executionProvider: typing.Literal[ExecutionProviderV1.CPU, ExecutionProviderV1.WASM, ExecutionProviderV1.WEBGPU]) -> None: ...
def OnnxBatchRequestV1AddItems(builder: flatbuffers.Builder, items: uoffset) -> None: ...
def OnnxBatchRequestV1StartItemsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartItemsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def OnnxBatchRequestV1AddTimeoutMs(builder: flatbuffers.Builder, timeoutMs: int) -> None: ...
def OnnxBatchRequestV1AddCollectMetrics(builder: flatbuffers.Builder, collectMetrics: bool) -> None: ...
def OnnxBatchRequestV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

