from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.onnx.v1.TensorTypeV1 import TensorTypeV1

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class TensorV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TensorV1: ...
  @classmethod
  def GetRootAsTensorV1(cls, buf: bytes, offset: int) -> TensorV1: ...
  @classmethod
  def TensorV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Name(self) -> str | None: ...
  def Shape(self, i: int) -> typing.List[int]: ...
  def ShapeAsNumpy(self) -> np.ndarray: ...
  def ShapeLength(self) -> int: ...
  def ShapeIsNone(self) -> bool: ...
  def Dtype(self) -> typing.Literal[TensorTypeV1.FLOAT32, TensorTypeV1.FLOAT16, TensorTypeV1.INT32, TensorTypeV1.INT64, TensorTypeV1.UINT8, TensorTypeV1.BOOL, TensorTypeV1.STRING]: ...
  def Data(self, i: int) -> typing.List[int]: ...
  def DataAsNumpy(self) -> np.ndarray: ...
  def DataLength(self) -> int: ...
  def DataIsNone(self) -> bool: ...
def TensorV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def TensorV1AddName(builder: flatbuffers.Builder, name: uoffset) -> None: ...
def TensorV1AddShape(builder: flatbuffers.Builder, shape: uoffset) -> None: ...
def TensorV1StartShapeVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartShapeVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def TensorV1AddDtype(builder: flatbuffers.Builder, dtype: typing.Literal[TensorTypeV1.FLOAT32, TensorTypeV1.FLOAT16, TensorTypeV1.INT32, TensorTypeV1.INT64, TensorTypeV1.UINT8, TensorTypeV1.BOOL, TensorTypeV1.STRING]) -> None: ...
def TensorV1AddData(builder: flatbuffers.Builder, data: uoffset) -> None: ...
def TensorV1StartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def TensorV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

