# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

# Tensor data type for inference IO.
class TensorTypeV1(object):
    FLOAT32 = 0
    FLOAT16 = 1
    INT32 = 2
    INT64 = 3
    UINT8 = 4
    BOOL = 5
    STRING = 6
