from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class BatteryStatus(object):
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def Level(self) -> float: ...
  def Voltage(self) -> float: ...
  def Current(self) -> float: ...
  def Temperature(self) -> float: ...
  def RemainingPercent(self) -> float: ...

def CreateBatteryStatus(builder: flatbuffers.Builder, level: float, voltage: float, current: float, temperature: float, remainingPercent: float) -> uoffset: ...

