# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class BatteryStatus(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls) -> int:
        return 20

    # BatteryStatus
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BatteryStatus
    def Level(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # BatteryStatus
    def Voltage(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # BatteryStatus
    def Current(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # BatteryStatus
    def Temperature(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
    # BatteryStatus
    def RemainingPercent(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))

def CreateBatteryStatus(builder, level, voltage, current, temperature, remainingPercent):
    builder.Prep(4, 20)
    builder.PrependFloat32(remainingPercent)
    builder.PrependFloat32(temperature)
    builder.PrependFloat32(current)
    builder.PrependFloat32(voltage)
    builder.PrependFloat32(level)
    return builder.Offset()
