# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class DeviceEventV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DeviceEventV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDeviceEventV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DeviceEventV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x45\x56\x31", size_prefixed=size_prefixed)

    # DeviceEventV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DeviceEventV1
    def DeviceId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DeviceEventV1
    def Type(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DeviceEventV1
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # DeviceEventV1
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # DeviceEventV1
    def Timestamp(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def DeviceEventV1Start(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    DeviceEventV1Start(builder)

def DeviceEventV1AddDeviceId(builder: flatbuffers.Builder, deviceId: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(deviceId), 0)

def AddDeviceId(builder: flatbuffers.Builder, deviceId: int):
    DeviceEventV1AddDeviceId(builder, deviceId)

def DeviceEventV1AddType(builder: flatbuffers.Builder, type: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(type), 0)

def AddType(builder: flatbuffers.Builder, type: int):
    DeviceEventV1AddType(builder, type)

def DeviceEventV1AddStatus(builder: flatbuffers.Builder, status: int):
    builder.PrependUint8Slot(2, status, 0)

def AddStatus(builder: flatbuffers.Builder, status: int):
    DeviceEventV1AddStatus(builder, status)

def DeviceEventV1AddValue(builder: flatbuffers.Builder, value: float):
    builder.PrependFloat32Slot(3, value, 0.0)

def AddValue(builder: flatbuffers.Builder, value: float):
    DeviceEventV1AddValue(builder, value)

def DeviceEventV1AddTimestamp(builder: flatbuffers.Builder, timestamp: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder: flatbuffers.Builder, timestamp: int):
    DeviceEventV1AddTimestamp(builder, timestamp)

def DeviceEventV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return DeviceEventV1End(builder)
