from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class DeviceEventV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> DeviceEventV1: ...
  @classmethod
  def GetRootAsDeviceEventV1(cls, buf: bytes, offset: int) -> DeviceEventV1: ...
  @classmethod
  def DeviceEventV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def DeviceId(self) -> str | None: ...
  def Type(self) -> str | None: ...
  def Status(self) -> int: ...
  def Value(self) -> float: ...
  def Timestamp(self) -> str | None: ...
def DeviceEventV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def DeviceEventV1AddDeviceId(builder: flatbuffers.Builder, deviceId: uoffset) -> None: ...
def DeviceEventV1AddType(builder: flatbuffers.Builder, type: uoffset) -> None: ...
def DeviceEventV1AddStatus(builder: flatbuffers.Builder, status: int) -> None: ...
def DeviceEventV1AddValue(builder: flatbuffers.Builder, value: float) -> None: ...
def DeviceEventV1AddTimestamp(builder: flatbuffers.Builder, timestamp: uoffset) -> None: ...
def DeviceEventV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

