# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
from baohaus.realtime.v1.DeviceEventV1 import DeviceEventV1
from baohaus.realtime.v1.GimbalEventV1 import GimbalEventV1
np = import_numpy()

# Internal drone realtime payload for high-frequency transport.
class DroneRealtimeV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DroneRealtimeV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDroneRealtimeV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DroneRealtimeV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x52\x56\x31", size_prefixed=size_prefixed)

    # DroneRealtimeV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DroneRealtimeV1
    def Channel(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DroneRealtimeV1
    def Event(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DroneRealtimeV1
    def Timestamp(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DroneRealtimeV1
    def BaseUrl(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DroneRealtimeV1
    def DeviceEvent(self) -> Optional[DeviceEventV1]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = DeviceEventV1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DroneRealtimeV1
    def GimbalEvent(self) -> Optional[GimbalEventV1]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = GimbalEventV1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def DroneRealtimeV1Start(builder: flatbuffers.Builder):
    builder.StartObject(6)

def Start(builder: flatbuffers.Builder):
    DroneRealtimeV1Start(builder)

def DroneRealtimeV1AddChannel(builder: flatbuffers.Builder, channel: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(channel), 0)

def AddChannel(builder: flatbuffers.Builder, channel: int):
    DroneRealtimeV1AddChannel(builder, channel)

def DroneRealtimeV1AddEvent(builder: flatbuffers.Builder, event: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(event), 0)

def AddEvent(builder: flatbuffers.Builder, event: int):
    DroneRealtimeV1AddEvent(builder, event)

def DroneRealtimeV1AddTimestamp(builder: flatbuffers.Builder, timestamp: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder: flatbuffers.Builder, timestamp: int):
    DroneRealtimeV1AddTimestamp(builder, timestamp)

def DroneRealtimeV1AddBaseUrl(builder: flatbuffers.Builder, baseUrl: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(baseUrl), 0)

def AddBaseUrl(builder: flatbuffers.Builder, baseUrl: int):
    DroneRealtimeV1AddBaseUrl(builder, baseUrl)

def DroneRealtimeV1AddDeviceEvent(builder: flatbuffers.Builder, deviceEvent: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(deviceEvent), 0)

def AddDeviceEvent(builder: flatbuffers.Builder, deviceEvent: int):
    DroneRealtimeV1AddDeviceEvent(builder, deviceEvent)

def DroneRealtimeV1AddGimbalEvent(builder: flatbuffers.Builder, gimbalEvent: int):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(gimbalEvent), 0)

def AddGimbalEvent(builder: flatbuffers.Builder, gimbalEvent: int):
    DroneRealtimeV1AddGimbalEvent(builder, gimbalEvent)

def DroneRealtimeV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return DroneRealtimeV1End(builder)
