from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.realtime.v1.DeviceEventV1 import DeviceEventV1
from baohaus.realtime.v1.GimbalEventV1 import GimbalEventV1

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class DroneRealtimeV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> DroneRealtimeV1: ...
  @classmethod
  def GetRootAsDroneRealtimeV1(cls, buf: bytes, offset: int) -> DroneRealtimeV1: ...
  @classmethod
  def DroneRealtimeV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Channel(self) -> str | None: ...
  def Event(self) -> str | None: ...
  def Timestamp(self) -> str | None: ...
  def BaseUrl(self) -> str | None: ...
  def DeviceEvent(self) -> DeviceEventV1 | None: ...
  def GimbalEvent(self) -> GimbalEventV1 | None: ...
def DroneRealtimeV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def DroneRealtimeV1AddChannel(builder: flatbuffers.Builder, channel: uoffset) -> None: ...
def DroneRealtimeV1AddEvent(builder: flatbuffers.Builder, event: uoffset) -> None: ...
def DroneRealtimeV1AddTimestamp(builder: flatbuffers.Builder, timestamp: uoffset) -> None: ...
def DroneRealtimeV1AddBaseUrl(builder: flatbuffers.Builder, baseUrl: uoffset) -> None: ...
def DroneRealtimeV1AddDeviceEvent(builder: flatbuffers.Builder, deviceEvent: uoffset) -> None: ...
def DroneRealtimeV1AddGimbalEvent(builder: flatbuffers.Builder, gimbalEvent: uoffset) -> None: ...
def DroneRealtimeV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

