from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class GimbalEventV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> GimbalEventV1: ...
  @classmethod
  def GetRootAsGimbalEventV1(cls, buf: bytes, offset: int) -> GimbalEventV1: ...
  @classmethod
  def GimbalEventV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Pitch(self) -> float: ...
  def Yaw(self) -> float: ...
  def Roll(self) -> float: ...
  def Mode(self) -> int: ...
  def Timestamp(self) -> str | None: ...
def GimbalEventV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def GimbalEventV1AddPitch(builder: flatbuffers.Builder, pitch: float) -> None: ...
def GimbalEventV1AddYaw(builder: flatbuffers.Builder, yaw: float) -> None: ...
def GimbalEventV1AddRoll(builder: flatbuffers.Builder, roll: float) -> None: ...
def GimbalEventV1AddMode(builder: flatbuffers.Builder, mode: int) -> None: ...
def GimbalEventV1AddTimestamp(builder: flatbuffers.Builder, timestamp: uoffset) -> None: ...
def GimbalEventV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

