# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class GimbalEventV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GimbalEventV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGimbalEventV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def GimbalEventV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x47\x49\x4D\x31", size_prefixed=size_prefixed)

    # GimbalEventV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GimbalEventV1
    def Pitch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # GimbalEventV1
    def Yaw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # GimbalEventV1
    def Roll(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # GimbalEventV1
    def Mode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # GimbalEventV1
    def Timestamp(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def GimbalEventV1Start(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    GimbalEventV1Start(builder)

def GimbalEventV1AddPitch(builder: flatbuffers.Builder, pitch: float):
    builder.PrependFloat32Slot(0, pitch, 0.0)

def AddPitch(builder: flatbuffers.Builder, pitch: float):
    GimbalEventV1AddPitch(builder, pitch)

def GimbalEventV1AddYaw(builder: flatbuffers.Builder, yaw: float):
    builder.PrependFloat32Slot(1, yaw, 0.0)

def AddYaw(builder: flatbuffers.Builder, yaw: float):
    GimbalEventV1AddYaw(builder, yaw)

def GimbalEventV1AddRoll(builder: flatbuffers.Builder, roll: float):
    builder.PrependFloat32Slot(2, roll, 0.0)

def AddRoll(builder: flatbuffers.Builder, roll: float):
    GimbalEventV1AddRoll(builder, roll)

def GimbalEventV1AddMode(builder: flatbuffers.Builder, mode: int):
    builder.PrependUint8Slot(3, mode, 0)

def AddMode(builder: flatbuffers.Builder, mode: int):
    GimbalEventV1AddMode(builder, mode)

def GimbalEventV1AddTimestamp(builder: flatbuffers.Builder, timestamp: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder: flatbuffers.Builder, timestamp: int):
    GimbalEventV1AddTimestamp(builder, timestamp)

def GimbalEventV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return GimbalEventV1End(builder)
