from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.realtime.v1.HardwareEventKindV1 import HardwareEventKindV1

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class HardwareStateEventV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> HardwareStateEventV1: ...
  @classmethod
  def GetRootAsHardwareStateEventV1(cls, buf: bytes, offset: int) -> HardwareStateEventV1: ...
  @classmethod
  def HardwareStateEventV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def DeviceId(self) -> str | None: ...
  def EventKind(self) -> typing.Literal[HardwareEventKindV1.StateChange, HardwareEventKindV1.SensorReading, HardwareEventKindV1.CommandSent, HardwareEventKindV1.CommandResult, HardwareEventKindV1.CalibrationUpdate, HardwareEventKindV1.HealthTransition]: ...
  def Status(self) -> str | None: ...
  def Metric(self) -> str | None: ...
  def ValueFloat(self) -> float: ...
  def ValueString(self) -> str | None: ...
  def Unit(self) -> str | None: ...
  def Quality(self) -> int: ...
  def Command(self) -> str | None: ...
  def Acknowledged(self) -> bool: ...
  def HealthScore(self) -> float: ...
  def Reason(self) -> str | None: ...
  def CorrelationId(self) -> str | None: ...
  def LatencyMs(self) -> int: ...
  def Timestamp(self) -> str | None: ...
  def MetadataJson(self) -> str | None: ...
def HardwareStateEventV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def HardwareStateEventV1AddDeviceId(builder: flatbuffers.Builder, deviceId: uoffset) -> None: ...
def HardwareStateEventV1AddEventKind(builder: flatbuffers.Builder, eventKind: typing.Literal[HardwareEventKindV1.StateChange, HardwareEventKindV1.SensorReading, HardwareEventKindV1.CommandSent, HardwareEventKindV1.CommandResult, HardwareEventKindV1.CalibrationUpdate, HardwareEventKindV1.HealthTransition]) -> None: ...
def HardwareStateEventV1AddStatus(builder: flatbuffers.Builder, status: uoffset) -> None: ...
def HardwareStateEventV1AddMetric(builder: flatbuffers.Builder, metric: uoffset) -> None: ...
def HardwareStateEventV1AddValueFloat(builder: flatbuffers.Builder, valueFloat: float) -> None: ...
def HardwareStateEventV1AddValueString(builder: flatbuffers.Builder, valueString: uoffset) -> None: ...
def HardwareStateEventV1AddUnit(builder: flatbuffers.Builder, unit: uoffset) -> None: ...
def HardwareStateEventV1AddQuality(builder: flatbuffers.Builder, quality: int) -> None: ...
def HardwareStateEventV1AddCommand(builder: flatbuffers.Builder, command: uoffset) -> None: ...
def HardwareStateEventV1AddAcknowledged(builder: flatbuffers.Builder, acknowledged: bool) -> None: ...
def HardwareStateEventV1AddHealthScore(builder: flatbuffers.Builder, healthScore: float) -> None: ...
def HardwareStateEventV1AddReason(builder: flatbuffers.Builder, reason: uoffset) -> None: ...
def HardwareStateEventV1AddCorrelationId(builder: flatbuffers.Builder, correlationId: uoffset) -> None: ...
def HardwareStateEventV1AddLatencyMs(builder: flatbuffers.Builder, latencyMs: int) -> None: ...
def HardwareStateEventV1AddTimestamp(builder: flatbuffers.Builder, timestamp: uoffset) -> None: ...
def HardwareStateEventV1AddMetadataJson(builder: flatbuffers.Builder, metadataJson: uoffset) -> None: ...
def HardwareStateEventV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

