# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class HardwareEventKindV1(object):
    StateChange = 0
    SensorReading = 1
    CommandSent = 2
    CommandResult = 3
    CalibrationUpdate = 4
    HealthTransition = 5
