# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class HardwareStateEventV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HardwareStateEventV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHardwareStateEventV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def HardwareStateEventV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x48\x57\x53\x31", size_prefixed=size_prefixed)

    # HardwareStateEventV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HardwareStateEventV1
    def DeviceId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HardwareStateEventV1
    def EventKind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # HardwareStateEventV1
    def Status(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HardwareStateEventV1
    def Metric(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HardwareStateEventV1
    def ValueFloat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # HardwareStateEventV1
    def ValueString(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HardwareStateEventV1
    def Unit(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HardwareStateEventV1
    def Quality(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # HardwareStateEventV1
    def Command(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HardwareStateEventV1
    def Acknowledged(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # HardwareStateEventV1
    def HealthScore(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # HardwareStateEventV1
    def Reason(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HardwareStateEventV1
    def CorrelationId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HardwareStateEventV1
    def LatencyMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # HardwareStateEventV1
    def Timestamp(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HardwareStateEventV1
    def MetadataJson(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def HardwareStateEventV1Start(builder: flatbuffers.Builder):
    builder.StartObject(16)

def Start(builder: flatbuffers.Builder):
    HardwareStateEventV1Start(builder)

def HardwareStateEventV1AddDeviceId(builder: flatbuffers.Builder, deviceId: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(deviceId), 0)

def AddDeviceId(builder: flatbuffers.Builder, deviceId: int):
    HardwareStateEventV1AddDeviceId(builder, deviceId)

def HardwareStateEventV1AddEventKind(builder: flatbuffers.Builder, eventKind: int):
    builder.PrependUint8Slot(1, eventKind, 0)

def AddEventKind(builder: flatbuffers.Builder, eventKind: int):
    HardwareStateEventV1AddEventKind(builder, eventKind)

def HardwareStateEventV1AddStatus(builder: flatbuffers.Builder, status: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(status), 0)

def AddStatus(builder: flatbuffers.Builder, status: int):
    HardwareStateEventV1AddStatus(builder, status)

def HardwareStateEventV1AddMetric(builder: flatbuffers.Builder, metric: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(metric), 0)

def AddMetric(builder: flatbuffers.Builder, metric: int):
    HardwareStateEventV1AddMetric(builder, metric)

def HardwareStateEventV1AddValueFloat(builder: flatbuffers.Builder, valueFloat: float):
    builder.PrependFloat32Slot(4, valueFloat, 0.0)

def AddValueFloat(builder: flatbuffers.Builder, valueFloat: float):
    HardwareStateEventV1AddValueFloat(builder, valueFloat)

def HardwareStateEventV1AddValueString(builder: flatbuffers.Builder, valueString: int):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(valueString), 0)

def AddValueString(builder: flatbuffers.Builder, valueString: int):
    HardwareStateEventV1AddValueString(builder, valueString)

def HardwareStateEventV1AddUnit(builder: flatbuffers.Builder, unit: int):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(unit), 0)

def AddUnit(builder: flatbuffers.Builder, unit: int):
    HardwareStateEventV1AddUnit(builder, unit)

def HardwareStateEventV1AddQuality(builder: flatbuffers.Builder, quality: int):
    builder.PrependUint8Slot(7, quality, 0)

def AddQuality(builder: flatbuffers.Builder, quality: int):
    HardwareStateEventV1AddQuality(builder, quality)

def HardwareStateEventV1AddCommand(builder: flatbuffers.Builder, command: int):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(command), 0)

def AddCommand(builder: flatbuffers.Builder, command: int):
    HardwareStateEventV1AddCommand(builder, command)

def HardwareStateEventV1AddAcknowledged(builder: flatbuffers.Builder, acknowledged: bool):
    builder.PrependBoolSlot(9, acknowledged, 0)

def AddAcknowledged(builder: flatbuffers.Builder, acknowledged: bool):
    HardwareStateEventV1AddAcknowledged(builder, acknowledged)

def HardwareStateEventV1AddHealthScore(builder: flatbuffers.Builder, healthScore: float):
    builder.PrependFloat32Slot(10, healthScore, 0.0)

def AddHealthScore(builder: flatbuffers.Builder, healthScore: float):
    HardwareStateEventV1AddHealthScore(builder, healthScore)

def HardwareStateEventV1AddReason(builder: flatbuffers.Builder, reason: int):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(reason), 0)

def AddReason(builder: flatbuffers.Builder, reason: int):
    HardwareStateEventV1AddReason(builder, reason)

def HardwareStateEventV1AddCorrelationId(builder: flatbuffers.Builder, correlationId: int):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(correlationId), 0)

def AddCorrelationId(builder: flatbuffers.Builder, correlationId: int):
    HardwareStateEventV1AddCorrelationId(builder, correlationId)

def HardwareStateEventV1AddLatencyMs(builder: flatbuffers.Builder, latencyMs: int):
    builder.PrependUint32Slot(13, latencyMs, 0)

def AddLatencyMs(builder: flatbuffers.Builder, latencyMs: int):
    HardwareStateEventV1AddLatencyMs(builder, latencyMs)

def HardwareStateEventV1AddTimestamp(builder: flatbuffers.Builder, timestamp: int):
    builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder: flatbuffers.Builder, timestamp: int):
    HardwareStateEventV1AddTimestamp(builder, timestamp)

def HardwareStateEventV1AddMetadataJson(builder: flatbuffers.Builder, metadataJson: int):
    builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(metadataJson), 0)

def AddMetadataJson(builder: flatbuffers.Builder, metadataJson: int):
    HardwareStateEventV1AddMetadataJson(builder, metadataJson)

def HardwareStateEventV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return HardwareStateEventV1End(builder)
