from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Position3D(object):
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def Latitude(self) -> float: ...
  def Longitude(self) -> float: ...
  def Altitude(self) -> float: ...
  def RelativeAltitude(self) -> float: ...

def CreatePosition3D(builder: flatbuffers.Builder, latitude: float, longitude: float, altitude: float, relativeAltitude: float) -> uoffset: ...

