# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

# Message kind for wrapped realtime payloads.
class RealtimePayloadKindV1(object):
    NONE = 0
    DRONE_REALTIME = 1
    SCANNER_PROGRESS = 2
    TELEMETRY_TYPED = 3
