from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ScannerProgressV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ScannerProgressV1: ...
  @classmethod
  def GetRootAsScannerProgressV1(cls, buf: bytes, offset: int) -> ScannerProgressV1: ...
  @classmethod
  def ScannerProgressV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def ScanId(self) -> str | None: ...
  def Phase(self) -> str | None: ...
  def CurrentStep(self) -> int: ...
  def TotalSteps(self) -> int: ...
  def Percentage(self) -> float: ...
  def Message(self) -> str | None: ...
  def Timestamp(self) -> str | None: ...
def ScannerProgressV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def ScannerProgressV1AddScanId(builder: flatbuffers.Builder, scanId: uoffset) -> None: ...
def ScannerProgressV1AddPhase(builder: flatbuffers.Builder, phase: uoffset) -> None: ...
def ScannerProgressV1AddCurrentStep(builder: flatbuffers.Builder, currentStep: int) -> None: ...
def ScannerProgressV1AddTotalSteps(builder: flatbuffers.Builder, totalSteps: int) -> None: ...
def ScannerProgressV1AddPercentage(builder: flatbuffers.Builder, percentage: float) -> None: ...
def ScannerProgressV1AddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def ScannerProgressV1AddTimestamp(builder: flatbuffers.Builder, timestamp: uoffset) -> None: ...
def ScannerProgressV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

