# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

# Internal scanner progress payload for high-frequency transport.
# Evolution policy: append-only fields, deprecate instead of deleting.
class ScannerProgressV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ScannerProgressV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsScannerProgressV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ScannerProgressV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x43\x56\x31", size_prefixed=size_prefixed)

    # ScannerProgressV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ScannerProgressV1
    def ScanId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScannerProgressV1
    def Phase(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScannerProgressV1
    def CurrentStep(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ScannerProgressV1
    def TotalSteps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ScannerProgressV1
    def Percentage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ScannerProgressV1
    def Message(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScannerProgressV1
    def Timestamp(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ScannerProgressV1Start(builder: flatbuffers.Builder):
    builder.StartObject(7)

def Start(builder: flatbuffers.Builder):
    ScannerProgressV1Start(builder)

def ScannerProgressV1AddScanId(builder: flatbuffers.Builder, scanId: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(scanId), 0)

def AddScanId(builder: flatbuffers.Builder, scanId: int):
    ScannerProgressV1AddScanId(builder, scanId)

def ScannerProgressV1AddPhase(builder: flatbuffers.Builder, phase: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(phase), 0)

def AddPhase(builder: flatbuffers.Builder, phase: int):
    ScannerProgressV1AddPhase(builder, phase)

def ScannerProgressV1AddCurrentStep(builder: flatbuffers.Builder, currentStep: int):
    builder.PrependUint32Slot(2, currentStep, 0)

def AddCurrentStep(builder: flatbuffers.Builder, currentStep: int):
    ScannerProgressV1AddCurrentStep(builder, currentStep)

def ScannerProgressV1AddTotalSteps(builder: flatbuffers.Builder, totalSteps: int):
    builder.PrependUint32Slot(3, totalSteps, 0)

def AddTotalSteps(builder: flatbuffers.Builder, totalSteps: int):
    ScannerProgressV1AddTotalSteps(builder, totalSteps)

def ScannerProgressV1AddPercentage(builder: flatbuffers.Builder, percentage: float):
    builder.PrependFloat32Slot(4, percentage, 0.0)

def AddPercentage(builder: flatbuffers.Builder, percentage: float):
    ScannerProgressV1AddPercentage(builder, percentage)

def ScannerProgressV1AddMessage(builder: flatbuffers.Builder, message: int):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder: flatbuffers.Builder, message: int):
    ScannerProgressV1AddMessage(builder, message)

def ScannerProgressV1AddTimestamp(builder: flatbuffers.Builder, timestamp: int):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder: flatbuffers.Builder, timestamp: int):
    ScannerProgressV1AddTimestamp(builder, timestamp)

def ScannerProgressV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return ScannerProgressV1End(builder)
