# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
from baohaus.realtime.v1.Attitude import Attitude
from baohaus.realtime.v1.BatteryStatus import BatteryStatus
from baohaus.realtime.v1.Position3D import Position3D
from baohaus.realtime.v1.Velocity3D import Velocity3D
np = import_numpy()

class TelemetryPayloadV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TelemetryPayloadV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTelemetryPayloadV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def TelemetryPayloadV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x50\x56\x31", size_prefixed=size_prefixed)

    # TelemetryPayloadV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TelemetryPayloadV1
    def VehicleId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TelemetryPayloadV1
    def Timestamp(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TelemetryPayloadV1
    def ConnectionState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TelemetryPayloadV1
    def Armed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TelemetryPayloadV1
    def FlightMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TelemetryPayloadV1
    def Position(self) -> Optional[Position3D]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            obj = Position3D()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TelemetryPayloadV1
    def Attitude(self) -> Optional[Attitude]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            obj = Attitude()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TelemetryPayloadV1
    def Velocity(self) -> Optional[Velocity3D]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = o + self._tab.Pos
            obj = Velocity3D()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TelemetryPayloadV1
    def GpsFixType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TelemetryPayloadV1
    def SatelliteCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TelemetryPayloadV1
    def Battery(self) -> Optional[BatteryStatus]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = o + self._tab.Pos
            obj = BatteryStatus()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TelemetryPayloadV1
    def SignalStrength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # TelemetryPayloadV1
    def FlightTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def TelemetryPayloadV1Start(builder: flatbuffers.Builder):
    builder.StartObject(14)

def Start(builder: flatbuffers.Builder):
    TelemetryPayloadV1Start(builder)

def TelemetryPayloadV1AddVehicleId(builder: flatbuffers.Builder, vehicleId: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(vehicleId), 0)

def AddVehicleId(builder: flatbuffers.Builder, vehicleId: int):
    TelemetryPayloadV1AddVehicleId(builder, vehicleId)

def TelemetryPayloadV1AddTimestamp(builder: flatbuffers.Builder, timestamp: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder: flatbuffers.Builder, timestamp: int):
    TelemetryPayloadV1AddTimestamp(builder, timestamp)

def TelemetryPayloadV1AddConnectionState(builder: flatbuffers.Builder, connectionState: int):
    builder.PrependUint8Slot(2, connectionState, 0)

def AddConnectionState(builder: flatbuffers.Builder, connectionState: int):
    TelemetryPayloadV1AddConnectionState(builder, connectionState)

def TelemetryPayloadV1AddArmed(builder: flatbuffers.Builder, armed: bool):
    builder.PrependBoolSlot(3, armed, 0)

def AddArmed(builder: flatbuffers.Builder, armed: bool):
    TelemetryPayloadV1AddArmed(builder, armed)

def TelemetryPayloadV1AddFlightMode(builder: flatbuffers.Builder, flightMode: int):
    builder.PrependUint8Slot(4, flightMode, 0)

def AddFlightMode(builder: flatbuffers.Builder, flightMode: int):
    TelemetryPayloadV1AddFlightMode(builder, flightMode)

def TelemetryPayloadV1AddPosition(builder: flatbuffers.Builder, position: Any):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(position), 0)

def AddPosition(builder: flatbuffers.Builder, position: Any):
    TelemetryPayloadV1AddPosition(builder, position)

def TelemetryPayloadV1AddAttitude(builder: flatbuffers.Builder, attitude: Any):
    builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(attitude), 0)

def AddAttitude(builder: flatbuffers.Builder, attitude: Any):
    TelemetryPayloadV1AddAttitude(builder, attitude)

def TelemetryPayloadV1AddVelocity(builder: flatbuffers.Builder, velocity: Any):
    builder.PrependStructSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(velocity), 0)

def AddVelocity(builder: flatbuffers.Builder, velocity: Any):
    TelemetryPayloadV1AddVelocity(builder, velocity)

def TelemetryPayloadV1AddGpsFixType(builder: flatbuffers.Builder, gpsFixType: int):
    builder.PrependUint8Slot(8, gpsFixType, 0)

def AddGpsFixType(builder: flatbuffers.Builder, gpsFixType: int):
    TelemetryPayloadV1AddGpsFixType(builder, gpsFixType)

def TelemetryPayloadV1AddSatelliteCount(builder: flatbuffers.Builder, satelliteCount: int):
    builder.PrependUint8Slot(9, satelliteCount, 0)

def AddSatelliteCount(builder: flatbuffers.Builder, satelliteCount: int):
    TelemetryPayloadV1AddSatelliteCount(builder, satelliteCount)

def TelemetryPayloadV1AddBattery(builder: flatbuffers.Builder, battery: Any):
    builder.PrependStructSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(battery), 0)

def AddBattery(builder: flatbuffers.Builder, battery: Any):
    TelemetryPayloadV1AddBattery(builder, battery)

def TelemetryPayloadV1AddSignalStrength(builder: flatbuffers.Builder, signalStrength: float):
    builder.PrependFloat32Slot(11, signalStrength, 0.0)

def AddSignalStrength(builder: flatbuffers.Builder, signalStrength: float):
    TelemetryPayloadV1AddSignalStrength(builder, signalStrength)

def TelemetryPayloadV1AddFlightTime(builder: flatbuffers.Builder, flightTime: float):
    builder.PrependFloat32Slot(12, flightTime, 0.0)

def AddFlightTime(builder: flatbuffers.Builder, flightTime: float):
    TelemetryPayloadV1AddFlightTime(builder, flightTime)

def TelemetryPayloadV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return TelemetryPayloadV1End(builder)
