from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.realtime.v1.Attitude import Attitude
from baohaus.realtime.v1.BatteryStatus import BatteryStatus
from baohaus.realtime.v1.Position3D import Position3D
from baohaus.realtime.v1.Velocity3D import Velocity3D

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class TelemetryPayloadV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TelemetryPayloadV1: ...
  @classmethod
  def GetRootAsTelemetryPayloadV1(cls, buf: bytes, offset: int) -> TelemetryPayloadV1: ...
  @classmethod
  def TelemetryPayloadV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def VehicleId(self) -> str | None: ...
  def Timestamp(self) -> str | None: ...
  def ConnectionState(self) -> int: ...
  def Armed(self) -> bool: ...
  def FlightMode(self) -> int: ...
  def Position(self) -> Position3D | None: ...
  def Attitude(self) -> Attitude | None: ...
  def Velocity(self) -> Velocity3D | None: ...
  def GpsFixType(self) -> int: ...
  def SatelliteCount(self) -> int: ...
  def Battery(self) -> BatteryStatus | None: ...
  def SignalStrength(self) -> float: ...
  def FlightTime(self) -> float: ...
def TelemetryPayloadV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def TelemetryPayloadV1AddVehicleId(builder: flatbuffers.Builder, vehicleId: uoffset) -> None: ...
def TelemetryPayloadV1AddTimestamp(builder: flatbuffers.Builder, timestamp: uoffset) -> None: ...
def TelemetryPayloadV1AddConnectionState(builder: flatbuffers.Builder, connectionState: int) -> None: ...
def TelemetryPayloadV1AddArmed(builder: flatbuffers.Builder, armed: bool) -> None: ...
def TelemetryPayloadV1AddFlightMode(builder: flatbuffers.Builder, flightMode: int) -> None: ...
def TelemetryPayloadV1AddPosition(builder: flatbuffers.Builder, position: uoffset) -> None: ...
def TelemetryPayloadV1AddAttitude(builder: flatbuffers.Builder, attitude: uoffset) -> None: ...
def TelemetryPayloadV1AddVelocity(builder: flatbuffers.Builder, velocity: uoffset) -> None: ...
def TelemetryPayloadV1AddGpsFixType(builder: flatbuffers.Builder, gpsFixType: int) -> None: ...
def TelemetryPayloadV1AddSatelliteCount(builder: flatbuffers.Builder, satelliteCount: int) -> None: ...
def TelemetryPayloadV1AddBattery(builder: flatbuffers.Builder, battery: uoffset) -> None: ...
def TelemetryPayloadV1AddSignalStrength(builder: flatbuffers.Builder, signalStrength: float) -> None: ...
def TelemetryPayloadV1AddFlightTime(builder: flatbuffers.Builder, flightTime: float) -> None: ...
def TelemetryPayloadV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

