from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Velocity3D(object):
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def X(self) -> float: ...
  def Y(self) -> float: ...
  def Z(self) -> float: ...
  def GroundSpeed(self) -> float: ...
  def AirSpeed(self) -> float: ...

def CreateVelocity3D(builder: flatbuffers.Builder, x: float, y: float, z: float, groundSpeed: float, airSpeed: float) -> uoffset: ...

