# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

# Generic wrapper for internal binary websocket transport.
# `payload` contains a nested FlatBuffer payload chosen by `kind`.
class WsEnvelopeV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WsEnvelopeV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWsEnvelopeV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def WsEnvelopeV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x57\x53\x56\x31", size_prefixed=size_prefixed)

    # WsEnvelopeV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WsEnvelopeV1
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 1

    # WsEnvelopeV1
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # WsEnvelopeV1
    def Payload(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # WsEnvelopeV1
    def PayloadAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # WsEnvelopeV1
    def PayloadLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WsEnvelopeV1
    def PayloadIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # WsEnvelopeV1
    def Timestamp(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Optional schema version for debug and compatibility checks.
    # WsEnvelopeV1
    def SchemaVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 1

    # Optional generation timestamp (ISO 8601) for debugging.
    # WsEnvelopeV1
    def GenerationTimestamp(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def WsEnvelopeV1Start(builder: flatbuffers.Builder):
    builder.StartObject(6)

def Start(builder: flatbuffers.Builder):
    WsEnvelopeV1Start(builder)

def WsEnvelopeV1AddVersion(builder: flatbuffers.Builder, version: int):
    builder.PrependUint16Slot(0, version, 1)

def AddVersion(builder: flatbuffers.Builder, version: int):
    WsEnvelopeV1AddVersion(builder, version)

def WsEnvelopeV1AddKind(builder: flatbuffers.Builder, kind: int):
    builder.PrependUint8Slot(1, kind, 0)

def AddKind(builder: flatbuffers.Builder, kind: int):
    WsEnvelopeV1AddKind(builder, kind)

def WsEnvelopeV1AddPayload(builder: flatbuffers.Builder, payload: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)

def AddPayload(builder: flatbuffers.Builder, payload: int):
    WsEnvelopeV1AddPayload(builder, payload)

def WsEnvelopeV1StartPayloadVector(builder, numElems: int) -> int:
    return builder.StartVector(1, numElems, 1)

def StartPayloadVector(builder, numElems: int) -> int:
    return WsEnvelopeV1StartPayloadVector(builder, numElems)

def WsEnvelopeV1AddTimestamp(builder: flatbuffers.Builder, timestamp: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder: flatbuffers.Builder, timestamp: int):
    WsEnvelopeV1AddTimestamp(builder, timestamp)

def WsEnvelopeV1AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: int):
    builder.PrependUint32Slot(4, schemaVersion, 1)

def AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: int):
    WsEnvelopeV1AddSchemaVersion(builder, schemaVersion)

def WsEnvelopeV1AddGenerationTimestamp(builder: flatbuffers.Builder, generationTimestamp: int):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(generationTimestamp), 0)

def AddGenerationTimestamp(builder: flatbuffers.Builder, generationTimestamp: int):
    WsEnvelopeV1AddGenerationTimestamp(builder, generationTimestamp)

def WsEnvelopeV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return WsEnvelopeV1End(builder)
