from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.realtime.v1.RealtimePayloadKindV1 import RealtimePayloadKindV1

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class WsEnvelopeV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> WsEnvelopeV1: ...
  @classmethod
  def GetRootAsWsEnvelopeV1(cls, buf: bytes, offset: int) -> WsEnvelopeV1: ...
  @classmethod
  def WsEnvelopeV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Version(self) -> int: ...
  def Kind(self) -> typing.Literal[RealtimePayloadKindV1.NONE, RealtimePayloadKindV1.DRONE_REALTIME, RealtimePayloadKindV1.SCANNER_PROGRESS, RealtimePayloadKindV1.TELEMETRY_TYPED]: ...
  def Payload(self, i: int) -> typing.List[int]: ...
  def PayloadAsNumpy(self) -> np.ndarray: ...
  def PayloadLength(self) -> int: ...
  def PayloadIsNone(self) -> bool: ...
  def Timestamp(self) -> str | None: ...
  def SchemaVersion(self) -> int: ...
  def GenerationTimestamp(self) -> str | None: ...
def WsEnvelopeV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def WsEnvelopeV1AddVersion(builder: flatbuffers.Builder, version: int) -> None: ...
def WsEnvelopeV1AddKind(builder: flatbuffers.Builder, kind: typing.Literal[RealtimePayloadKindV1.NONE, RealtimePayloadKindV1.DRONE_REALTIME, RealtimePayloadKindV1.SCANNER_PROGRESS, RealtimePayloadKindV1.TELEMETRY_TYPED]) -> None: ...
def WsEnvelopeV1AddPayload(builder: flatbuffers.Builder, payload: uoffset) -> None: ...
def WsEnvelopeV1StartPayloadVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartPayloadVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def WsEnvelopeV1AddTimestamp(builder: flatbuffers.Builder, timestamp: uoffset) -> None: ...
def WsEnvelopeV1AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: int) -> None: ...
def WsEnvelopeV1AddGenerationTimestamp(builder: flatbuffers.Builder, generationTimestamp: uoffset) -> None: ...
def WsEnvelopeV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

