import type { BaoInstallTargetKind } from "./bao-install/core.schemas.ts";
import {
  baoRuntimeWorkloadTargetSchema,
  configOverlayTargetSchema,
  ociImageTargetSchema,
  uiComponentKitTargetSchema,
  usdSceneTargetSchema,
} from "./bao-target-payload-distribution.schemas.ts";
import {
  apiGroupTargetSchema,
  baodownNodeTargetSchema,
  baoPackageTargetSchema,
  betterAuthExtensionTargetSchema,
  bunPluginTargetSchema,
  densityPresetTargetSchema,
  designTokensTargetSchema,
  elysiaPluginTargetSchema,
  htmxExtensionTargetSchema,
  mcpProviderTargetSchema,
  motionPresetTargetSchema,
  navTargetSchema,
  paletteEntryGroupTargetSchema,
  prismaExtensionTargetSchema,
  settingsTabTargetSchema,
  sidebarTargetSchema,
  themePackTargetSchema,
  tileGroupTargetSchema,
  topbarTargetSchema,
} from "./bao-target-payload-extension.schemas.ts";
import {
  aiModelTargetSchema,
  baodownFlowTargetSchema,
  bunbuddyContractTargetSchema,
  flatbufferSchemaTargetSchema,
  hardwareDriverTargetSchema,
} from "./bao-target-payload-platform.schemas.ts";

export const TARGET_PAYLOAD_SCHEMAS = {
  "bao-package": baoPackageTargetSchema,
  "htmx-extension": htmxExtensionTargetSchema,
  "prisma-extension": prismaExtensionTargetSchema,
  "better-auth-extension": betterAuthExtensionTargetSchema,
  "elysia-plugin": elysiaPluginTargetSchema,
  "baodown-node": baodownNodeTargetSchema,
  "mcp-provider": mcpProviderTargetSchema,
  "bun-plugin": bunPluginTargetSchema,
  "flatbuffer-schema": flatbufferSchemaTargetSchema,
  "hardware-driver": hardwareDriverTargetSchema,
  "ai-model": aiModelTargetSchema,
  "baodown-flow": baodownFlowTargetSchema,
  "bunbuddy-contract": bunbuddyContractTargetSchema,
  "bao-runtime-workload": baoRuntimeWorkloadTargetSchema,
  "config-overlay": configOverlayTargetSchema,
  "oci-image": ociImageTargetSchema,
  "usd-scene": usdSceneTargetSchema,
  "ui-component-kit": uiComponentKitTargetSchema,
  "theme-pack": themePackTargetSchema,
  "design-tokens": designTokensTargetSchema,
  "motion-preset": motionPresetTargetSchema,
  "density-preset": densityPresetTargetSchema,
  sidebar: sidebarTargetSchema,
  nav: navTargetSchema,
  "settings-tab": settingsTabTargetSchema,
  "palette-entry-group": paletteEntryGroupTargetSchema,
  "api-group": apiGroupTargetSchema,
  "tile-group": tileGroupTargetSchema,
  topbar: topbarTargetSchema,
} satisfies Record<BaoInstallTargetKind, object>;
