/**
 * Capability route definitions for hardware-adjacent capabilities.
 *
 * @shared/contracts/versions/v1/capability/routes-hardware
 */

import { API_PATHS } from "@baohaus/bao-constants/api-paths";
import type { ApiRouteDefinition } from "./core";
import {
  BUNBUDDIES_BASE,
  CALIBRATION_BASE,
  DEVICES_BASE,
  DRIVERS_BASE,
  FOOTPEDAL_BASE,
  HARDWARE_BASE,
  IMAGER_BASE,
  INDUSTRIAL_BASE,
  IOT_BASE,
  LIGHTING_BASE,
  MCP_HARDWARE_CONTEXT,
  MCP_RESOURCES_BASE,
  MCP_TOOLS_BASE,
  NETWORK_BASE,
  PRINTER_BASE,
} from "./core";

export const HARDWARE_ROUTE_DEFINITIONS_V1: readonly ApiRouteDefinition[] = [
  { method: "GET", path: API_PATHS.hardwarePolicies },
  { method: "POST", path: API_PATHS.hardwareLifecycleEnroll },
  { method: "POST", path: API_PATHS.hardwareLifecycleProvision },
  { method: "GET", path: CALIBRATION_BASE },
  { method: "GET", path: `${CALIBRATION_BASE}/:id` },
  { method: "POST", path: `${CALIBRATION_BASE}/run` },
  { method: "POST", path: `${CALIBRATION_BASE}/jobs` },
  { method: "GET", path: `${CALIBRATION_BASE}/jobs/:jobId` },
  { method: "GET", path: `${CALIBRATION_BASE}/status` },
  { method: "GET", path: DEVICES_BASE },
  { method: "GET", path: `${DEVICES_BASE}/:deviceId` },
  { method: "POST", path: `${DEVICES_BASE}/:deviceId/assign` },
  { method: "GET", path: `${DEVICES_BASE}/:deviceId/drivers` },
  { method: "POST", path: `${DEVICES_BASE}/:deviceId/drivers/:packageName/install` },
  { method: "GET", path: `${DEVICES_BASE}/:deviceId/events` },
  { method: "GET", path: `${DEVICES_BASE}/:deviceId/status` },
  { method: "POST", path: `${DEVICES_BASE}/:deviceId/unassign` },
  { method: "GET", path: `${DEVICES_BASE}/:deviceId/usage` },
  { method: "GET", path: `${DEVICES_BASE}/assignments` },
  { method: "GET", path: `${DEVICES_BASE}/assignments/options` },
  { method: "GET", path: `${DEVICES_BASE}/basler` },
  { method: "GET", path: `${DEVICES_BASE}/bluetooth` },
  { method: "GET", path: `${DEVICES_BASE}/csi` },
  { method: "POST", path: `${DEVICES_BASE}/detect` },
  { method: "GET", path: `${DEVICES_BASE}/detect/stream` },
  { method: "POST", path: `${DEVICES_BASE}/inventory/refresh` },
  { method: "GET", path: `${DEVICES_BASE}/diagnostics` },
  { method: "POST", path: `${DEVICES_BASE}/enumerate` },
  { method: "GET", path: `${DEVICES_BASE}/imagers` },
  { method: "POST", path: `${DEVICES_BASE}/imagers/:deviceId/capture` },
  { method: "POST", path: `${DEVICES_BASE}/lighting/:deviceId/:action` },
  { method: "POST", path: `${DEVICES_BASE}/microscope/:deviceId/:action` },
  { method: "GET", path: `${DEVICES_BASE}/serial` },
  { method: "GET", path: `${DEVICES_BASE}/status` },
  { method: "GET", path: DRIVERS_BASE },
  { method: "GET", path: `${FOOTPEDAL_BASE}/actions` },
  { method: "POST", path: `${FOOTPEDAL_BASE}/devices/:id/action` },
  { method: "POST", path: `${FOOTPEDAL_BASE}/enumerate` },
  { method: "GET", path: `${FOOTPEDAL_BASE}/health` },
  { method: "GET", path: `${FOOTPEDAL_BASE}/status` },
  { method: "GET", path: `${HARDWARE_BASE}/summary` },
  { method: "GET", path: `${HARDWARE_BASE}/integration` },
  { method: "GET", path: `${NETWORK_BASE}/protocols` },
  { method: "POST", path: `${NETWORK_BASE}/discover` },
  { method: "POST", path: `${NETWORK_BASE}/discover/onvif` },
  { method: "POST", path: `${NETWORK_BASE}/discover/mdns` },
  { method: "POST", path: `${NETWORK_BASE}/discover/ssdp` },
  { method: "POST", path: `${NETWORK_BASE}/discover/cameras` },
  { method: "POST", path: `${NETWORK_BASE}/discover/categorized` },
  { method: "POST", path: `${IMAGER_BASE}/autofocus` },
  { method: "POST", path: `${IMAGER_BASE}/calibrate` },
  { method: "POST", path: `${IMAGER_BASE}/quality` },
  { method: "POST", path: `${IMAGER_BASE}/preprocess` },
  { method: "POST", path: `${IMAGER_BASE}/rectify` },
  { method: "POST", path: `${IMAGER_BASE}/sync-capture` },
  { method: "POST", path: `${IMAGER_BASE}/assets` },
  { method: "POST", path: `${IMAGER_BASE}/enumerate` },
  { method: "GET", path: `${IMAGER_BASE}/health` },
  { method: "GET", path: `${IMAGER_BASE}/preview/:deviceId` },
  { method: "GET", path: `${IMAGER_BASE}/preview/:deviceId/snapshot` },
  { method: "GET", path: `${IMAGER_BASE}/status` },
  { method: "GET", path: `${INDUSTRIAL_BASE}/devices` },
  { method: "POST", path: `${INDUSTRIAL_BASE}/devices` },
  { method: "DELETE", path: `${INDUSTRIAL_BASE}/devices/:deviceId` },
  { method: "GET", path: `${INDUSTRIAL_BASE}/devices/:deviceId` },
  { method: "PATCH", path: `${INDUSTRIAL_BASE}/devices/:deviceId` },
  { method: "POST", path: `${INDUSTRIAL_BASE}/devices/:deviceId/connect` },
  { method: "POST", path: `${INDUSTRIAL_BASE}/devices/:deviceId/disconnect` },
  { method: "POST", path: `${INDUSTRIAL_BASE}/enumerate` },
  { method: "GET", path: `${INDUSTRIAL_BASE}/metrics` },
  { method: "POST", path: `${INDUSTRIAL_BASE}/modbus/:deviceId/coils/:address` },
  { method: "GET", path: `${INDUSTRIAL_BASE}/modbus/:deviceId/coils/:address/:count` },
  { method: "GET", path: `${INDUSTRIAL_BASE}/modbus/:deviceId/discrete/:address/:count` },
  { method: "POST", path: `${INDUSTRIAL_BASE}/modbus/:deviceId/holding/:address` },
  { method: "GET", path: `${INDUSTRIAL_BASE}/modbus/:deviceId/holding/:address/:count` },
  { method: "GET", path: `${INDUSTRIAL_BASE}/modbus/:deviceId/input/:address/:count` },
  { method: "GET", path: `${INDUSTRIAL_BASE}/modbus/status` },
  { method: "POST", path: `${INDUSTRIAL_BASE}/scan` },
  { method: "GET", path: `${INDUSTRIAL_BASE}/status` },
  { method: "GET", path: `${IOT_BASE}/devices` },
  { method: "GET", path: `${IOT_BASE}/devices/:sensorId` },
  { method: "POST", path: `${IOT_BASE}/enumerate` },
  { method: "GET", path: `${IOT_BASE}/metrics` },
  { method: "GET", path: `${IOT_BASE}/outputs` },
  { method: "POST", path: `${IOT_BASE}/outputs` },
  { method: "DELETE", path: `${IOT_BASE}/outputs/:outputId` },
  { method: "GET", path: `${IOT_BASE}/outputs/:outputId` },
  { method: "POST", path: `${IOT_BASE}/outputs/:outputId/state` },
  { method: "POST", path: `${IOT_BASE}/scan` },
  { method: "GET", path: `${IOT_BASE}/sensors` },
  { method: "POST", path: `${IOT_BASE}/sensors` },
  { method: "DELETE", path: `${IOT_BASE}/sensors/:sensorId` },
  { method: "GET", path: `${IOT_BASE}/sensors/:sensorId` },
  { method: "GET", path: `${IOT_BASE}/sensors/:sensorId/history` },
  { method: "GET", path: `${IOT_BASE}/sensors/:sensorId/reading` },
  { method: "GET", path: `${IOT_BASE}/status` },
  { method: "GET", path: `${LIGHTING_BASE}/devices` },
  { method: "POST", path: `${LIGHTING_BASE}/devices` },
  { method: "DELETE", path: `${LIGHTING_BASE}/devices/:deviceId` },
  { method: "GET", path: `${LIGHTING_BASE}/devices/:deviceId` },
  { method: "PATCH", path: `${LIGHTING_BASE}/devices/:deviceId` },
  { method: "POST", path: `${LIGHTING_BASE}/enumerate` },
  { method: "GET", path: `${LIGHTING_BASE}/health` },
  { method: "GET", path: `${LIGHTING_BASE}/metrics` },
  { method: "POST", path: `${LIGHTING_BASE}/scan` },
  { method: "GET", path: `${LIGHTING_BASE}/settings` },
  { method: "GET", path: `${LIGHTING_BASE}/status` },
  { method: "GET", path: MCP_HARDWARE_CONTEXT },
  { method: "GET", path: MCP_RESOURCES_BASE },
  { method: "GET", path: `${MCP_RESOURCES_BASE}/:encoded` },
  { method: "GET", path: MCP_TOOLS_BASE },
  { method: "POST", path: `${MCP_TOOLS_BASE}/:name` },
  { method: "GET", path: `${PRINTER_BASE}/devices` },
  { method: "POST", path: `${PRINTER_BASE}/devices` },
  { method: "DELETE", path: `${PRINTER_BASE}/devices/:printerId` },
  { method: "GET", path: `${PRINTER_BASE}/devices/:printerId` },
  { method: "POST", path: `${PRINTER_BASE}/enumerate` },
  { method: "GET", path: `${PRINTER_BASE}/jobs` },
  { method: "GET", path: `${PRINTER_BASE}/jobs/:jobId` },
  { method: "GET", path: `${PRINTER_BASE}/metrics` },
  { method: "POST", path: `${PRINTER_BASE}/print/label` },
  { method: "POST", path: `${PRINTER_BASE}/print/receipt` },
  { method: "POST", path: `${PRINTER_BASE}/print/text` },
  { method: "POST", path: `${PRINTER_BASE}/scan` },
  { method: "POST", path: `${PRINTER_BASE}/scan/barcode` },
  { method: "POST", path: `${PRINTER_BASE}/scan/qr` },
  { method: "GET", path: `${PRINTER_BASE}/status` },
  { method: "GET", path: `${BUNBUDDIES_BASE}/:source/openapi` },
  { method: "GET", path: `${BUNBUDDIES_BASE}/capabilities` },
  { method: "GET", path: `${BUNBUDDIES_BASE}/graph` },
] satisfies ApiRouteDefinition[];
