/**
 * Capability route definitions for AI/chat/auth/explorer/fleet/xr/usd/three.
 *
 * @shared/contracts/versions/v1/capability/routes-ai-chat
 */

import { API_PATHS } from "@baohaus/bao-constants/api-paths";
import { AUTH_ROUTE_DEFINITIONS } from "@baohaus/bao-constants/auth-routes";
import type { ApiRouteDefinition, ApiRouteMethod } from "./core";
import {
  AI_AZURE_BASE,
  AI_BASE,
  AI_CHAT_BASE,
  AI_EMBEDDINGS_BASE,
  AI_HUGGINGFACE_BASE,
  AI_NIM_BASE,
  AI_OLLAMA_BASE,
  AI_OPENAI_BASE,
  AI_RAMLAMA_BASE,
  AI_WEAVIATE_BASE,
  API_EXPLORER_BASE,
  CHAT_BASE,
  FLEET_BASE,
  THREE_AI_BASE,
  THREE_AI_JOBS_BASE,
  THREE_BASE,
  THREE_MEDIA_BASE,
  toAppContractPath,
  USD_ASSETS_BASE,
  USD_SCAN_IMPORT_BASE,
  XR_BASE,
  XR_EXPERIENCES_BASE,
  XR_SHARED_BASE,
} from "./core";

export const AI_ROUTE_DEFINITIONS_V1: readonly ApiRouteDefinition[] = [
  { method: "DELETE", path: `${AI_AZURE_BASE}/credentials` },
  { method: "GET", path: `${AI_AZURE_BASE}/credentials` },
  { method: "PUT", path: `${AI_AZURE_BASE}/credentials` },
  { method: "GET", path: `${AI_AZURE_BASE}/settings` },
  { method: "PUT", path: `${AI_AZURE_BASE}/settings` },
  { method: "GET", path: `${AI_BASE}/capabilities` },
  { method: "GET", path: `${AI_CHAT_BASE}/conversations` },
  { method: "POST", path: `${AI_CHAT_BASE}/conversations` },
  { method: "DELETE", path: `${AI_CHAT_BASE}/conversations/:id` },
  { method: "GET", path: `${AI_CHAT_BASE}/conversations/:id/messages` },
  { method: "POST", path: `${AI_CHAT_BASE}/conversations/:id/messages` },
  { method: "POST", path: `${AI_BASE}/devices/assist` },
  { method: "GET", path: `${AI_BASE}/devices/assist/config` },
  { method: "POST", path: AI_EMBEDDINGS_BASE },
  { method: "DELETE", path: `${AI_EMBEDDINGS_BASE}/:sourceType/:sourceId` },
  { method: "GET", path: `${AI_EMBEDDINGS_BASE}/:sourceType/:sourceId` },
  { method: "GET", path: `${AI_EMBEDDINGS_BASE}/models` },
  { method: "POST", path: `${AI_EMBEDDINGS_BASE}/store` },
  { method: "GET", path: `${AI_BASE}/health` },
  { method: "DELETE", path: `${AI_HUGGINGFACE_BASE}/credentials` },
  { method: "GET", path: `${AI_HUGGINGFACE_BASE}/credentials` },
  { method: "PUT", path: `${AI_HUGGINGFACE_BASE}/credentials` },
  { method: "POST", path: `${AI_BASE}/images` },
  { method: "GET", path: `${AI_BASE}/insights` },
  { method: "GET", path: `${AI_BASE}/models` },
  { method: "PUT", path: `${AI_BASE}/models/:id/promote` },
  { method: "DELETE", path: `${AI_NIM_BASE}/credentials` },
  { method: "GET", path: `${AI_NIM_BASE}/credentials` },
  { method: "PUT", path: `${AI_NIM_BASE}/credentials` },
  { method: "GET", path: `${AI_NIM_BASE}/endpoints` },
  { method: "PUT", path: `${AI_NIM_BASE}/endpoints` },
  { method: "GET", path: `${AI_NIM_BASE}/health` },
  { method: "GET", path: `${AI_NIM_BASE}/metadata` },
  { method: "GET", path: `${AI_NIM_BASE}/metrics` },
  { method: "GET", path: `${AI_NIM_BASE}/models` },
  { method: "GET", path: `${AI_NIM_BASE}/version` },
  { method: "GET", path: `${AI_OLLAMA_BASE}/health` },
  { method: "GET", path: `${AI_OLLAMA_BASE}/models` },
  { method: "GET", path: `${AI_OLLAMA_BASE}/settings` },
  { method: "PUT", path: `${AI_OLLAMA_BASE}/settings` },
  { method: "POST", path: `${AI_OPENAI_BASE}/chat/completions` },
  { method: "POST", path: `${AI_OPENAI_BASE}/embeddings` },
  { method: "GET", path: `${AI_OPENAI_BASE}/models` },
  { method: "GET", path: `${AI_BASE}/providers` },
  { method: "GET", path: API_PATHS.aiProvidersHealth },
  { method: "POST", path: `${AI_BASE}/providers/reset` },
  { method: "GET", path: `${AI_RAMLAMA_BASE}/models` },
  { method: "POST", path: `${AI_RAMLAMA_BASE}/models/pull` },
  { method: "POST", path: `${AI_RAMLAMA_BASE}/models/remove` },
  { method: "POST", path: `${AI_RAMLAMA_BASE}/serve` },
  { method: "GET", path: `${AI_RAMLAMA_BASE}/status` },
  { method: "POST", path: `${AI_RAMLAMA_BASE}/stop` },
  { method: "GET", path: API_PATHS.aiSystemConfig },
  { method: "GET", path: API_PATHS.aiSystemRuntimes },
  { method: "POST", path: API_PATHS.aiSystemTestConnection },
  { method: "POST", path: `${AI_BASE}/text` },
  { method: "POST", path: `${AI_BASE}/text/stream` },
  { method: "GET", path: `${AI_BASE}/usage` },
  { method: "GET", path: `${AI_BASE}/usage/records` },
  { method: "DELETE", path: `${AI_WEAVIATE_BASE}/credentials` },
  { method: "GET", path: `${AI_WEAVIATE_BASE}/credentials` },
  { method: "PUT", path: `${AI_WEAVIATE_BASE}/credentials` },
  { method: "GET", path: `${AI_WEAVIATE_BASE}/settings` },
  { method: "PUT", path: `${AI_WEAVIATE_BASE}/settings` },
] satisfies ApiRouteDefinition[];

export const CHAT_ROUTE_DEFINITIONS_V1: readonly ApiRouteDefinition[] = [
  { method: "GET", path: `${CHAT_BASE}/tools` },
  { method: "GET", path: `${CHAT_BASE}/conversations` },
  { method: "POST", path: `${CHAT_BASE}/conversations/resolve` },
  { method: "DELETE", path: `${CHAT_BASE}/conversations/:id` },
  { method: "PATCH", path: `${CHAT_BASE}/conversations/:id` },
  { method: "POST", path: `${CHAT_BASE}/conversations/:id/join` },
  { method: "GET", path: `${CHAT_BASE}/conversations/:id/members` },
  { method: "POST", path: `${CHAT_BASE}/conversations/:id/members` },
  { method: "DELETE", path: `${CHAT_BASE}/conversations/:id/members/:userId` },
  { method: "GET", path: `${CHAT_BASE}/conversations/:id/messages` },
  { method: "POST", path: `${CHAT_BASE}/conversations/:id/messages` },
  { method: "POST", path: `${CHAT_BASE}/conversations/:id/messages/stream` },
  { method: "POST", path: `${CHAT_BASE}/conversations/:id/messages/run` },
  { method: "POST", path: `${CHAT_BASE}/messages/:id/feedback` },
  { method: "GET", path: `${CHAT_BASE}/conversations/:id/runs` },
  { method: "GET", path: `${CHAT_BASE}/conversations/:id/runs/:runId` },
  { method: "GET", path: `${CHAT_BASE}/conversations/:id/memory` },
  { method: "POST", path: `${CHAT_BASE}/conversations/:id/memory/refresh` },
] satisfies ApiRouteDefinition[];

export const AUTH_ROUTE_DEFINITIONS_V1: readonly ApiRouteDefinition[] = AUTH_ROUTE_DEFINITIONS.map(
  (definition) => ({
    method: definition.method.toUpperCase() as ApiRouteMethod,
    path: toAppContractPath(`${API_PATHS.authBase}${definition.path}`),
  }),
);

export const API_EXPLORER_ROUTE_DEFINITIONS_V1: readonly ApiRouteDefinition[] = [
  { method: "GET", path: `${API_EXPLORER_BASE}/routes` },
  { method: "POST", path: `${API_EXPLORER_BASE}/try` },
] satisfies ApiRouteDefinition[];

export const FLEET_ROUTE_DEFINITIONS_V1: readonly ApiRouteDefinition[] = [
  { method: "GET", path: `${FLEET_BASE}/adapters` },
  { method: "GET", path: `${FLEET_BASE}/alerts` },
  { method: "POST", path: toAppContractPath(API_PATHS.fleetAlertAck) },
  { method: "POST", path: `${FLEET_BASE}/assignments/preview` },
  { method: "POST", path: `${FLEET_BASE}/runs` },
  { method: "GET", path: toAppContractPath(API_PATHS.fleetRunById) },
  { method: "POST", path: toAppContractPath(API_PATHS.fleetRunCancel) },
  { method: "GET", path: toAppContractPath(API_PATHS.fleetRunEvents) },
  { method: "GET", path: toAppContractPath(API_PATHS.fleetRunEventsStream) },
] satisfies ApiRouteDefinition[];

export const XR_ROUTE_DEFINITIONS_V1: readonly ApiRouteDefinition[] = [
  { method: "GET", path: `${XR_BASE}/capabilities` },
  { method: "GET", path: `${XR_BASE}/config` },
  { method: "PUT", path: `${XR_BASE}/config` },
  { method: "GET", path: `${XR_BASE}/hardware` },
  { method: "GET", path: `${XR_BASE}/input-profiles` },
  { method: "GET", path: `${XR_BASE}/sessions` },
  { method: "POST", path: `${XR_BASE}/sessions` },
  { method: "GET", path: `${XR_BASE}/sessions/:sessionId` },
  { method: "POST", path: `${XR_BASE}/sessions/:sessionId/join` },
  { method: "POST", path: `${XR_BASE}/sessions/:sessionId/leave` },
  { method: "POST", path: `${XR_BASE}/sessions/:sessionId/close` },
  { method: "GET", path: `${XR_BASE}/sessions/:sessionId/events` },
  { method: "POST", path: `${XR_BASE}/sessions/:sessionId/events` },
  { method: "POST", path: `${XR_BASE}/validate-config` },
  { method: "GET", path: XR_EXPERIENCES_BASE },
  { method: "POST", path: XR_EXPERIENCES_BASE },
  { method: "DELETE", path: `${XR_EXPERIENCES_BASE}/:id` },
  { method: "GET", path: `${XR_EXPERIENCES_BASE}/:id` },
  { method: "GET", path: `${XR_EXPERIENCES_BASE}/:id/composition` },
  { method: "GET", path: `${XR_EXPERIENCES_BASE}/:id/reviews` },
  { method: "POST", path: `${XR_EXPERIENCES_BASE}/:id/reviews` },
  { method: "POST", path: `${XR_EXPERIENCES_BASE}/:id/ingest/scan` },
  { method: "POST", path: `${XR_EXPERIENCES_BASE}/:id/ingest/autonomy` },
  { method: "PUT", path: `${XR_EXPERIENCES_BASE}/:id` },
  { method: "POST", path: `${XR_EXPERIENCES_BASE}/:id/ai/overlays` },
  { method: "POST", path: `${XR_EXPERIENCES_BASE}/:id/ai/placement-suggestions` },
  { method: "POST", path: `${XR_EXPERIENCES_BASE}/:id/ai/usd` },
  { method: "POST", path: `${XR_EXPERIENCES_BASE}/:id/archive` },
  { method: "GET", path: `${XR_EXPERIENCES_BASE}/:id/assets` },
  { method: "POST", path: `${XR_EXPERIENCES_BASE}/:id/assets` },
  { method: "DELETE", path: `${XR_EXPERIENCES_BASE}/:id/assets/:assetId` },
  { method: "PATCH", path: `${XR_EXPERIENCES_BASE}/:id/assets/:assetId` },
  { method: "POST", path: `${XR_EXPERIENCES_BASE}/:id/assets/from-scan-session` },
  { method: "POST", path: `${XR_EXPERIENCES_BASE}/:id/publish` },
  { method: "GET", path: `${XR_EXPERIENCES_BASE}/:id/revisions` },
  { method: "GET", path: `${XR_EXPERIENCES_BASE}/:id/revisions/:version` },
  { method: "POST", path: `${XR_EXPERIENCES_BASE}/:id/revisions/:version/restore` },
  { method: "GET", path: `${XR_EXPERIENCES_BASE}/:id/revisions/compare` },
  { method: "DELETE", path: `${XR_EXPERIENCES_BASE}/:id/share` },
  { method: "GET", path: `${XR_EXPERIENCES_BASE}/:id/share` },
  { method: "POST", path: `${XR_EXPERIENCES_BASE}/:id/share` },
  { method: "POST", path: `${XR_EXPERIENCES_BASE}/:id/unpublish` },
  { method: "GET", path: `${XR_SHARED_BASE}/:token` },
] satisfies ApiRouteDefinition[];

export const USD_ROUTE_DEFINITIONS_V1: readonly ApiRouteDefinition[] = [
  { method: "GET", path: USD_ASSETS_BASE },
  { method: "POST", path: USD_ASSETS_BASE },
  { method: "DELETE", path: `${USD_ASSETS_BASE}/:id` },
  { method: "GET", path: `${USD_ASSETS_BASE}/:id` },
  { method: "GET", path: `${USD_ASSETS_BASE}/:id/ar-urls` },
  { method: "GET", path: `${USD_ASSETS_BASE}/:id/file` },
  { method: "POST", path: `${USD_ASSETS_BASE}/:id/validate` },
  { method: "POST", path: USD_SCAN_IMPORT_BASE },
  { method: "GET", path: `${USD_SCAN_IMPORT_BASE}/jobs/:jobId` },
  { method: "POST", path: `${USD_SCAN_IMPORT_BASE}/queue` },
] satisfies ApiRouteDefinition[];

export const THREE_ROUTE_DEFINITIONS_V1: readonly ApiRouteDefinition[] = [
  { method: "GET", path: `${THREE_BASE}/capabilities` },
  { method: "GET", path: THREE_AI_JOBS_BASE },
  { method: "POST", path: THREE_AI_JOBS_BASE },
  { method: "GET", path: `${THREE_AI_JOBS_BASE}/:id` },
  { method: "POST", path: `${THREE_AI_JOBS_BASE}/:id/decision` },
  { method: "POST", path: `${THREE_AI_JOBS_BASE}/queue` },
  { method: "GET", path: `${THREE_AI_BASE}/queue-metrics` },
  { method: "GET", path: THREE_MEDIA_BASE },
  { method: "POST", path: THREE_MEDIA_BASE },
  { method: "DELETE", path: `${THREE_MEDIA_BASE}/:id` },
  { method: "GET", path: `${THREE_MEDIA_BASE}/:id` },
  { method: "GET", path: `${THREE_MEDIA_BASE}/:id/file` },
  { method: "POST", path: `${THREE_MEDIA_BASE}/import-scan-session` },
  { method: "GET", path: `${THREE_MEDIA_BASE}/import-scan-session/jobs/:jobId` },
  { method: "POST", path: `${THREE_MEDIA_BASE}/import-scan-session/queue` },
  { method: "POST", path: `${THREE_MEDIA_BASE}/import-usd` },
  { method: "GET", path: `${THREE_MEDIA_BASE}/stats` },
] satisfies ApiRouteDefinition[];
