import type { ValidatorContext } from "../context.ts";
import { RAW_FETCH_PATTERN } from "../patterns.ts";

/**
 * First-line header markers that identify a `public/*.js` artifact as a
 * checked-in compiled bundle. These bundles re-emit the canonical client API
 * composable's transport `fetch()` and are not handwritten source.
 */
const BUNDLE_HEADER_PATTERNS: readonly RegExp[] = [
  /^\/\/\s*Generated by\b/u,
  /^\/\/\s*\.{0,2}\/?bao-source\//u,
  /^\/\/\s*\.{0,2}\/?src\//u,
];

const fileHeaderIndicatesBundle = async (ctx: ValidatorContext, path: string): Promise<boolean> => {
  if (!path.endsWith(".js")) {
    return false;
  }
  const contents = await ctx.readFile(path);
  const firstLine = contents.split("\n", 1)[0] ?? "";
  return BUNDLE_HEADER_PATTERNS.some((pattern) => pattern.test(firstLine));
};

export const noClientFetchDrift = async (ctx: ValidatorContext): Promise<void> => {
  const allowedFiles = ctx.config.allowedClientFetchFiles ?? new Set<string>();
  const candidates = ctx.clientCodeFiles().filter((path) => !allowedFiles.has(path));
  const scanTargets: string[] = [];
  for (const path of candidates) {
    if (await fileHeaderIndicatesBundle(ctx, path)) {
      continue;
    }
    scanTargets.push(path);
  }
  ctx.failAll(await ctx.findAllMatches(RAW_FETCH_PATTERN, scanTargets), "raw fetch() usage found");
};
