// AUTO-GENERATED by @baohaus/sdk-codegen-bao for @baohaus/bao-runtime@0.1.0
// Source: DELETE /api/v1/drone/devices/{deviceId}/rally-points
// Do not edit by hand — re-run `bun run sdk:gen` after spec changes.

import { toResultAsync } from "@baohaus/bao-utils/async-result";
import type { BaoError } from "@baohaus/bao-utils/canonical/bao-error";
import { buildBaoError } from "@baohaus/bao-utils/canonical/bao-error";

export type deleteApiV1DroneDevicesByDeviceIdRally
-pointsOptions = {
  readonly baseUrl: string;
readonly;
init?: RequestInit;
readonly;
pathParams?: Readonly<Record<string, string>>;
readonly;
query?: Readonly<Record<string, string>>;
}

export type deleteApiV1DroneDevicesByDeviceIdRally
-pointsResponse = {
  readonly status: number;
readonly;
headers: Headers;
readonly;
body: string;
}

export async function deleteApiV1DroneDevicesByDeviceIdRally
-points(
  options: deleteApiV1DroneDevicesByDeviceIdRally-pointsOptions,
)
: Promise<
{
  ok: true;
  value: deleteApiV1DroneDevicesByDeviceIdRally - pointsResponse;
}
|
{
  ok: false;
  error: BaoError;
}
>
{
  const params = options.pathParams ?? {};
  const pathTemplate = "/api/v1/drone/devices/{deviceId}/rally-points";
  const path = pathTemplate.replace(
    /\{([^}]+)\}/g,
    (_match, key) => params[key] ?? "{" + key + "}",
  );
  const queryString = options.query ? "?" + new URLSearchParams(options.query).toString() : "";
  const url = options.baseUrl + path + queryString;
  const fetchResult = await toResultAsync<Response, BaoError>(
    fetch(url, { method: "DELETE", ...options.init }),
    (error) =>
      buildBaoError({
        code: "SDK_DELETEAPIV1DRONEDEVICESBYDEVICEIDRALLY-POINTS_FETCH_FAILED",
        kind: "upstream",
        message: `fetch to ${url} failed`,
        details: { url, cause: error instanceof Error ? error.message : String(error) },
      }),
  );
  if (!fetchResult.ok) {
    return fetchResult;
  }
  const response = fetchResult.value;
  const bodyResult = await toResultAsync<string, BaoError>(response.text(), (error) =>
    buildBaoError({
      code: "SDK_DELETEAPIV1DRONEDEVICESBYDEVICEIDRALLY-POINTS_BODY_READ_FAILED",
      kind: "io",
      message: `reading response body for ${url} failed`,
      details: { url, cause: error instanceof Error ? error.message : String(error) },
    }),
  );
  if (!bodyResult.ok) {
    return bodyResult;
  }
  return {
    ok: true,
    value: { status: response.status, headers: response.headers, body: bodyResult.value },
  };
}
