// AUTO-GENERATED by @baohaus/sdk-codegen-bao for @baohaus/bao-runtime@0.1.0
// Source: PUT /api/v1/work-orders/{id}
// Do not edit by hand — re-run `bun run sdk:gen` after spec changes.

import { toResultAsync } from "@baohaus/bao-utils/async-result";
import type { BaoError } from "@baohaus/bao-utils/canonical/bao-error";
import { buildBaoError } from "@baohaus/bao-utils/canonical/bao-error";

export type putApiV1Work
-ordersByIdOptions = {
  readonly baseUrl: string;
readonly;
init?: RequestInit;
readonly;
pathParams?: Readonly<Record<string, string>>;
readonly;
query?: Readonly<Record<string, string>>;
}

export type putApiV1Work
-ordersByIdResponse = {
  readonly status: number;
readonly;
headers: Headers;
readonly;
body: string;
}

export async function putApiV1Work
-ordersById(
  options: putApiV1Work-ordersByIdOptions,
)
: Promise<
{
  ok: true;
  value: putApiV1Work - ordersByIdResponse;
}
|
{
  ok: false;
  error: BaoError;
}
>
{
  const params = options.pathParams ?? {};
  const pathTemplate = "/api/v1/work-orders/{id}";
  const path = pathTemplate.replace(
    /\{([^}]+)\}/g,
    (_match, key) => params[key] ?? "{" + key + "}",
  );
  const queryString = options.query ? "?" + new URLSearchParams(options.query).toString() : "";
  const url = options.baseUrl + path + queryString;
  const fetchResult = await toResultAsync<Response, BaoError>(
    fetch(url, { method: "PUT", ...options.init }),
    (error) =>
      buildBaoError({
        code: "SDK_PUTAPIV1WORK-ORDERSBYID_FETCH_FAILED",
        kind: "upstream",
        message: `fetch to ${url} failed`,
        details: { url, cause: error instanceof Error ? error.message : String(error) },
      }),
  );
  if (!fetchResult.ok) {
    return fetchResult;
  }
  const response = fetchResult.value;
  const bodyResult = await toResultAsync<string, BaoError>(response.text(), (error) =>
    buildBaoError({
      code: "SDK_PUTAPIV1WORK-ORDERSBYID_BODY_READ_FAILED",
      kind: "io",
      message: `reading response body for ${url} failed`,
      details: { url, cause: error instanceof Error ? error.message : String(error) },
    }),
  );
  if (!bodyResult.ok) {
    return bodyResult;
  }
  return {
    ok: true,
    value: { status: response.status, headers: response.headers, body: bodyResult.value },
  };
}
