/**
 * AI provider metadata lookup table.
 * Extracted from ai-providers.ts to keep module size under 400 lines.
 */

import type { AiProviderKey, AiProviderMetadata } from "./ai-providers";

export const AI_PROVIDER_METADATA: Record<AiProviderKey, AiProviderMetadata> = {
  auto: {
    key: "auto",
    label: "Auto (Best Available)",
    shortLabel: "Auto",
    icon: "lucide--sparkles",
    badgeClass: "badge-primary",
    textClass: "text-primary",
  },
  openai: {
    key: "openai",
    label: "OpenAI",
    shortLabel: "OpenAI",
    icon: "simple-icons--openai",
    badgeClass: "badge-success",
    textClass: "text-success",
  },
  anthropic: {
    key: "anthropic",
    label: "Anthropic",
    shortLabel: "Anthropic",
    icon: "simple-icons--anthropic",
    badgeClass: "badge-warning",
    textClass: "text-warning",
  },
  gemini: {
    key: "gemini",
    label: "Google Gemini",
    shortLabel: "Gemini",
    icon: "simple-icons--googlegemini",
    badgeClass: "badge-info",
    textClass: "text-info",
  },
  deepseek: {
    key: "deepseek",
    label: "DeepSeek",
    shortLabel: "DeepSeek",
    icon: "simple-icons--deepseek",
    badgeClass: "badge-primary",
    textClass: "text-primary",
  },
  azure: {
    key: "azure",
    label: "Azure OpenAI",
    shortLabel: "Azure",
    icon: "simple-icons--microsoftazure",
    badgeClass: "badge-info",
    textClass: "text-info",
  },
  bedrock: {
    key: "bedrock",
    label: "AWS Bedrock",
    shortLabel: "Bedrock",
    icon: "simple-icons--amazonaws",
    badgeClass: "badge-warning",
    textClass: "text-warning",
  },
  copilot: {
    key: "copilot",
    label: "GitHub Copilot",
    shortLabel: "Copilot",
    icon: "simple-icons--githubcopilot",
    badgeClass: "badge-secondary",
    textClass: "text-secondary",
  },
  github: {
    key: "github",
    label: "GitHub Models",
    shortLabel: "GitHub",
    icon: "simple-icons--github",
    badgeClass: "badge-neutral",
    textClass: "text-base-content",
  },
  groq: {
    key: "groq",
    label: "Groq",
    shortLabel: "Groq",
    icon: "simple-icons--groq",
    badgeClass: "badge-accent",
    textClass: "text-accent",
  },
  together: {
    key: "together",
    label: "Together AI",
    shortLabel: "Together",
    icon: "lucide--layers",
    badgeClass: "badge-info",
    textClass: "text-info",
  },
  fireworks: {
    key: "fireworks",
    label: "Fireworks AI",
    shortLabel: "Fireworks",
    icon: "lucide--flame",
    badgeClass: "badge-error",
    textClass: "text-error",
  },
  mistral: {
    key: "mistral",
    label: "Mistral AI",
    shortLabel: "Mistral",
    icon: "simple-icons--mistral",
    badgeClass: "badge-warning",
    textClass: "text-warning",
  },
  cohere: {
    key: "cohere",
    label: "Cohere",
    shortLabel: "Cohere",
    icon: "lucide--message-circle",
    badgeClass: "badge-success",
    textClass: "text-success",
  },
  xai: {
    key: "xai",
    label: "xAI (Grok)",
    shortLabel: "xAI",
    icon: "simple-icons--x",
    badgeClass: "badge-neutral",
    textClass: "text-base-content",
  },
  cerebras: {
    key: "cerebras",
    label: "Cerebras",
    shortLabel: "Cerebras",
    icon: "lucide--cpu",
    badgeClass: "badge-accent",
    textClass: "text-accent",
  },
  perplexity: {
    key: "perplexity",
    label: "Perplexity",
    shortLabel: "Perplexity",
    icon: "lucide--search",
    badgeClass: "badge-info",
    textClass: "text-info",
  },
  sambanova: {
    key: "sambanova",
    label: "SambaNova",
    shortLabel: "SambaNova",
    icon: "lucide--zap",
    badgeClass: "badge-success",
    textClass: "text-success",
  },
  openrouter: {
    key: "openrouter",
    label: "OpenRouter",
    shortLabel: "OpenRouter",
    icon: "lucide--git-branch",
    badgeClass: "badge-primary",
    textClass: "text-primary",
  },
  lmstudio: {
    key: "lmstudio",
    label: "LM Studio",
    shortLabel: "LMStudio",
    icon: "lucide--monitor",
    badgeClass: "badge-secondary",
    textClass: "text-secondary",
  },
  huggingface: {
    key: "huggingface",
    label: "Hugging Face",
    shortLabel: "HF",
    icon: "simple-icons--huggingface",
    badgeClass: "badge-warning",
    textClass: "text-warning",
  },
  nim: {
    key: "nim",
    label: "NVIDIA NIM",
    shortLabel: "NIM",
    icon: "simple-icons--nvidia",
    badgeClass: "badge-success",
    textClass: "text-success",
  },
  ollama: {
    key: "ollama",
    label: "Ollama",
    shortLabel: "Ollama",
    icon: "simple-icons--ollama",
    badgeClass: "badge-secondary",
    textClass: "text-secondary",
  },
  ramalama: {
    key: "ramalama",
    label: "RamaLama",
    shortLabel: "RamaLama",
    icon: "lucide--box",
    badgeClass: "badge-info",
    textClass: "text-info",
  },
  minimax: {
    key: "minimax",
    label: "MiniMax",
    shortLabel: "MiniMax",
    icon: "lucide--sparkle",
    badgeClass: "badge-info",
    textClass: "text-info",
  },
  minimaxcn: {
    key: "minimaxcn",
    label: "MiniMax (China)",
    shortLabel: "MiniMaxCN",
    icon: "lucide--sparkle",
    badgeClass: "badge-info",
    textClass: "text-info",
  },
  glm: {
    key: "glm",
    label: "Zhipu GLM",
    shortLabel: "GLM",
    icon: "lucide--brain",
    badgeClass: "badge-primary",
    textClass: "text-primary",
  },
  moonshot: {
    key: "moonshot",
    label: "Moonshot Kimi",
    shortLabel: "Kimi",
    icon: "lucide--moon",
    badgeClass: "badge-info",
    textClass: "text-info",
  },
  qwen: {
    key: "qwen",
    label: "Alibaba Qwen",
    shortLabel: "Qwen",
    icon: "lucide--bot",
    badgeClass: "badge-warning",
    textClass: "text-warning",
  },
  yi: {
    key: "yi",
    label: "01.AI Yi",
    shortLabel: "Yi",
    icon: "lucide--star",
    badgeClass: "badge-accent",
    textClass: "text-accent",
  },
  deepinfra: {
    key: "deepinfra",
    label: "DeepInfra",
    shortLabel: "DeepInfra",
    icon: "lucide--server",
    badgeClass: "badge-neutral",
    textClass: "text-base-content",
  },
  novita: {
    key: "novita",
    label: "Novita",
    shortLabel: "Novita",
    icon: "lucide--cloud",
    badgeClass: "badge-info",
    textClass: "text-info",
  },
  hyperbolic: {
    key: "hyperbolic",
    label: "Hyperbolic",
    shortLabel: "Hyperbolic",
    icon: "lucide--orbit",
    badgeClass: "badge-secondary",
    textClass: "text-secondary",
  },
  doubao: {
    key: "doubao",
    label: "ByteDance Doubao",
    shortLabel: "Doubao",
    icon: "lucide--sparkles",
    badgeClass: "badge-error",
    textClass: "text-error",
  },
  oaicompat: {
    key: "oaicompat",
    label: "OpenAI Compatible",
    shortLabel: "OAI Compat",
    icon: "lucide--plug",
    badgeClass: "badge-neutral",
    textClass: "text-base-content",
  },
  anthcompat: {
    key: "anthcompat",
    label: "Anthropic Compatible",
    shortLabel: "Anth Compat",
    icon: "lucide--plug",
    badgeClass: "badge-neutral",
    textClass: "text-base-content",
  },
  onnx: {
    key: "onnx",
    label: "ONNX Runtime",
    shortLabel: "ONNX",
    icon: "simple-icons--onnx",
    badgeClass: "badge-accent",
    textClass: "text-accent",
  },
  local: {
    key: "local",
    label: "Local Model",
    shortLabel: "Local",
    icon: "lucide--hard-drive",
    badgeClass: "badge-neutral",
    textClass: "text-base-content",
  },
};
