from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.ai.chat.v1.AiChatStreamEventV1 import AiChatStreamEventV1

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class AiChatStreamBatchV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> AiChatStreamBatchV1: ...
  @classmethod
  def GetRootAsAiChatStreamBatchV1(cls, buf: bytes, offset: int) -> AiChatStreamBatchV1: ...
  @classmethod
  def AiChatStreamBatchV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Events(self, i: int) -> AiChatStreamEventV1 | None: ...
  def EventsLength(self) -> int: ...
  def EventsIsNone(self) -> bool: ...
def AiChatStreamBatchV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def AiChatStreamBatchV1AddEvents(builder: flatbuffers.Builder, events: uoffset) -> None: ...
def AiChatStreamBatchV1StartEventsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartEventsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def AiChatStreamBatchV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

