# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
from baohaus.ai.chat.v1.CitationV1 import CitationV1
from baohaus.ai.chat.v1.ToolCallV1 import ToolCallV1
from baohaus.ai.chat.v1.UsageStatsV1 import UsageStatsV1
np = import_numpy()

# Single chat stream event.
class AiChatStreamEventV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AiChatStreamEventV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAiChatStreamEventV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def AiChatStreamEventV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x41\x43\x56\x31", size_prefixed=size_prefixed)

    # AiChatStreamEventV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Correlation ID for request tracing.
    # AiChatStreamEventV1
    def CorrelationId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Stream event type.
    # AiChatStreamEventV1
    def EventType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Token content (when event_type = TOKEN).
    # AiChatStreamEventV1
    def Token(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Sequence index of this token in the stream.
    # AiChatStreamEventV1
    def Sequence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AI model identifier.
    # AiChatStreamEventV1
    def ModelId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AI provider.
    # AiChatStreamEventV1
    def Provider(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Finish reason (when event_type = DONE).
    # AiChatStreamEventV1
    def FinishReason(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Usage statistics (when event_type = DONE).
    # AiChatStreamEventV1
    def Usage(self) -> Optional[UsageStatsV1]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = UsageStatsV1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Tool calls (when event_type = TOOL_CALL).
    # AiChatStreamEventV1
    def ToolCalls(self, j: int) -> Optional[ToolCallV1]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = ToolCallV1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AiChatStreamEventV1
    def ToolCallsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AiChatStreamEventV1
    def ToolCallsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # Citations (when event_type = CITATION).
    # AiChatStreamEventV1
    def Citations(self, j: int) -> Optional[CitationV1]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = CitationV1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AiChatStreamEventV1
    def CitationsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AiChatStreamEventV1
    def CitationsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

    # Error message (when event_type = ERROR).
    # AiChatStreamEventV1
    def Error(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Timestamp in milliseconds since epoch.
    # AiChatStreamEventV1
    def TimestampMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Latency in milliseconds for this token.
    # AiChatStreamEventV1
    def LatencyMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def AiChatStreamEventV1Start(builder: flatbuffers.Builder):
    builder.StartObject(13)

def Start(builder: flatbuffers.Builder):
    AiChatStreamEventV1Start(builder)

def AiChatStreamEventV1AddCorrelationId(builder: flatbuffers.Builder, correlationId: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(correlationId), 0)

def AddCorrelationId(builder: flatbuffers.Builder, correlationId: int):
    AiChatStreamEventV1AddCorrelationId(builder, correlationId)

def AiChatStreamEventV1AddEventType(builder: flatbuffers.Builder, eventType: int):
    builder.PrependUint8Slot(1, eventType, 0)

def AddEventType(builder: flatbuffers.Builder, eventType: int):
    AiChatStreamEventV1AddEventType(builder, eventType)

def AiChatStreamEventV1AddToken(builder: flatbuffers.Builder, token: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(token), 0)

def AddToken(builder: flatbuffers.Builder, token: int):
    AiChatStreamEventV1AddToken(builder, token)

def AiChatStreamEventV1AddSequence(builder: flatbuffers.Builder, sequence: int):
    builder.PrependUint32Slot(3, sequence, 0)

def AddSequence(builder: flatbuffers.Builder, sequence: int):
    AiChatStreamEventV1AddSequence(builder, sequence)

def AiChatStreamEventV1AddModelId(builder: flatbuffers.Builder, modelId: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(modelId), 0)

def AddModelId(builder: flatbuffers.Builder, modelId: int):
    AiChatStreamEventV1AddModelId(builder, modelId)

def AiChatStreamEventV1AddProvider(builder: flatbuffers.Builder, provider: int):
    builder.PrependUint8Slot(5, provider, 0)

def AddProvider(builder: flatbuffers.Builder, provider: int):
    AiChatStreamEventV1AddProvider(builder, provider)

def AiChatStreamEventV1AddFinishReason(builder: flatbuffers.Builder, finishReason: int):
    builder.PrependUint8Slot(6, finishReason, 0)

def AddFinishReason(builder: flatbuffers.Builder, finishReason: int):
    AiChatStreamEventV1AddFinishReason(builder, finishReason)

def AiChatStreamEventV1AddUsage(builder: flatbuffers.Builder, usage: int):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(usage), 0)

def AddUsage(builder: flatbuffers.Builder, usage: int):
    AiChatStreamEventV1AddUsage(builder, usage)

def AiChatStreamEventV1AddToolCalls(builder: flatbuffers.Builder, toolCalls: int):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(toolCalls), 0)

def AddToolCalls(builder: flatbuffers.Builder, toolCalls: int):
    AiChatStreamEventV1AddToolCalls(builder, toolCalls)

def AiChatStreamEventV1StartToolCallsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartToolCallsVector(builder, numElems: int) -> int:
    return AiChatStreamEventV1StartToolCallsVector(builder, numElems)

def AiChatStreamEventV1AddCitations(builder: flatbuffers.Builder, citations: int):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(citations), 0)

def AddCitations(builder: flatbuffers.Builder, citations: int):
    AiChatStreamEventV1AddCitations(builder, citations)

def AiChatStreamEventV1StartCitationsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartCitationsVector(builder, numElems: int) -> int:
    return AiChatStreamEventV1StartCitationsVector(builder, numElems)

def AiChatStreamEventV1AddError(builder: flatbuffers.Builder, error: int):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)

def AddError(builder: flatbuffers.Builder, error: int):
    AiChatStreamEventV1AddError(builder, error)

def AiChatStreamEventV1AddTimestampMs(builder: flatbuffers.Builder, timestampMs: int):
    builder.PrependUint64Slot(11, timestampMs, 0)

def AddTimestampMs(builder: flatbuffers.Builder, timestampMs: int):
    AiChatStreamEventV1AddTimestampMs(builder, timestampMs)

def AiChatStreamEventV1AddLatencyMs(builder: flatbuffers.Builder, latencyMs: int):
    builder.PrependUint16Slot(12, latencyMs, 0)

def AddLatencyMs(builder: flatbuffers.Builder, latencyMs: int):
    AiChatStreamEventV1AddLatencyMs(builder, latencyMs)

def AiChatStreamEventV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return AiChatStreamEventV1End(builder)
