from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.ai.chat.v1.AiProviderV1 import AiProviderV1
from baohaus.ai.chat.v1.CitationV1 import CitationV1
from baohaus.ai.chat.v1.FinishReasonV1 import FinishReasonV1
from baohaus.ai.chat.v1.StreamEventV1 import StreamEventV1
from baohaus.ai.chat.v1.ToolCallV1 import ToolCallV1
from baohaus.ai.chat.v1.UsageStatsV1 import UsageStatsV1

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class AiChatStreamEventV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> AiChatStreamEventV1: ...
  @classmethod
  def GetRootAsAiChatStreamEventV1(cls, buf: bytes, offset: int) -> AiChatStreamEventV1: ...
  @classmethod
  def AiChatStreamEventV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def CorrelationId(self) -> str | None: ...
  def EventType(self) -> typing.Literal[StreamEventV1.TOKEN, StreamEventV1.METADATA, StreamEventV1.DONE, StreamEventV1.ERROR, StreamEventV1.TOOL_CALL, StreamEventV1.CITATION]: ...
  def Token(self) -> str | None: ...
  def Sequence(self) -> int: ...
  def ModelId(self) -> str | None: ...
  def Provider(self) -> typing.Literal[AiProviderV1.UNKNOWN, AiProviderV1.OPENAI, AiProviderV1.ANTHROPIC, AiProviderV1.OLLAMA, AiProviderV1.ONNX_LOCAL, AiProviderV1.CUSTOM]: ...
  def FinishReason(self) -> typing.Literal[FinishReasonV1.NONE, FinishReasonV1.STOP, FinishReasonV1.LENGTH, FinishReasonV1.TOOL_CALLS, FinishReasonV1.CONTENT_FILTER, FinishReasonV1.ERROR]: ...
  def Usage(self) -> UsageStatsV1 | None: ...
  def ToolCalls(self, i: int) -> ToolCallV1 | None: ...
  def ToolCallsLength(self) -> int: ...
  def ToolCallsIsNone(self) -> bool: ...
  def Citations(self, i: int) -> CitationV1 | None: ...
  def CitationsLength(self) -> int: ...
  def CitationsIsNone(self) -> bool: ...
  def Error(self) -> str | None: ...
  def TimestampMs(self) -> int: ...
  def LatencyMs(self) -> int: ...
def AiChatStreamEventV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def AiChatStreamEventV1AddCorrelationId(builder: flatbuffers.Builder, correlationId: uoffset) -> None: ...
def AiChatStreamEventV1AddEventType(builder: flatbuffers.Builder, eventType: typing.Literal[StreamEventV1.TOKEN, StreamEventV1.METADATA, StreamEventV1.DONE, StreamEventV1.ERROR, StreamEventV1.TOOL_CALL, StreamEventV1.CITATION]) -> None: ...
def AiChatStreamEventV1AddToken(builder: flatbuffers.Builder, token: uoffset) -> None: ...
def AiChatStreamEventV1AddSequence(builder: flatbuffers.Builder, sequence: int) -> None: ...
def AiChatStreamEventV1AddModelId(builder: flatbuffers.Builder, modelId: uoffset) -> None: ...
def AiChatStreamEventV1AddProvider(builder: flatbuffers.Builder, provider: typing.Literal[AiProviderV1.UNKNOWN, AiProviderV1.OPENAI, AiProviderV1.ANTHROPIC, AiProviderV1.OLLAMA, AiProviderV1.ONNX_LOCAL, AiProviderV1.CUSTOM]) -> None: ...
def AiChatStreamEventV1AddFinishReason(builder: flatbuffers.Builder, finishReason: typing.Literal[FinishReasonV1.NONE, FinishReasonV1.STOP, FinishReasonV1.LENGTH, FinishReasonV1.TOOL_CALLS, FinishReasonV1.CONTENT_FILTER, FinishReasonV1.ERROR]) -> None: ...
def AiChatStreamEventV1AddUsage(builder: flatbuffers.Builder, usage: uoffset) -> None: ...
def AiChatStreamEventV1AddToolCalls(builder: flatbuffers.Builder, toolCalls: uoffset) -> None: ...
def AiChatStreamEventV1StartToolCallsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartToolCallsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def AiChatStreamEventV1AddCitations(builder: flatbuffers.Builder, citations: uoffset) -> None: ...
def AiChatStreamEventV1StartCitationsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartCitationsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def AiChatStreamEventV1AddError(builder: flatbuffers.Builder, error: uoffset) -> None: ...
def AiChatStreamEventV1AddTimestampMs(builder: flatbuffers.Builder, timestampMs: int) -> None: ...
def AiChatStreamEventV1AddLatencyMs(builder: flatbuffers.Builder, latencyMs: int) -> None: ...
def AiChatStreamEventV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

