# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
from baohaus.ai.chat.v1.AiChatStreamEventV1 import AiChatStreamEventV1
np = import_numpy()

# Batch of chat stream events (for WebSocket frame aggregation).
class AiChatStreamBatchV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AiChatStreamBatchV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAiChatStreamBatchV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def AiChatStreamBatchV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x41\x43\x56\x31", size_prefixed=size_prefixed)

    # AiChatStreamBatchV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Batch of stream events.
    # AiChatStreamBatchV1
    def Events(self, j: int) -> Optional[AiChatStreamEventV1]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = AiChatStreamEventV1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AiChatStreamBatchV1
    def EventsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AiChatStreamBatchV1
    def EventsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def AiChatStreamBatchV1Start(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    AiChatStreamBatchV1Start(builder)

def AiChatStreamBatchV1AddEvents(builder: flatbuffers.Builder, events: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(events), 0)

def AddEvents(builder: flatbuffers.Builder, events: int):
    AiChatStreamBatchV1AddEvents(builder, events)

def AiChatStreamBatchV1StartEventsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartEventsVector(builder, numElems: int) -> int:
    return AiChatStreamBatchV1StartEventsVector(builder, numElems)

def AiChatStreamBatchV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return AiChatStreamBatchV1End(builder)
