from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class CitationV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> CitationV1: ...
  @classmethod
  def GetRootAsCitationV1(cls, buf: bytes, offset: int) -> CitationV1: ...
  @classmethod
  def CitationV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SourceId(self) -> str | None: ...
  def Title(self) -> str | None: ...
  def OffsetStart(self) -> int: ...
  def OffsetEnd(self) -> int: ...
  def Score(self) -> float: ...
def CitationV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def CitationV1AddSourceId(builder: flatbuffers.Builder, sourceId: uoffset) -> None: ...
def CitationV1AddTitle(builder: flatbuffers.Builder, title: uoffset) -> None: ...
def CitationV1AddOffsetStart(builder: flatbuffers.Builder, offsetStart: int) -> None: ...
def CitationV1AddOffsetEnd(builder: flatbuffers.Builder, offsetEnd: int) -> None: ...
def CitationV1AddScore(builder: flatbuffers.Builder, score: float) -> None: ...
def CitationV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

