# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

# Citation reference within a stream.
class CitationV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CitationV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCitationV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CitationV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x41\x43\x56\x31", size_prefixed=size_prefixed)

    # CitationV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Source document identifier.
    # CitationV1
    def SourceId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Source document title/name.
    # CitationV1
    def Title(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Character offset start in the output.
    # CitationV1
    def OffsetStart(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Character offset end in the output.
    # CitationV1
    def OffsetEnd(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Relevance score (0.0–1.0).
    # CitationV1
    def Score(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def CitationV1Start(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    CitationV1Start(builder)

def CitationV1AddSourceId(builder: flatbuffers.Builder, sourceId: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sourceId), 0)

def AddSourceId(builder: flatbuffers.Builder, sourceId: int):
    CitationV1AddSourceId(builder, sourceId)

def CitationV1AddTitle(builder: flatbuffers.Builder, title: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(title), 0)

def AddTitle(builder: flatbuffers.Builder, title: int):
    CitationV1AddTitle(builder, title)

def CitationV1AddOffsetStart(builder: flatbuffers.Builder, offsetStart: int):
    builder.PrependUint32Slot(2, offsetStart, 0)

def AddOffsetStart(builder: flatbuffers.Builder, offsetStart: int):
    CitationV1AddOffsetStart(builder, offsetStart)

def CitationV1AddOffsetEnd(builder: flatbuffers.Builder, offsetEnd: int):
    builder.PrependUint32Slot(3, offsetEnd, 0)

def AddOffsetEnd(builder: flatbuffers.Builder, offsetEnd: int):
    CitationV1AddOffsetEnd(builder, offsetEnd)

def CitationV1AddScore(builder: flatbuffers.Builder, score: float):
    builder.PrependFloat32Slot(4, score, 0.0)

def AddScore(builder: flatbuffers.Builder, score: float):
    CitationV1AddScore(builder, score)

def CitationV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return CitationV1End(builder)
