# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

# Finish reason for a completed stream.
class FinishReasonV1(object):
    NONE = 0
    STOP = 1
    LENGTH = 2
    TOOL_CALLS = 3
    CONTENT_FILTER = 4
    ERROR = 5
