# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

# Token stream event type.
class StreamEventV1(object):
    TOKEN = 0
    METADATA = 1
    DONE = 2
    ERROR = 3
    TOOL_CALL = 4
    CITATION = 5
