from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ToolCallV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ToolCallV1: ...
  @classmethod
  def GetRootAsToolCallV1(cls, buf: bytes, offset: int) -> ToolCallV1: ...
  @classmethod
  def ToolCallV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Name(self) -> str | None: ...
  def Arguments(self) -> str | None: ...
def ToolCallV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def ToolCallV1AddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def ToolCallV1AddName(builder: flatbuffers.Builder, name: uoffset) -> None: ...
def ToolCallV1AddArguments(builder: flatbuffers.Builder, arguments: uoffset) -> None: ...
def ToolCallV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

