# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

# Usage statistics for a completed response.
class UsageStatsV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UsageStatsV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUsageStatsV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def UsageStatsV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x41\x43\x56\x31", size_prefixed=size_prefixed)

    # UsageStatsV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Number of prompt tokens consumed.
    # UsageStatsV1
    def PromptTokens(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Number of completion tokens generated.
    # UsageStatsV1
    def CompletionTokens(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Total tokens (prompt + completion).
    # UsageStatsV1
    def TotalTokens(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Estimated cost in microdollars.
    # UsageStatsV1
    def CostMicrodollars(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def UsageStatsV1Start(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    UsageStatsV1Start(builder)

def UsageStatsV1AddPromptTokens(builder: flatbuffers.Builder, promptTokens: int):
    builder.PrependUint32Slot(0, promptTokens, 0)

def AddPromptTokens(builder: flatbuffers.Builder, promptTokens: int):
    UsageStatsV1AddPromptTokens(builder, promptTokens)

def UsageStatsV1AddCompletionTokens(builder: flatbuffers.Builder, completionTokens: int):
    builder.PrependUint32Slot(1, completionTokens, 0)

def AddCompletionTokens(builder: flatbuffers.Builder, completionTokens: int):
    UsageStatsV1AddCompletionTokens(builder, completionTokens)

def UsageStatsV1AddTotalTokens(builder: flatbuffers.Builder, totalTokens: int):
    builder.PrependUint32Slot(2, totalTokens, 0)

def AddTotalTokens(builder: flatbuffers.Builder, totalTokens: int):
    UsageStatsV1AddTotalTokens(builder, totalTokens)

def UsageStatsV1AddCostMicrodollars(builder: flatbuffers.Builder, costMicrodollars: int):
    builder.PrependUint32Slot(3, costMicrodollars, 0)

def AddCostMicrodollars(builder: flatbuffers.Builder, costMicrodollars: int):
    UsageStatsV1AddCostMicrodollars(builder, costMicrodollars)

def UsageStatsV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return UsageStatsV1End(builder)
