from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class UsageStatsV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> UsageStatsV1: ...
  @classmethod
  def GetRootAsUsageStatsV1(cls, buf: bytes, offset: int) -> UsageStatsV1: ...
  @classmethod
  def UsageStatsV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def PromptTokens(self) -> int: ...
  def CompletionTokens(self) -> int: ...
  def TotalTokens(self) -> int: ...
  def CostMicrodollars(self) -> int: ...
def UsageStatsV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def UsageStatsV1AddPromptTokens(builder: flatbuffers.Builder, promptTokens: int) -> None: ...
def UsageStatsV1AddCompletionTokens(builder: flatbuffers.Builder, completionTokens: int) -> None: ...
def UsageStatsV1AddTotalTokens(builder: flatbuffers.Builder, totalTokens: int) -> None: ...
def UsageStatsV1AddCostMicrodollars(builder: flatbuffers.Builder, costMicrodollars: int) -> None: ...
def UsageStatsV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

