/**
 * Canonical BaoDown native editor API re-exported from @baohaus/bao-core (single source of truth).
 * Named exports only — no `export * from` (per repo strict validators).
 * @module @baohaus/bao-shared/baodown/native-editor
 */
export type {
  BaoDownEditorBounds,
  BaoDownEditorConnectionValidation,
  BaoDownEditorDragSession,
  BaoDownEditorHistory,
  BaoDownEditorPendingConnection,
  BaoDownEditorPointer,
  BaoDownEditorPositionOptions,
  BaoDownEditorValidationCode,
  BaoDownEditorValidationIssue,
  BaoDownEditorValidationResult,
  BaoDownEditorValidationSeverity,
  BaoDownGraphInspectionResult,
  BaoDownNativeEditorState,
} from "@baohaus/bao-core/baodown/native-editor";

export {
  BAODOWN_CANVAS_NODE_HEIGHT_BASE,
  BAODOWN_CANVAS_NODE_WIDTH,
  BAODOWN_CANVAS_PORT_RADIUS,
  BAODOWN_CANVAS_PORT_SPACING,
  BAODOWN_EDITOR_DEFAULT_GRID_SIZE,
  BAODOWN_EDITOR_DEFAULT_HISTORY_LIMIT,
  beginBaoDownEditorConnection,
  beginBaoDownEditorNodeDrag,
  buildBaoDownEditorEdge,
  calculateBaoDownEdgePath,
  calculateBaoDownInputPortPosition,
  calculateBaoDownNodeHeight,
  calculateBaoDownOutputPortPosition,
  canRedoBaoDownEditor,
  canUndoBaoDownEditor,
  completeBaoDownEditorConnection,
  createBaoDownEditorHistory,
  createBaoDownNativeEditorState,
  endBaoDownEditorNodeDrag,
  formatBaoDownNodePosition,
  getBaoDownEditorNode,
  hasBaoDownEditorBlockingIssues,
  inspectBaoDownGraphCandidate,
  isBaoDownGraph,
  listBaoDownNodeConnections,
  pushBaoDownEditorHistory,
  redoBaoDownEditorHistory,
  removeBaoDownEditorEdge,
  removeBaoDownEditorNode,
  selectBaoDownEditorNode,
  serializeBaoDownNativeEditor,
  setBaoDownEditorNodePosition,
  undoBaoDownEditorHistory,
  updateBaoDownEditorNodeDrag,
  upsertBaoDownEditorEdge,
  upsertBaoDownEditorNode,
  validateBaoDownEditorConnection,
} from "@baohaus/bao-core/baodown/native-editor";
