# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

# Per-epoch metrics.
class EpochMetricsV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EpochMetricsV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEpochMetricsV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def EpochMetricsV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x50\x56\x31", size_prefixed=size_prefixed)

    # EpochMetricsV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Current epoch number (0-indexed).
    # EpochMetricsV1
    def Epoch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Total epochs planned.
    # EpochMetricsV1
    def TotalEpochs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Training loss value.
    # EpochMetricsV1
    def TrainLoss(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Validation loss value (NaN if not yet computed).
    # EpochMetricsV1
    def ValLoss(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Learning rate at this epoch.
    # EpochMetricsV1
    def LearningRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Loss metric type.
    # EpochMetricsV1
    def LossType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Samples processed this epoch.
    # EpochMetricsV1
    def SamplesProcessed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Total samples in the epoch.
    # EpochMetricsV1
    def TotalSamples(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Epoch duration in milliseconds.
    # EpochMetricsV1
    def EpochDurationMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def EpochMetricsV1Start(builder: flatbuffers.Builder):
    builder.StartObject(9)

def Start(builder: flatbuffers.Builder):
    EpochMetricsV1Start(builder)

def EpochMetricsV1AddEpoch(builder: flatbuffers.Builder, epoch: int):
    builder.PrependUint16Slot(0, epoch, 0)

def AddEpoch(builder: flatbuffers.Builder, epoch: int):
    EpochMetricsV1AddEpoch(builder, epoch)

def EpochMetricsV1AddTotalEpochs(builder: flatbuffers.Builder, totalEpochs: int):
    builder.PrependUint16Slot(1, totalEpochs, 0)

def AddTotalEpochs(builder: flatbuffers.Builder, totalEpochs: int):
    EpochMetricsV1AddTotalEpochs(builder, totalEpochs)

def EpochMetricsV1AddTrainLoss(builder: flatbuffers.Builder, trainLoss: float):
    builder.PrependFloat32Slot(2, trainLoss, 0.0)

def AddTrainLoss(builder: flatbuffers.Builder, trainLoss: float):
    EpochMetricsV1AddTrainLoss(builder, trainLoss)

def EpochMetricsV1AddValLoss(builder: flatbuffers.Builder, valLoss: float):
    builder.PrependFloat32Slot(3, valLoss, 0.0)

def AddValLoss(builder: flatbuffers.Builder, valLoss: float):
    EpochMetricsV1AddValLoss(builder, valLoss)

def EpochMetricsV1AddLearningRate(builder: flatbuffers.Builder, learningRate: float):
    builder.PrependFloat32Slot(4, learningRate, 0.0)

def AddLearningRate(builder: flatbuffers.Builder, learningRate: float):
    EpochMetricsV1AddLearningRate(builder, learningRate)

def EpochMetricsV1AddLossType(builder: flatbuffers.Builder, lossType: int):
    builder.PrependUint8Slot(5, lossType, 0)

def AddLossType(builder: flatbuffers.Builder, lossType: int):
    EpochMetricsV1AddLossType(builder, lossType)

def EpochMetricsV1AddSamplesProcessed(builder: flatbuffers.Builder, samplesProcessed: int):
    builder.PrependUint32Slot(6, samplesProcessed, 0)

def AddSamplesProcessed(builder: flatbuffers.Builder, samplesProcessed: int):
    EpochMetricsV1AddSamplesProcessed(builder, samplesProcessed)

def EpochMetricsV1AddTotalSamples(builder: flatbuffers.Builder, totalSamples: int):
    builder.PrependUint32Slot(7, totalSamples, 0)

def AddTotalSamples(builder: flatbuffers.Builder, totalSamples: int):
    EpochMetricsV1AddTotalSamples(builder, totalSamples)

def EpochMetricsV1AddEpochDurationMs(builder: flatbuffers.Builder, epochDurationMs: int):
    builder.PrependUint32Slot(8, epochDurationMs, 0)

def AddEpochDurationMs(builder: flatbuffers.Builder, epochDurationMs: int):
    EpochMetricsV1AddEpochDurationMs(builder, epochDurationMs)

def EpochMetricsV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return EpochMetricsV1End(builder)
