from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.training.v1.LossTypeV1 import LossTypeV1

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class EpochMetricsV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> EpochMetricsV1: ...
  @classmethod
  def GetRootAsEpochMetricsV1(cls, buf: bytes, offset: int) -> EpochMetricsV1: ...
  @classmethod
  def EpochMetricsV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Epoch(self) -> int: ...
  def TotalEpochs(self) -> int: ...
  def TrainLoss(self) -> float: ...
  def ValLoss(self) -> float: ...
  def LearningRate(self) -> float: ...
  def LossType(self) -> typing.Literal[LossTypeV1.CROSS_ENTROPY, LossTypeV1.MSE, LossTypeV1.MAE, LossTypeV1.CUSTOM]: ...
  def SamplesProcessed(self) -> int: ...
  def TotalSamples(self) -> int: ...
  def EpochDurationMs(self) -> int: ...
def EpochMetricsV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def EpochMetricsV1AddEpoch(builder: flatbuffers.Builder, epoch: int) -> None: ...
def EpochMetricsV1AddTotalEpochs(builder: flatbuffers.Builder, totalEpochs: int) -> None: ...
def EpochMetricsV1AddTrainLoss(builder: flatbuffers.Builder, trainLoss: float) -> None: ...
def EpochMetricsV1AddValLoss(builder: flatbuffers.Builder, valLoss: float) -> None: ...
def EpochMetricsV1AddLearningRate(builder: flatbuffers.Builder, learningRate: float) -> None: ...
def EpochMetricsV1AddLossType(builder: flatbuffers.Builder, lossType: typing.Literal[LossTypeV1.CROSS_ENTROPY, LossTypeV1.MSE, LossTypeV1.MAE, LossTypeV1.CUSTOM]) -> None: ...
def EpochMetricsV1AddSamplesProcessed(builder: flatbuffers.Builder, samplesProcessed: int) -> None: ...
def EpochMetricsV1AddTotalSamples(builder: flatbuffers.Builder, totalSamples: int) -> None: ...
def EpochMetricsV1AddEpochDurationMs(builder: flatbuffers.Builder, epochDurationMs: int) -> None: ...
def EpochMetricsV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

