# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

# Hardware utilization snapshot.
class HardwareSnapshotV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HardwareSnapshotV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHardwareSnapshotV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def HardwareSnapshotV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x50\x56\x31", size_prefixed=size_prefixed)

    # HardwareSnapshotV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GPU utilization percentage (0-100).
    # HardwareSnapshotV1
    def GpuUtilization(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # GPU memory used in MB.
    # HardwareSnapshotV1
    def GpuMemoryMb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # GPU temperature in Celsius.
    # HardwareSnapshotV1
    def GpuTempCelsius(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CPU utilization percentage (0-100).
    # HardwareSnapshotV1
    def CpuUtilization(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # System memory used in MB.
    # HardwareSnapshotV1
    def SystemMemoryMb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def HardwareSnapshotV1Start(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    HardwareSnapshotV1Start(builder)

def HardwareSnapshotV1AddGpuUtilization(builder: flatbuffers.Builder, gpuUtilization: int):
    builder.PrependUint8Slot(0, gpuUtilization, 0)

def AddGpuUtilization(builder: flatbuffers.Builder, gpuUtilization: int):
    HardwareSnapshotV1AddGpuUtilization(builder, gpuUtilization)

def HardwareSnapshotV1AddGpuMemoryMb(builder: flatbuffers.Builder, gpuMemoryMb: int):
    builder.PrependUint32Slot(1, gpuMemoryMb, 0)

def AddGpuMemoryMb(builder: flatbuffers.Builder, gpuMemoryMb: int):
    HardwareSnapshotV1AddGpuMemoryMb(builder, gpuMemoryMb)

def HardwareSnapshotV1AddGpuTempCelsius(builder: flatbuffers.Builder, gpuTempCelsius: int):
    builder.PrependUint8Slot(2, gpuTempCelsius, 0)

def AddGpuTempCelsius(builder: flatbuffers.Builder, gpuTempCelsius: int):
    HardwareSnapshotV1AddGpuTempCelsius(builder, gpuTempCelsius)

def HardwareSnapshotV1AddCpuUtilization(builder: flatbuffers.Builder, cpuUtilization: int):
    builder.PrependUint8Slot(3, cpuUtilization, 0)

def AddCpuUtilization(builder: flatbuffers.Builder, cpuUtilization: int):
    HardwareSnapshotV1AddCpuUtilization(builder, cpuUtilization)

def HardwareSnapshotV1AddSystemMemoryMb(builder: flatbuffers.Builder, systemMemoryMb: int):
    builder.PrependUint32Slot(4, systemMemoryMb, 0)

def AddSystemMemoryMb(builder: flatbuffers.Builder, systemMemoryMb: int):
    HardwareSnapshotV1AddSystemMemoryMb(builder, systemMemoryMb)

def HardwareSnapshotV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return HardwareSnapshotV1End(builder)
