from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class HardwareSnapshotV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> HardwareSnapshotV1: ...
  @classmethod
  def GetRootAsHardwareSnapshotV1(cls, buf: bytes, offset: int) -> HardwareSnapshotV1: ...
  @classmethod
  def HardwareSnapshotV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def GpuUtilization(self) -> int: ...
  def GpuMemoryMb(self) -> int: ...
  def GpuTempCelsius(self) -> int: ...
  def CpuUtilization(self) -> int: ...
  def SystemMemoryMb(self) -> int: ...
def HardwareSnapshotV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def HardwareSnapshotV1AddGpuUtilization(builder: flatbuffers.Builder, gpuUtilization: int) -> None: ...
def HardwareSnapshotV1AddGpuMemoryMb(builder: flatbuffers.Builder, gpuMemoryMb: int) -> None: ...
def HardwareSnapshotV1AddGpuTempCelsius(builder: flatbuffers.Builder, gpuTempCelsius: int) -> None: ...
def HardwareSnapshotV1AddCpuUtilization(builder: flatbuffers.Builder, cpuUtilization: int) -> None: ...
def HardwareSnapshotV1AddSystemMemoryMb(builder: flatbuffers.Builder, systemMemoryMb: int) -> None: ...
def HardwareSnapshotV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

