from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.training.v1.EpochMetricsV1 import EpochMetricsV1
from baohaus.training.v1.HardwareSnapshotV1 import HardwareSnapshotV1
from baohaus.training.v1.TrainingStageV1 import TrainingStageV1

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class TrainingProgressV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TrainingProgressV1: ...
  @classmethod
  def GetRootAsTrainingProgressV1(cls, buf: bytes, offset: int) -> TrainingProgressV1: ...
  @classmethod
  def TrainingProgressV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def CorrelationId(self) -> str | None: ...
  def JobId(self) -> str | None: ...
  def ModelId(self) -> str | None: ...
  def Stage(self) -> typing.Literal[TrainingStageV1.IDLE, TrainingStageV1.DATA_LOADING, TrainingStageV1.PREPROCESSING, TrainingStageV1.TRAINING, TrainingStageV1.VALIDATION, TrainingStageV1.EVALUATION, TrainingStageV1.EXPORT, TrainingStageV1.COMPLETED, TrainingStageV1.FAILED, TrainingStageV1.CANCELLED]: ...
  def ProgressPct(self) -> float: ...
  def ElapsedMs(self) -> int: ...
  def EtaMs(self) -> int: ...
  def EpochMetrics(self) -> EpochMetricsV1 | None: ...
  def Hardware(self) -> HardwareSnapshotV1 | None: ...
  def StatusMessage(self) -> str | None: ...
  def TimestampMs(self) -> int: ...
  def ErrorMessage(self) -> str | None: ...
def TrainingProgressV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def TrainingProgressV1AddCorrelationId(builder: flatbuffers.Builder, correlationId: uoffset) -> None: ...
def TrainingProgressV1AddJobId(builder: flatbuffers.Builder, jobId: uoffset) -> None: ...
def TrainingProgressV1AddModelId(builder: flatbuffers.Builder, modelId: uoffset) -> None: ...
def TrainingProgressV1AddStage(builder: flatbuffers.Builder, stage: typing.Literal[TrainingStageV1.IDLE, TrainingStageV1.DATA_LOADING, TrainingStageV1.PREPROCESSING, TrainingStageV1.TRAINING, TrainingStageV1.VALIDATION, TrainingStageV1.EVALUATION, TrainingStageV1.EXPORT, TrainingStageV1.COMPLETED, TrainingStageV1.FAILED, TrainingStageV1.CANCELLED]) -> None: ...
def TrainingProgressV1AddProgressPct(builder: flatbuffers.Builder, progressPct: float) -> None: ...
def TrainingProgressV1AddElapsedMs(builder: flatbuffers.Builder, elapsedMs: int) -> None: ...
def TrainingProgressV1AddEtaMs(builder: flatbuffers.Builder, etaMs: int) -> None: ...
def TrainingProgressV1AddEpochMetrics(builder: flatbuffers.Builder, epochMetrics: uoffset) -> None: ...
def TrainingProgressV1AddHardware(builder: flatbuffers.Builder, hardware: uoffset) -> None: ...
def TrainingProgressV1AddStatusMessage(builder: flatbuffers.Builder, statusMessage: uoffset) -> None: ...
def TrainingProgressV1AddTimestampMs(builder: flatbuffers.Builder, timestampMs: int) -> None: ...
def TrainingProgressV1AddErrorMessage(builder: flatbuffers.Builder, errorMessage: uoffset) -> None: ...
def TrainingProgressV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

