# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

# Training stage identifier.
class TrainingStageV1(object):
    IDLE = 0
    DATA_LOADING = 1
    PREPROCESSING = 2
    TRAINING = 3
    VALIDATION = 4
    EVALUATION = 5
    EXPORT = 6
    COMPLETED = 7
    FAILED = 8
    CANCELLED = 9
