# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
from baohaus.training.v1.EpochMetricsV1 import EpochMetricsV1
from baohaus.training.v1.HardwareSnapshotV1 import HardwareSnapshotV1
np = import_numpy()

# Training progress update message.
class TrainingProgressV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrainingProgressV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTrainingProgressV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def TrainingProgressV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x50\x56\x31", size_prefixed=size_prefixed)

    # TrainingProgressV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Correlation ID for request tracing.
    # TrainingProgressV1
    def CorrelationId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Training job identifier.
    # TrainingProgressV1
    def JobId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Model identifier.
    # TrainingProgressV1
    def ModelId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Current training stage.
    # TrainingProgressV1
    def Stage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Overall progress percentage (0.0–100.0).
    # TrainingProgressV1
    def ProgressPct(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Wall-clock elapsed time in milliseconds.
    # TrainingProgressV1
    def ElapsedMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Estimated remaining time in milliseconds.
    # TrainingProgressV1
    def EtaMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Current epoch metrics (when in TRAINING or VALIDATION stage).
    # TrainingProgressV1
    def EpochMetrics(self) -> Optional[EpochMetricsV1]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = EpochMetricsV1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Hardware utilization snapshot.
    # TrainingProgressV1
    def Hardware(self) -> Optional[HardwareSnapshotV1]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = HardwareSnapshotV1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # User-visible status message.
    # TrainingProgressV1
    def StatusMessage(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Timestamp in milliseconds since epoch.
    # TrainingProgressV1
    def TimestampMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Error message (when stage = FAILED).
    # TrainingProgressV1
    def ErrorMessage(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def TrainingProgressV1Start(builder: flatbuffers.Builder):
    builder.StartObject(12)

def Start(builder: flatbuffers.Builder):
    TrainingProgressV1Start(builder)

def TrainingProgressV1AddCorrelationId(builder: flatbuffers.Builder, correlationId: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(correlationId), 0)

def AddCorrelationId(builder: flatbuffers.Builder, correlationId: int):
    TrainingProgressV1AddCorrelationId(builder, correlationId)

def TrainingProgressV1AddJobId(builder: flatbuffers.Builder, jobId: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(jobId), 0)

def AddJobId(builder: flatbuffers.Builder, jobId: int):
    TrainingProgressV1AddJobId(builder, jobId)

def TrainingProgressV1AddModelId(builder: flatbuffers.Builder, modelId: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(modelId), 0)

def AddModelId(builder: flatbuffers.Builder, modelId: int):
    TrainingProgressV1AddModelId(builder, modelId)

def TrainingProgressV1AddStage(builder: flatbuffers.Builder, stage: int):
    builder.PrependUint8Slot(3, stage, 0)

def AddStage(builder: flatbuffers.Builder, stage: int):
    TrainingProgressV1AddStage(builder, stage)

def TrainingProgressV1AddProgressPct(builder: flatbuffers.Builder, progressPct: float):
    builder.PrependFloat32Slot(4, progressPct, 0.0)

def AddProgressPct(builder: flatbuffers.Builder, progressPct: float):
    TrainingProgressV1AddProgressPct(builder, progressPct)

def TrainingProgressV1AddElapsedMs(builder: flatbuffers.Builder, elapsedMs: int):
    builder.PrependUint64Slot(5, elapsedMs, 0)

def AddElapsedMs(builder: flatbuffers.Builder, elapsedMs: int):
    TrainingProgressV1AddElapsedMs(builder, elapsedMs)

def TrainingProgressV1AddEtaMs(builder: flatbuffers.Builder, etaMs: int):
    builder.PrependUint64Slot(6, etaMs, 0)

def AddEtaMs(builder: flatbuffers.Builder, etaMs: int):
    TrainingProgressV1AddEtaMs(builder, etaMs)

def TrainingProgressV1AddEpochMetrics(builder: flatbuffers.Builder, epochMetrics: int):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(epochMetrics), 0)

def AddEpochMetrics(builder: flatbuffers.Builder, epochMetrics: int):
    TrainingProgressV1AddEpochMetrics(builder, epochMetrics)

def TrainingProgressV1AddHardware(builder: flatbuffers.Builder, hardware: int):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(hardware), 0)

def AddHardware(builder: flatbuffers.Builder, hardware: int):
    TrainingProgressV1AddHardware(builder, hardware)

def TrainingProgressV1AddStatusMessage(builder: flatbuffers.Builder, statusMessage: int):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(statusMessage), 0)

def AddStatusMessage(builder: flatbuffers.Builder, statusMessage: int):
    TrainingProgressV1AddStatusMessage(builder, statusMessage)

def TrainingProgressV1AddTimestampMs(builder: flatbuffers.Builder, timestampMs: int):
    builder.PrependUint64Slot(10, timestampMs, 0)

def AddTimestampMs(builder: flatbuffers.Builder, timestampMs: int):
    TrainingProgressV1AddTimestampMs(builder, timestampMs)

def TrainingProgressV1AddErrorMessage(builder: flatbuffers.Builder, errorMessage: int):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(errorMessage), 0)

def AddErrorMessage(builder: flatbuffers.Builder, errorMessage: int):
    TrainingProgressV1AddErrorMessage(builder, errorMessage)

def TrainingProgressV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return TrainingProgressV1End(builder)
