# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
from baohaus.training.v1.TrainingProgressV1 import TrainingProgressV1
np = import_numpy()

# Batch of training progress updates.
class TrainingProgressBatchV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrainingProgressBatchV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTrainingProgressBatchV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def TrainingProgressBatchV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x50\x56\x31", size_prefixed=size_prefixed)

    # TrainingProgressBatchV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Batch of progress updates.
    # TrainingProgressBatchV1
    def Updates(self, j: int) -> Optional[TrainingProgressV1]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = TrainingProgressV1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrainingProgressBatchV1
    def UpdatesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TrainingProgressBatchV1
    def UpdatesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def TrainingProgressBatchV1Start(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    TrainingProgressBatchV1Start(builder)

def TrainingProgressBatchV1AddUpdates(builder: flatbuffers.Builder, updates: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(updates), 0)

def AddUpdates(builder: flatbuffers.Builder, updates: int):
    TrainingProgressBatchV1AddUpdates(builder, updates)

def TrainingProgressBatchV1StartUpdatesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartUpdatesVector(builder, numElems: int) -> int:
    return TrainingProgressBatchV1StartUpdatesVector(builder, numElems)

def TrainingProgressBatchV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return TrainingProgressBatchV1End(builder)
