from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.training.v1.TrainingProgressV1 import TrainingProgressV1

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class TrainingProgressBatchV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TrainingProgressBatchV1: ...
  @classmethod
  def GetRootAsTrainingProgressBatchV1(cls, buf: bytes, offset: int) -> TrainingProgressBatchV1: ...
  @classmethod
  def TrainingProgressBatchV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Updates(self, i: int) -> TrainingProgressV1 | None: ...
  def UpdatesLength(self) -> int: ...
  def UpdatesIsNone(self) -> bool: ...
def TrainingProgressBatchV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def TrainingProgressBatchV1AddUpdates(builder: flatbuffers.Builder, updates: uoffset) -> None: ...
def TrainingProgressBatchV1StartUpdatesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartUpdatesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def TrainingProgressBatchV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

