# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class BaoInstallEventV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BaoInstallEventV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBaoInstallEventV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BaoInstallEventV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x45\x56\x31", size_prefixed=size_prefixed)

    # BaoInstallEventV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BaoInstallEventV1
    def RunId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoInstallEventV1
    def Phase(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoInstallEventV1
    def ManifestName(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoInstallEventV1
    def ManifestVersion(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoInstallEventV1
    def TargetCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # BaoInstallEventV1
    def DurationMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # BaoInstallEventV1
    def Message(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def BaoInstallEventV1Start(builder: flatbuffers.Builder):
    builder.StartObject(7)

def Start(builder: flatbuffers.Builder):
    BaoInstallEventV1Start(builder)

def BaoInstallEventV1AddRunId(builder: flatbuffers.Builder, runId: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(runId), 0)

def AddRunId(builder: flatbuffers.Builder, runId: int):
    BaoInstallEventV1AddRunId(builder, runId)

def BaoInstallEventV1AddPhase(builder: flatbuffers.Builder, phase: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(phase), 0)

def AddPhase(builder: flatbuffers.Builder, phase: int):
    BaoInstallEventV1AddPhase(builder, phase)

def BaoInstallEventV1AddManifestName(builder: flatbuffers.Builder, manifestName: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(manifestName), 0)

def AddManifestName(builder: flatbuffers.Builder, manifestName: int):
    BaoInstallEventV1AddManifestName(builder, manifestName)

def BaoInstallEventV1AddManifestVersion(builder: flatbuffers.Builder, manifestVersion: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(manifestVersion), 0)

def AddManifestVersion(builder: flatbuffers.Builder, manifestVersion: int):
    BaoInstallEventV1AddManifestVersion(builder, manifestVersion)

def BaoInstallEventV1AddTargetCount(builder: flatbuffers.Builder, targetCount: int):
    builder.PrependUint32Slot(4, targetCount, 0)

def AddTargetCount(builder: flatbuffers.Builder, targetCount: int):
    BaoInstallEventV1AddTargetCount(builder, targetCount)

def BaoInstallEventV1AddDurationMs(builder: flatbuffers.Builder, durationMs: int):
    builder.PrependUint32Slot(5, durationMs, 0)

def AddDurationMs(builder: flatbuffers.Builder, durationMs: int):
    BaoInstallEventV1AddDurationMs(builder, durationMs)

def BaoInstallEventV1AddMessage(builder: flatbuffers.Builder, message: int):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder: flatbuffers.Builder, message: int):
    BaoInstallEventV1AddMessage(builder, message)

def BaoInstallEventV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return BaoInstallEventV1End(builder)
