# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class BunBuddyProbeEventV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BunBuddyProbeEventV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBunBuddyProbeEventV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BunBuddyProbeEventV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x45\x56\x31", size_prefixed=size_prefixed)

    # BunBuddyProbeEventV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BunBuddyProbeEventV1
    def RunId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BunBuddyProbeEventV1
    def BunbuddyId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BunBuddyProbeEventV1
    def Phase(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BunBuddyProbeEventV1
    def LatencyMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # BunBuddyProbeEventV1
    def Message(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def BunBuddyProbeEventV1Start(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    BunBuddyProbeEventV1Start(builder)

def BunBuddyProbeEventV1AddRunId(builder: flatbuffers.Builder, runId: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(runId), 0)

def AddRunId(builder: flatbuffers.Builder, runId: int):
    BunBuddyProbeEventV1AddRunId(builder, runId)

def BunBuddyProbeEventV1AddBunbuddyId(builder: flatbuffers.Builder, bunbuddyId: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(bunbuddyId), 0)

def AddBunbuddyId(builder: flatbuffers.Builder, bunbuddyId: int):
    BunBuddyProbeEventV1AddBunbuddyId(builder, bunbuddyId)

def BunBuddyProbeEventV1AddPhase(builder: flatbuffers.Builder, phase: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(phase), 0)

def AddPhase(builder: flatbuffers.Builder, phase: int):
    BunBuddyProbeEventV1AddPhase(builder, phase)

def BunBuddyProbeEventV1AddLatencyMs(builder: flatbuffers.Builder, latencyMs: int):
    builder.PrependUint32Slot(3, latencyMs, 0)

def AddLatencyMs(builder: flatbuffers.Builder, latencyMs: int):
    BunBuddyProbeEventV1AddLatencyMs(builder, latencyMs)

def BunBuddyProbeEventV1AddMessage(builder: flatbuffers.Builder, message: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder: flatbuffers.Builder, message: int):
    BunBuddyProbeEventV1AddMessage(builder, message)

def BunBuddyProbeEventV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return BunBuddyProbeEventV1End(builder)
