# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class CacheEnvelopeV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CacheEnvelopeV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCacheEnvelopeV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CacheEnvelopeV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x45\x56\x31", size_prefixed=size_prefixed)

    # CacheEnvelopeV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CacheEnvelopeV1
    def CachedAtMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CacheEnvelopeV1
    def Fingerprint(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CacheEnvelopeV1
    def ValueFormat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CacheEnvelopeV1
    def ValueBytes(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # CacheEnvelopeV1
    def ValueBytesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # CacheEnvelopeV1
    def ValueBytesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CacheEnvelopeV1
    def ValueBytesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Optional schema version for debug and compatibility checks.
    # CacheEnvelopeV1
    def SchemaVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 1

    # Optional generation timestamp (ISO 8601) for debugging.
    # CacheEnvelopeV1
    def GenerationTimestamp(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def CacheEnvelopeV1Start(builder: flatbuffers.Builder):
    builder.StartObject(6)

def Start(builder: flatbuffers.Builder):
    CacheEnvelopeV1Start(builder)

def CacheEnvelopeV1AddCachedAtMs(builder: flatbuffers.Builder, cachedAtMs: int):
    builder.PrependUint64Slot(0, cachedAtMs, 0)

def AddCachedAtMs(builder: flatbuffers.Builder, cachedAtMs: int):
    CacheEnvelopeV1AddCachedAtMs(builder, cachedAtMs)

def CacheEnvelopeV1AddFingerprint(builder: flatbuffers.Builder, fingerprint: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(fingerprint), 0)

def AddFingerprint(builder: flatbuffers.Builder, fingerprint: int):
    CacheEnvelopeV1AddFingerprint(builder, fingerprint)

def CacheEnvelopeV1AddValueFormat(builder: flatbuffers.Builder, valueFormat: int):
    builder.PrependUint8Slot(2, valueFormat, 0)

def AddValueFormat(builder: flatbuffers.Builder, valueFormat: int):
    CacheEnvelopeV1AddValueFormat(builder, valueFormat)

def CacheEnvelopeV1AddValueBytes(builder: flatbuffers.Builder, valueBytes: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(valueBytes), 0)

def AddValueBytes(builder: flatbuffers.Builder, valueBytes: int):
    CacheEnvelopeV1AddValueBytes(builder, valueBytes)

def CacheEnvelopeV1StartValueBytesVector(builder, numElems: int) -> int:
    return builder.StartVector(1, numElems, 1)

def StartValueBytesVector(builder, numElems: int) -> int:
    return CacheEnvelopeV1StartValueBytesVector(builder, numElems)

def CacheEnvelopeV1AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: int):
    builder.PrependUint32Slot(4, schemaVersion, 1)

def AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: int):
    CacheEnvelopeV1AddSchemaVersion(builder, schemaVersion)

def CacheEnvelopeV1AddGenerationTimestamp(builder: flatbuffers.Builder, generationTimestamp: int):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(generationTimestamp), 0)

def AddGenerationTimestamp(builder: flatbuffers.Builder, generationTimestamp: int):
    CacheEnvelopeV1AddGenerationTimestamp(builder, generationTimestamp)

def CacheEnvelopeV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return CacheEnvelopeV1End(builder)
