# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class GitOpsSyncEventV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GitOpsSyncEventV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGitOpsSyncEventV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def GitOpsSyncEventV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x45\x56\x31", size_prefixed=size_prefixed)

    # GitOpsSyncEventV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GitOpsSyncEventV1
    def RunId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GitOpsSyncEventV1
    def Phase(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GitOpsSyncEventV1
    def Commit(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GitOpsSyncEventV1
    def Message(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def GitOpsSyncEventV1Start(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    GitOpsSyncEventV1Start(builder)

def GitOpsSyncEventV1AddRunId(builder: flatbuffers.Builder, runId: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(runId), 0)

def AddRunId(builder: flatbuffers.Builder, runId: int):
    GitOpsSyncEventV1AddRunId(builder, runId)

def GitOpsSyncEventV1AddPhase(builder: flatbuffers.Builder, phase: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(phase), 0)

def AddPhase(builder: flatbuffers.Builder, phase: int):
    GitOpsSyncEventV1AddPhase(builder, phase)

def GitOpsSyncEventV1AddCommit(builder: flatbuffers.Builder, commit: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(commit), 0)

def AddCommit(builder: flatbuffers.Builder, commit: int):
    GitOpsSyncEventV1AddCommit(builder, commit)

def GitOpsSyncEventV1AddMessage(builder: flatbuffers.Builder, message: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder: flatbuffers.Builder, message: int):
    GitOpsSyncEventV1AddMessage(builder, message)

def GitOpsSyncEventV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return GitOpsSyncEventV1End(builder)
