# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class ModuleLifecycleEventV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ModuleLifecycleEventV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsModuleLifecycleEventV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ModuleLifecycleEventV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x45\x56\x31", size_prefixed=size_prefixed)

    # ModuleLifecycleEventV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ModuleLifecycleEventV1
    def RunId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ModuleLifecycleEventV1
    def ModuleId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ModuleLifecycleEventV1
    def Lifecycle(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ModuleLifecycleEventV1
    def State(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ModuleLifecycleEventV1
    def HealthState(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ModuleLifecycleEventV1
    def DurationMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ModuleLifecycleEventV1
    def Message(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ModuleLifecycleEventV1Start(builder: flatbuffers.Builder):
    builder.StartObject(7)

def Start(builder: flatbuffers.Builder):
    ModuleLifecycleEventV1Start(builder)

def ModuleLifecycleEventV1AddRunId(builder: flatbuffers.Builder, runId: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(runId), 0)

def AddRunId(builder: flatbuffers.Builder, runId: int):
    ModuleLifecycleEventV1AddRunId(builder, runId)

def ModuleLifecycleEventV1AddModuleId(builder: flatbuffers.Builder, moduleId: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(moduleId), 0)

def AddModuleId(builder: flatbuffers.Builder, moduleId: int):
    ModuleLifecycleEventV1AddModuleId(builder, moduleId)

def ModuleLifecycleEventV1AddLifecycle(builder: flatbuffers.Builder, lifecycle: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(lifecycle), 0)

def AddLifecycle(builder: flatbuffers.Builder, lifecycle: int):
    ModuleLifecycleEventV1AddLifecycle(builder, lifecycle)

def ModuleLifecycleEventV1AddState(builder: flatbuffers.Builder, state: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(state), 0)

def AddState(builder: flatbuffers.Builder, state: int):
    ModuleLifecycleEventV1AddState(builder, state)

def ModuleLifecycleEventV1AddHealthState(builder: flatbuffers.Builder, healthState: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(healthState), 0)

def AddHealthState(builder: flatbuffers.Builder, healthState: int):
    ModuleLifecycleEventV1AddHealthState(builder, healthState)

def ModuleLifecycleEventV1AddDurationMs(builder: flatbuffers.Builder, durationMs: int):
    builder.PrependUint32Slot(5, durationMs, 0)

def AddDurationMs(builder: flatbuffers.Builder, durationMs: int):
    ModuleLifecycleEventV1AddDurationMs(builder, durationMs)

def ModuleLifecycleEventV1AddMessage(builder: flatbuffers.Builder, message: int):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder: flatbuffers.Builder, message: int):
    ModuleLifecycleEventV1AddMessage(builder, message)

def ModuleLifecycleEventV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return ModuleLifecycleEventV1End(builder)
