// AUTO-GENERATED by @baohaus/sdk-codegen-bao for @baohaus/bao-registry@0.1.0
// Source: GET /v2/_catalog
// Do not edit by hand — re-run `bun run sdk:gen` after spec changes.

import { toResultAsync } from "@baohaus/bao-utils/async-result";
import type { BaoError } from "@baohaus/bao-utils/canonical/bao-error";
import { buildBaoError } from "@baohaus/bao-utils/canonical/bao-error";

export type getV2CatalogOptions = {
  readonly baseUrl: string;
  readonly init?: RequestInit;
  readonly pathParams?: Readonly<Record<string, string>>;
  readonly query?: Readonly<Record<string, string>>;
};

export type getV2CatalogResponse = {
  readonly status: number;
  readonly headers: Headers;
  readonly body: string;
};

export async function getV2Catalog(
  options: getV2CatalogOptions,
): Promise<{ ok: true; value: getV2CatalogResponse } | { ok: false; error: BaoError }> {
  const params = options.pathParams ?? {};
  const pathTemplate = "/v2/_catalog";
  const path = pathTemplate.replace(/\{([^}]+)\}/g, (_match, key) => params[key] ?? `{${key}}`);
  const queryString = options.query ? `?${new URLSearchParams(options.query).toString()}` : "";
  const url = options.baseUrl + path + queryString;
  const fetchResult = await toResultAsync<Response, BaoError>(
    fetch(url, { method: "GET", ...options.init }),
    (error) =>
      buildBaoError({
        code: "SDK_GETV2CATALOG_FETCH_FAILED",
        kind: "upstream",
        message: `fetch to ${url} failed`,
        details: { url, cause: error instanceof Error ? error.message : String(error) },
      }),
  );
  if (!fetchResult.ok) {
    return fetchResult;
  }
  const response = fetchResult.value;
  const bodyResult = await toResultAsync<string, BaoError>(response.text(), (error) =>
    buildBaoError({
      code: "SDK_GETV2CATALOG_BODY_READ_FAILED",
      kind: "io",
      message: `reading response body for ${url} failed`,
      details: { url, cause: error instanceof Error ? error.message : String(error) },
    }),
  );
  if (!bodyResult.ok) {
    return bodyResult;
  }
  return {
    ok: true,
    value: { status: response.status, headers: response.headers, body: bodyResult.value },
  };
}
