# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
from baohaus.observability.v1.SpanV1 import SpanV1
np = import_numpy()

# Batch of spans for a single service.
class ObservabilityBatchV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ObservabilityBatchV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsObservabilityBatchV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ObservabilityBatchV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4F\x42\x53\x31", size_prefixed=size_prefixed)

    # ObservabilityBatchV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ObservabilityBatchV1
    def ServiceName(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ObservabilityBatchV1
    def BatchId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ObservabilityBatchV1
    def Timestamp(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ObservabilityBatchV1
    def Spans(self, j: int) -> Optional[SpanV1]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = SpanV1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ObservabilityBatchV1
    def SpansLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ObservabilityBatchV1
    def SpansIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # ObservabilityBatchV1
    def DroppedCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ObservabilityBatchV1Start(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    ObservabilityBatchV1Start(builder)

def ObservabilityBatchV1AddServiceName(builder: flatbuffers.Builder, serviceName: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(serviceName), 0)

def AddServiceName(builder: flatbuffers.Builder, serviceName: int):
    ObservabilityBatchV1AddServiceName(builder, serviceName)

def ObservabilityBatchV1AddBatchId(builder: flatbuffers.Builder, batchId: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(batchId), 0)

def AddBatchId(builder: flatbuffers.Builder, batchId: int):
    ObservabilityBatchV1AddBatchId(builder, batchId)

def ObservabilityBatchV1AddTimestamp(builder: flatbuffers.Builder, timestamp: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder: flatbuffers.Builder, timestamp: int):
    ObservabilityBatchV1AddTimestamp(builder, timestamp)

def ObservabilityBatchV1AddSpans(builder: flatbuffers.Builder, spans: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(spans), 0)

def AddSpans(builder: flatbuffers.Builder, spans: int):
    ObservabilityBatchV1AddSpans(builder, spans)

def ObservabilityBatchV1StartSpansVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartSpansVector(builder, numElems: int) -> int:
    return ObservabilityBatchV1StartSpansVector(builder, numElems)

def ObservabilityBatchV1AddDroppedCount(builder: flatbuffers.Builder, droppedCount: int):
    builder.PrependUint32Slot(4, droppedCount, 0)

def AddDroppedCount(builder: flatbuffers.Builder, droppedCount: int):
    ObservabilityBatchV1AddDroppedCount(builder, droppedCount)

def ObservabilityBatchV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return ObservabilityBatchV1End(builder)
