from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.observability.v1.SpanV1 import SpanV1

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ObservabilityBatchV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ObservabilityBatchV1: ...
  @classmethod
  def GetRootAsObservabilityBatchV1(cls, buf: bytes, offset: int) -> ObservabilityBatchV1: ...
  @classmethod
  def ObservabilityBatchV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def ServiceName(self) -> str | None: ...
  def BatchId(self) -> str | None: ...
  def Timestamp(self) -> str | None: ...
  def Spans(self, i: int) -> SpanV1 | None: ...
  def SpansLength(self) -> int: ...
  def SpansIsNone(self) -> bool: ...
  def DroppedCount(self) -> int: ...
def ObservabilityBatchV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def ObservabilityBatchV1AddServiceName(builder: flatbuffers.Builder, serviceName: uoffset) -> None: ...
def ObservabilityBatchV1AddBatchId(builder: flatbuffers.Builder, batchId: uoffset) -> None: ...
def ObservabilityBatchV1AddTimestamp(builder: flatbuffers.Builder, timestamp: uoffset) -> None: ...
def ObservabilityBatchV1AddSpans(builder: flatbuffers.Builder, spans: uoffset) -> None: ...
def ObservabilityBatchV1StartSpansVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartSpansVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def ObservabilityBatchV1AddDroppedCount(builder: flatbuffers.Builder, droppedCount: int) -> None: ...
def ObservabilityBatchV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

