# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

# Trace span for batch export.
class SpanV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SpanV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSpanV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SpanV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4F\x42\x53\x31", size_prefixed=size_prefixed)

    # SpanV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SpanV1
    def TraceId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SpanV1
    def SpanId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SpanV1
    def ParentSpanId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SpanV1
    def Name(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SpanV1
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # SpanV1
    def StartTimeUnixNano(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # SpanV1
    def EndTimeUnixNano(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # SpanV1
    def StatusCode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # SpanV1
    def StatusMessage(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SpanV1
    def AttributesJson(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SpanV1Start(builder: flatbuffers.Builder):
    builder.StartObject(10)

def Start(builder: flatbuffers.Builder):
    SpanV1Start(builder)

def SpanV1AddTraceId(builder: flatbuffers.Builder, traceId: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(traceId), 0)

def AddTraceId(builder: flatbuffers.Builder, traceId: int):
    SpanV1AddTraceId(builder, traceId)

def SpanV1AddSpanId(builder: flatbuffers.Builder, spanId: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(spanId), 0)

def AddSpanId(builder: flatbuffers.Builder, spanId: int):
    SpanV1AddSpanId(builder, spanId)

def SpanV1AddParentSpanId(builder: flatbuffers.Builder, parentSpanId: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(parentSpanId), 0)

def AddParentSpanId(builder: flatbuffers.Builder, parentSpanId: int):
    SpanV1AddParentSpanId(builder, parentSpanId)

def SpanV1AddName(builder: flatbuffers.Builder, name: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder: flatbuffers.Builder, name: int):
    SpanV1AddName(builder, name)

def SpanV1AddKind(builder: flatbuffers.Builder, kind: int):
    builder.PrependUint8Slot(4, kind, 0)

def AddKind(builder: flatbuffers.Builder, kind: int):
    SpanV1AddKind(builder, kind)

def SpanV1AddStartTimeUnixNano(builder: flatbuffers.Builder, startTimeUnixNano: int):
    builder.PrependUint64Slot(5, startTimeUnixNano, 0)

def AddStartTimeUnixNano(builder: flatbuffers.Builder, startTimeUnixNano: int):
    SpanV1AddStartTimeUnixNano(builder, startTimeUnixNano)

def SpanV1AddEndTimeUnixNano(builder: flatbuffers.Builder, endTimeUnixNano: int):
    builder.PrependUint64Slot(6, endTimeUnixNano, 0)

def AddEndTimeUnixNano(builder: flatbuffers.Builder, endTimeUnixNano: int):
    SpanV1AddEndTimeUnixNano(builder, endTimeUnixNano)

def SpanV1AddStatusCode(builder: flatbuffers.Builder, statusCode: int):
    builder.PrependUint8Slot(7, statusCode, 0)

def AddStatusCode(builder: flatbuffers.Builder, statusCode: int):
    SpanV1AddStatusCode(builder, statusCode)

def SpanV1AddStatusMessage(builder: flatbuffers.Builder, statusMessage: int):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(statusMessage), 0)

def AddStatusMessage(builder: flatbuffers.Builder, statusMessage: int):
    SpanV1AddStatusMessage(builder, statusMessage)

def SpanV1AddAttributesJson(builder: flatbuffers.Builder, attributesJson: int):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(attributesJson), 0)

def AddAttributesJson(builder: flatbuffers.Builder, attributesJson: int):
    SpanV1AddAttributesJson(builder, attributesJson)

def SpanV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return SpanV1End(builder)
