from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class SpanV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> SpanV1: ...
  @classmethod
  def GetRootAsSpanV1(cls, buf: bytes, offset: int) -> SpanV1: ...
  @classmethod
  def SpanV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def TraceId(self) -> str | None: ...
  def SpanId(self) -> str | None: ...
  def ParentSpanId(self) -> str | None: ...
  def Name(self) -> str | None: ...
  def Kind(self) -> int: ...
  def StartTimeUnixNano(self) -> int: ...
  def EndTimeUnixNano(self) -> int: ...
  def StatusCode(self) -> int: ...
  def StatusMessage(self) -> str | None: ...
  def AttributesJson(self) -> str | None: ...
def SpanV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def SpanV1AddTraceId(builder: flatbuffers.Builder, traceId: uoffset) -> None: ...
def SpanV1AddSpanId(builder: flatbuffers.Builder, spanId: uoffset) -> None: ...
def SpanV1AddParentSpanId(builder: flatbuffers.Builder, parentSpanId: uoffset) -> None: ...
def SpanV1AddName(builder: flatbuffers.Builder, name: uoffset) -> None: ...
def SpanV1AddKind(builder: flatbuffers.Builder, kind: int) -> None: ...
def SpanV1AddStartTimeUnixNano(builder: flatbuffers.Builder, startTimeUnixNano: int) -> None: ...
def SpanV1AddEndTimeUnixNano(builder: flatbuffers.Builder, endTimeUnixNano: int) -> None: ...
def SpanV1AddStatusCode(builder: flatbuffers.Builder, statusCode: int) -> None: ...
def SpanV1AddStatusMessage(builder: flatbuffers.Builder, statusMessage: uoffset) -> None: ...
def SpanV1AddAttributesJson(builder: flatbuffers.Builder, attributesJson: uoffset) -> None: ...
def SpanV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

