#!/usr/bin/env bun

const GENERATED_BROWSER_ASSET_BANNER =
  "// Generated by scripts/build-tinygarden-assets.ts from Android TinyGarden TypeScript browser sources. Do not edit.";

const rootUrl = new URL("..", import.meta.url);
const tinyGardenUrl = new URL("Android/src/app/src/main/assets/tinygarden/", rootUrl);
const sourceUrl = new URL("main.ts", tinyGardenUrl);
const outputUrl = new URL("main.js", tinyGardenUrl);
const transpiler = new Bun.Transpiler({
  loader: "ts",
  target: "browser",
});

const source = await Bun.file(sourceUrl).text();
const output = transpiler.transformSync(source, "ts").trimEnd();

await Bun.write(outputUrl, `${GENERATED_BROWSER_ASSET_BANNER}\n\n${output}\n`);
await Bun.write(
  Bun.stdout,
  `${JSON.stringify({
    built: 1,
    level: "info",
    message: "bao-edge.tinygarden-assets.built",
  })}\n`,
);
