from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.rag.v1.RagMatchStrategyV1 import RagMatchStrategyV1
from baohaus.rag.v1.RagSourceTypeV1 import RagSourceTypeV1

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RagChunkMatchV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RagChunkMatchV1: ...
  @classmethod
  def GetRootAsRagChunkMatchV1(cls, buf: bytes, offset: int) -> RagChunkMatchV1: ...
  @classmethod
  def RagChunkMatchV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SourceType(self) -> typing.Literal[RagSourceTypeV1.ASSET, RagSourceTypeV1.ANNOTATION, RagSourceTypeV1.DOCUMENT, RagSourceTypeV1.CONVERSATION, RagSourceTypeV1.NOTE, RagSourceTypeV1.MANUAL, RagSourceTypeV1.LIBRARY_DOC]: ...
  def SourceId(self) -> str | None: ...
  def ChunkIndex(self) -> int: ...
  def ChunkText(self) -> str | None: ...
  def Score(self) -> float: ...
  def Strategy(self) -> typing.Literal[RagMatchStrategyV1.VECTOR, RagMatchStrategyV1.KEYWORD, RagMatchStrategyV1.DETERMINISTIC, RagMatchStrategyV1.MCP]: ...
  def Distance(self) -> float: ...
  def Certainty(self) -> float: ...
  def ContentHash(self) -> str | None: ...
  def Chars(self) -> int: ...
  def Truncated(self) -> bool: ...
def RagChunkMatchV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RagChunkMatchV1AddSourceType(builder: flatbuffers.Builder, sourceType: typing.Literal[RagSourceTypeV1.ASSET, RagSourceTypeV1.ANNOTATION, RagSourceTypeV1.DOCUMENT, RagSourceTypeV1.CONVERSATION, RagSourceTypeV1.NOTE, RagSourceTypeV1.MANUAL, RagSourceTypeV1.LIBRARY_DOC]) -> None: ...
def RagChunkMatchV1AddSourceId(builder: flatbuffers.Builder, sourceId: uoffset) -> None: ...
def RagChunkMatchV1AddChunkIndex(builder: flatbuffers.Builder, chunkIndex: int) -> None: ...
def RagChunkMatchV1AddChunkText(builder: flatbuffers.Builder, chunkText: uoffset) -> None: ...
def RagChunkMatchV1AddScore(builder: flatbuffers.Builder, score: float) -> None: ...
def RagChunkMatchV1AddStrategy(builder: flatbuffers.Builder, strategy: typing.Literal[RagMatchStrategyV1.VECTOR, RagMatchStrategyV1.KEYWORD, RagMatchStrategyV1.DETERMINISTIC, RagMatchStrategyV1.MCP]) -> None: ...
def RagChunkMatchV1AddDistance(builder: flatbuffers.Builder, distance: float) -> None: ...
def RagChunkMatchV1AddCertainty(builder: flatbuffers.Builder, certainty: float) -> None: ...
def RagChunkMatchV1AddContentHash(builder: flatbuffers.Builder, contentHash: uoffset) -> None: ...
def RagChunkMatchV1AddChars(builder: flatbuffers.Builder, chars: int) -> None: ...
def RagChunkMatchV1AddTruncated(builder: flatbuffers.Builder, truncated: bool) -> None: ...
def RagChunkMatchV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

