# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

# A single retrieved chunk with match metadata.
class RagChunkMatchV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RagChunkMatchV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRagChunkMatchV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RagChunkMatchV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x52\x56\x31", size_prefixed=size_prefixed)

    # RagChunkMatchV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Source type of the matched chunk.
    # RagChunkMatchV1
    def SourceType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Source identifier.
    # RagChunkMatchV1
    def SourceId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Chunk index within the source document.
    # RagChunkMatchV1
    def ChunkIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # The chunk text content.
    # RagChunkMatchV1
    def ChunkText(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Match score (higher = better relevance).
    # RagChunkMatchV1
    def Score(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Strategy used to match this chunk.
    # RagChunkMatchV1
    def Strategy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Vector distance (when strategy = VECTOR).
    # RagChunkMatchV1
    def Distance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Vector certainty (when strategy = VECTOR).
    # RagChunkMatchV1
    def Certainty(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # SHA-256 hash of chunk content for deduplication.
    # RagChunkMatchV1
    def ContentHash(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Character count of the chunk.
    # RagChunkMatchV1
    def Chars(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Whether the chunk was truncated to fit within max_chars.
    # RagChunkMatchV1
    def Truncated(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def RagChunkMatchV1Start(builder: flatbuffers.Builder):
    builder.StartObject(11)

def Start(builder: flatbuffers.Builder):
    RagChunkMatchV1Start(builder)

def RagChunkMatchV1AddSourceType(builder: flatbuffers.Builder, sourceType: int):
    builder.PrependUint8Slot(0, sourceType, 0)

def AddSourceType(builder: flatbuffers.Builder, sourceType: int):
    RagChunkMatchV1AddSourceType(builder, sourceType)

def RagChunkMatchV1AddSourceId(builder: flatbuffers.Builder, sourceId: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(sourceId), 0)

def AddSourceId(builder: flatbuffers.Builder, sourceId: int):
    RagChunkMatchV1AddSourceId(builder, sourceId)

def RagChunkMatchV1AddChunkIndex(builder: flatbuffers.Builder, chunkIndex: int):
    builder.PrependUint32Slot(2, chunkIndex, 0)

def AddChunkIndex(builder: flatbuffers.Builder, chunkIndex: int):
    RagChunkMatchV1AddChunkIndex(builder, chunkIndex)

def RagChunkMatchV1AddChunkText(builder: flatbuffers.Builder, chunkText: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(chunkText), 0)

def AddChunkText(builder: flatbuffers.Builder, chunkText: int):
    RagChunkMatchV1AddChunkText(builder, chunkText)

def RagChunkMatchV1AddScore(builder: flatbuffers.Builder, score: float):
    builder.PrependFloat32Slot(4, score, 0.0)

def AddScore(builder: flatbuffers.Builder, score: float):
    RagChunkMatchV1AddScore(builder, score)

def RagChunkMatchV1AddStrategy(builder: flatbuffers.Builder, strategy: int):
    builder.PrependUint8Slot(5, strategy, 0)

def AddStrategy(builder: flatbuffers.Builder, strategy: int):
    RagChunkMatchV1AddStrategy(builder, strategy)

def RagChunkMatchV1AddDistance(builder: flatbuffers.Builder, distance: float):
    builder.PrependFloat32Slot(6, distance, 0.0)

def AddDistance(builder: flatbuffers.Builder, distance: float):
    RagChunkMatchV1AddDistance(builder, distance)

def RagChunkMatchV1AddCertainty(builder: flatbuffers.Builder, certainty: float):
    builder.PrependFloat32Slot(7, certainty, 0.0)

def AddCertainty(builder: flatbuffers.Builder, certainty: float):
    RagChunkMatchV1AddCertainty(builder, certainty)

def RagChunkMatchV1AddContentHash(builder: flatbuffers.Builder, contentHash: int):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(contentHash), 0)

def AddContentHash(builder: flatbuffers.Builder, contentHash: int):
    RagChunkMatchV1AddContentHash(builder, contentHash)

def RagChunkMatchV1AddChars(builder: flatbuffers.Builder, chars: int):
    builder.PrependUint32Slot(9, chars, 0)

def AddChars(builder: flatbuffers.Builder, chars: int):
    RagChunkMatchV1AddChars(builder, chars)

def RagChunkMatchV1AddTruncated(builder: flatbuffers.Builder, truncated: bool):
    builder.PrependBoolSlot(10, truncated, 0)

def AddTruncated(builder: flatbuffers.Builder, truncated: bool):
    RagChunkMatchV1AddTruncated(builder, truncated)

def RagChunkMatchV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return RagChunkMatchV1End(builder)
