# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

# Match strategy used to retrieve a chunk.
class RagMatchStrategyV1(object):
    VECTOR = 0
    KEYWORD = 1
    DETERMINISTIC = 2
    MCP = 3
