from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.rag.v1.RagSourceRefV1 import RagSourceRefV1

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RagRetrievalQueryV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RagRetrievalQueryV1: ...
  @classmethod
  def GetRootAsRagRetrievalQueryV1(cls, buf: bytes, offset: int) -> RagRetrievalQueryV1: ...
  @classmethod
  def RagRetrievalQueryV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def CorrelationId(self) -> str | None: ...
  def Sources(self, i: int) -> RagSourceRefV1 | None: ...
  def SourcesLength(self) -> int: ...
  def SourcesIsNone(self) -> bool: ...
  def QueryText(self) -> str | None: ...
  def MaxChars(self) -> int: ...
  def PreferVectorSearch(self) -> bool: ...
def RagRetrievalQueryV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RagRetrievalQueryV1AddCorrelationId(builder: flatbuffers.Builder, correlationId: uoffset) -> None: ...
def RagRetrievalQueryV1AddSources(builder: flatbuffers.Builder, sources: uoffset) -> None: ...
def RagRetrievalQueryV1StartSourcesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartSourcesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RagRetrievalQueryV1AddQueryText(builder: flatbuffers.Builder, queryText: uoffset) -> None: ...
def RagRetrievalQueryV1AddMaxChars(builder: flatbuffers.Builder, maxChars: int) -> None: ...
def RagRetrievalQueryV1AddPreferVectorSearch(builder: flatbuffers.Builder, preferVectorSearch: bool) -> None: ...
def RagRetrievalQueryV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

