from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.rag.v1.RagChunkMatchV1 import RagChunkMatchV1
from baohaus.rag.v1.RagSourceSummaryV1 import RagSourceSummaryV1

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RagRetrievalResponseV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RagRetrievalResponseV1: ...
  @classmethod
  def GetRootAsRagRetrievalResponseV1(cls, buf: bytes, offset: int) -> RagRetrievalResponseV1: ...
  @classmethod
  def RagRetrievalResponseV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Ok(self) -> bool: ...
  def Prompt(self) -> str | None: ...
  def Sources(self, i: int) -> RagSourceSummaryV1 | None: ...
  def SourcesLength(self) -> int: ...
  def SourcesIsNone(self) -> bool: ...
  def ChunksIncluded(self) -> int: ...
  def CharsIncluded(self) -> int: ...
  def Matches(self, i: int) -> RagChunkMatchV1 | None: ...
  def MatchesLength(self) -> int: ...
  def MatchesIsNone(self) -> bool: ...
  def Error(self) -> str | None: ...
def RagRetrievalResponseV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RagRetrievalResponseV1AddOk(builder: flatbuffers.Builder, ok: bool) -> None: ...
def RagRetrievalResponseV1AddPrompt(builder: flatbuffers.Builder, prompt: uoffset) -> None: ...
def RagRetrievalResponseV1AddSources(builder: flatbuffers.Builder, sources: uoffset) -> None: ...
def RagRetrievalResponseV1StartSourcesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartSourcesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RagRetrievalResponseV1AddChunksIncluded(builder: flatbuffers.Builder, chunksIncluded: int) -> None: ...
def RagRetrievalResponseV1AddCharsIncluded(builder: flatbuffers.Builder, charsIncluded: int) -> None: ...
def RagRetrievalResponseV1AddMatches(builder: flatbuffers.Builder, matches: uoffset) -> None: ...
def RagRetrievalResponseV1StartMatchesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartMatchesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RagRetrievalResponseV1AddError(builder: flatbuffers.Builder, error: uoffset) -> None: ...
def RagRetrievalResponseV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

