# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
from baohaus.rag.v1.RagChunkMatchV1 import RagChunkMatchV1
from baohaus.rag.v1.RagSourceSummaryV1 import RagSourceSummaryV1
np = import_numpy()

# RAG retrieval response.
class RagRetrievalResponseV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RagRetrievalResponseV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRagRetrievalResponseV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RagRetrievalResponseV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x52\x56\x31", size_prefixed=size_prefixed)

    # RagRetrievalResponseV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Whether retrieval was successful.
    # RagRetrievalResponseV1
    def Ok(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Assembled prompt text from retrieved chunks.
    # RagRetrievalResponseV1
    def Prompt(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Per-source summary of included chunks.
    # RagRetrievalResponseV1
    def Sources(self, j: int) -> Optional[RagSourceSummaryV1]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = RagSourceSummaryV1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RagRetrievalResponseV1
    def SourcesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RagRetrievalResponseV1
    def SourcesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Total chunks included in the prompt.
    # RagRetrievalResponseV1
    def ChunksIncluded(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Total characters included in the prompt.
    # RagRetrievalResponseV1
    def CharsIncluded(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Detailed match metadata for each included chunk.
    # RagRetrievalResponseV1
    def Matches(self, j: int) -> Optional[RagChunkMatchV1]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = RagChunkMatchV1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RagRetrievalResponseV1
    def MatchesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RagRetrievalResponseV1
    def MatchesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # Error message when ok = false.
    # RagRetrievalResponseV1
    def Error(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def RagRetrievalResponseV1Start(builder: flatbuffers.Builder):
    builder.StartObject(7)

def Start(builder: flatbuffers.Builder):
    RagRetrievalResponseV1Start(builder)

def RagRetrievalResponseV1AddOk(builder: flatbuffers.Builder, ok: bool):
    builder.PrependBoolSlot(0, ok, 0)

def AddOk(builder: flatbuffers.Builder, ok: bool):
    RagRetrievalResponseV1AddOk(builder, ok)

def RagRetrievalResponseV1AddPrompt(builder: flatbuffers.Builder, prompt: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(prompt), 0)

def AddPrompt(builder: flatbuffers.Builder, prompt: int):
    RagRetrievalResponseV1AddPrompt(builder, prompt)

def RagRetrievalResponseV1AddSources(builder: flatbuffers.Builder, sources: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(sources), 0)

def AddSources(builder: flatbuffers.Builder, sources: int):
    RagRetrievalResponseV1AddSources(builder, sources)

def RagRetrievalResponseV1StartSourcesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartSourcesVector(builder, numElems: int) -> int:
    return RagRetrievalResponseV1StartSourcesVector(builder, numElems)

def RagRetrievalResponseV1AddChunksIncluded(builder: flatbuffers.Builder, chunksIncluded: int):
    builder.PrependUint16Slot(3, chunksIncluded, 0)

def AddChunksIncluded(builder: flatbuffers.Builder, chunksIncluded: int):
    RagRetrievalResponseV1AddChunksIncluded(builder, chunksIncluded)

def RagRetrievalResponseV1AddCharsIncluded(builder: flatbuffers.Builder, charsIncluded: int):
    builder.PrependUint32Slot(4, charsIncluded, 0)

def AddCharsIncluded(builder: flatbuffers.Builder, charsIncluded: int):
    RagRetrievalResponseV1AddCharsIncluded(builder, charsIncluded)

def RagRetrievalResponseV1AddMatches(builder: flatbuffers.Builder, matches: int):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(matches), 0)

def AddMatches(builder: flatbuffers.Builder, matches: int):
    RagRetrievalResponseV1AddMatches(builder, matches)

def RagRetrievalResponseV1StartMatchesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartMatchesVector(builder, numElems: int) -> int:
    return RagRetrievalResponseV1StartMatchesVector(builder, numElems)

def RagRetrievalResponseV1AddError(builder: flatbuffers.Builder, error: int):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)

def AddError(builder: flatbuffers.Builder, error: int):
    RagRetrievalResponseV1AddError(builder, error)

def RagRetrievalResponseV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return RagRetrievalResponseV1End(builder)
