# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

# Embedding source type enum matching @shared/types/rag.
class RagSourceTypeV1(object):
    ASSET = 0
    ANNOTATION = 1
    DOCUMENT = 2
    CONVERSATION = 3
    NOTE = 4
    MANUAL = 5
    LIBRARY_DOC = 6
