# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

# Per-source retrieval summary.
class RagSourceSummaryV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RagSourceSummaryV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRagSourceSummaryV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RagSourceSummaryV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x52\x56\x31", size_prefixed=size_prefixed)

    # RagSourceSummaryV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RagSourceSummaryV1
    def SourceType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # RagSourceSummaryV1
    def SourceId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RagSourceSummaryV1
    def ChunksIncluded(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def RagSourceSummaryV1Start(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    RagSourceSummaryV1Start(builder)

def RagSourceSummaryV1AddSourceType(builder: flatbuffers.Builder, sourceType: int):
    builder.PrependUint8Slot(0, sourceType, 0)

def AddSourceType(builder: flatbuffers.Builder, sourceType: int):
    RagSourceSummaryV1AddSourceType(builder, sourceType)

def RagSourceSummaryV1AddSourceId(builder: flatbuffers.Builder, sourceId: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(sourceId), 0)

def AddSourceId(builder: flatbuffers.Builder, sourceId: int):
    RagSourceSummaryV1AddSourceId(builder, sourceId)

def RagSourceSummaryV1AddChunksIncluded(builder: flatbuffers.Builder, chunksIncluded: int):
    builder.PrependUint16Slot(2, chunksIncluded, 0)

def AddChunksIncluded(builder: flatbuffers.Builder, chunksIncluded: int):
    RagSourceSummaryV1AddChunksIncluded(builder, chunksIncluded)

def RagSourceSummaryV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return RagSourceSummaryV1End(builder)
