from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.rag.v1.RagSourceTypeV1 import RagSourceTypeV1

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RagSourceSummaryV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RagSourceSummaryV1: ...
  @classmethod
  def GetRootAsRagSourceSummaryV1(cls, buf: bytes, offset: int) -> RagSourceSummaryV1: ...
  @classmethod
  def RagSourceSummaryV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SourceType(self) -> typing.Literal[RagSourceTypeV1.ASSET, RagSourceTypeV1.ANNOTATION, RagSourceTypeV1.DOCUMENT, RagSourceTypeV1.CONVERSATION, RagSourceTypeV1.NOTE, RagSourceTypeV1.MANUAL, RagSourceTypeV1.LIBRARY_DOC]: ...
  def SourceId(self) -> str | None: ...
  def ChunksIncluded(self) -> int: ...
def RagSourceSummaryV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RagSourceSummaryV1AddSourceType(builder: flatbuffers.Builder, sourceType: typing.Literal[RagSourceTypeV1.ASSET, RagSourceTypeV1.ANNOTATION, RagSourceTypeV1.DOCUMENT, RagSourceTypeV1.CONVERSATION, RagSourceTypeV1.NOTE, RagSourceTypeV1.MANUAL, RagSourceTypeV1.LIBRARY_DOC]) -> None: ...
def RagSourceSummaryV1AddSourceId(builder: flatbuffers.Builder, sourceId: uoffset) -> None: ...
def RagSourceSummaryV1AddChunksIncluded(builder: flatbuffers.Builder, chunksIncluded: int) -> None: ...
def RagSourceSummaryV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

