# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

# A source reference for retrieval queries.
class RagSourceRefV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RagSourceRefV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRagSourceRefV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RagSourceRefV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x52\x56\x31", size_prefixed=size_prefixed)

    # RagSourceRefV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RagSourceRefV1
    def SourceType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # RagSourceRefV1
    def SourceId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RagSourceRefV1
    def MaxChunks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 10

def RagSourceRefV1Start(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    RagSourceRefV1Start(builder)

def RagSourceRefV1AddSourceType(builder: flatbuffers.Builder, sourceType: int):
    builder.PrependUint8Slot(0, sourceType, 0)

def AddSourceType(builder: flatbuffers.Builder, sourceType: int):
    RagSourceRefV1AddSourceType(builder, sourceType)

def RagSourceRefV1AddSourceId(builder: flatbuffers.Builder, sourceId: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(sourceId), 0)

def AddSourceId(builder: flatbuffers.Builder, sourceId: int):
    RagSourceRefV1AddSourceId(builder, sourceId)

def RagSourceRefV1AddMaxChunks(builder: flatbuffers.Builder, maxChunks: int):
    builder.PrependUint16Slot(2, maxChunks, 10)

def AddMaxChunks(builder: flatbuffers.Builder, maxChunks: int):
    RagSourceRefV1AddMaxChunks(builder, maxChunks)

def RagSourceRefV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return RagSourceRefV1End(builder)
