from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.rag.v1.RagSourceTypeV1 import RagSourceTypeV1

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RagSourceRefV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RagSourceRefV1: ...
  @classmethod
  def GetRootAsRagSourceRefV1(cls, buf: bytes, offset: int) -> RagSourceRefV1: ...
  @classmethod
  def RagSourceRefV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SourceType(self) -> typing.Literal[RagSourceTypeV1.ASSET, RagSourceTypeV1.ANNOTATION, RagSourceTypeV1.DOCUMENT, RagSourceTypeV1.CONVERSATION, RagSourceTypeV1.NOTE, RagSourceTypeV1.MANUAL, RagSourceTypeV1.LIBRARY_DOC]: ...
  def SourceId(self) -> str | None: ...
  def MaxChunks(self) -> int: ...
def RagSourceRefV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RagSourceRefV1AddSourceType(builder: flatbuffers.Builder, sourceType: typing.Literal[RagSourceTypeV1.ASSET, RagSourceTypeV1.ANNOTATION, RagSourceTypeV1.DOCUMENT, RagSourceTypeV1.CONVERSATION, RagSourceTypeV1.NOTE, RagSourceTypeV1.MANUAL, RagSourceTypeV1.LIBRARY_DOC]) -> None: ...
def RagSourceRefV1AddSourceId(builder: flatbuffers.Builder, sourceId: uoffset) -> None: ...
def RagSourceRefV1AddMaxChunks(builder: flatbuffers.Builder, maxChunks: int) -> None: ...
def RagSourceRefV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

