# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from flatbuffers.table import Table
from typing import Optional
np = import_numpy()

class BaoDownRunEventV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BaoDownRunEventV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBaoDownRunEventV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BaoDownRunEventV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x42\x52\x45\x31", size_prefixed=size_prefixed)

    # BaoDownRunEventV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BaoDownRunEventV1
    def RunId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoDownRunEventV1
    def Seq(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # BaoDownRunEventV1
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # BaoDownRunEventV1
    def Timestamp(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoDownRunEventV1
    def NodeId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoDownRunEventV1
    def PayloadType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # BaoDownRunEventV1
    def Payload(self) -> Optional[flatbuffers.table.Table]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def BaoDownRunEventV1Start(builder: flatbuffers.Builder):
    builder.StartObject(7)

def Start(builder: flatbuffers.Builder):
    BaoDownRunEventV1Start(builder)

def BaoDownRunEventV1AddRunId(builder: flatbuffers.Builder, runId: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(runId), 0)

def AddRunId(builder: flatbuffers.Builder, runId: int):
    BaoDownRunEventV1AddRunId(builder, runId)

def BaoDownRunEventV1AddSeq(builder: flatbuffers.Builder, seq: int):
    builder.PrependUint32Slot(1, seq, 0)

def AddSeq(builder: flatbuffers.Builder, seq: int):
    BaoDownRunEventV1AddSeq(builder, seq)

def BaoDownRunEventV1AddKind(builder: flatbuffers.Builder, kind: int):
    builder.PrependUint8Slot(2, kind, 0)

def AddKind(builder: flatbuffers.Builder, kind: int):
    BaoDownRunEventV1AddKind(builder, kind)

def BaoDownRunEventV1AddTimestamp(builder: flatbuffers.Builder, timestamp: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder: flatbuffers.Builder, timestamp: int):
    BaoDownRunEventV1AddTimestamp(builder, timestamp)

def BaoDownRunEventV1AddNodeId(builder: flatbuffers.Builder, nodeId: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(nodeId), 0)

def AddNodeId(builder: flatbuffers.Builder, nodeId: int):
    BaoDownRunEventV1AddNodeId(builder, nodeId)

def BaoDownRunEventV1AddPayloadType(builder: flatbuffers.Builder, payloadType: int):
    builder.PrependUint8Slot(5, payloadType, 0)

def AddPayloadType(builder: flatbuffers.Builder, payloadType: int):
    BaoDownRunEventV1AddPayloadType(builder, payloadType)

def BaoDownRunEventV1AddPayload(builder: flatbuffers.Builder, payload: int):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)

def AddPayload(builder: flatbuffers.Builder, payload: int):
    BaoDownRunEventV1AddPayload(builder, payload)

def BaoDownRunEventV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return BaoDownRunEventV1End(builder)
