# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class BaoDownRunEventKindV1(object):
    RUN_STARTED = 0
    RUN_COMPLETED = 1
    RUN_FAILED = 2
    RUN_CANCELLED = 3
    NODE_STARTED = 4
    NODE_COMPLETED = 5
    NODE_FAILED = 6
    NODE_LOG = 7
