# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class BaoDownPayloadUnion(object):
    NONE = 0
    LogPayload = 1
    NodeOutputPayload = 2
    RunMetadataPayload = 3
