from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from flatbuffers import table
from baohaus.baodown.v1.BaoDownPayloadUnion import BaoDownPayloadUnion
from baohaus.baodown.v1.BaoDownRunEventKindV1 import BaoDownRunEventKindV1

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class BaoDownRunEventV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> BaoDownRunEventV1: ...
  @classmethod
  def GetRootAsBaoDownRunEventV1(cls, buf: bytes, offset: int) -> BaoDownRunEventV1: ...
  @classmethod
  def BaoDownRunEventV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def RunId(self) -> str | None: ...
  def Seq(self) -> int: ...
  def Kind(self) -> typing.Literal[BaoDownRunEventKindV1.RUN_STARTED, BaoDownRunEventKindV1.RUN_COMPLETED, BaoDownRunEventKindV1.RUN_FAILED, BaoDownRunEventKindV1.RUN_CANCELLED, BaoDownRunEventKindV1.NODE_STARTED, BaoDownRunEventKindV1.NODE_COMPLETED, BaoDownRunEventKindV1.NODE_FAILED, BaoDownRunEventKindV1.NODE_LOG]: ...
  def Timestamp(self) -> str | None: ...
  def NodeId(self) -> str | None: ...
  def PayloadType(self) -> typing.Literal[BaoDownPayloadUnion.NONE, BaoDownPayloadUnion.LogPayload, BaoDownPayloadUnion.NodeOutputPayload, BaoDownPayloadUnion.RunMetadataPayload]: ...
  def Payload(self) -> table.Table | None: ...
def BaoDownRunEventV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def BaoDownRunEventV1AddRunId(builder: flatbuffers.Builder, runId: uoffset) -> None: ...
def BaoDownRunEventV1AddSeq(builder: flatbuffers.Builder, seq: int) -> None: ...
def BaoDownRunEventV1AddKind(builder: flatbuffers.Builder, kind: typing.Literal[BaoDownRunEventKindV1.RUN_STARTED, BaoDownRunEventKindV1.RUN_COMPLETED, BaoDownRunEventKindV1.RUN_FAILED, BaoDownRunEventKindV1.RUN_CANCELLED, BaoDownRunEventKindV1.NODE_STARTED, BaoDownRunEventKindV1.NODE_COMPLETED, BaoDownRunEventKindV1.NODE_FAILED, BaoDownRunEventKindV1.NODE_LOG]) -> None: ...
def BaoDownRunEventV1AddTimestamp(builder: flatbuffers.Builder, timestamp: uoffset) -> None: ...
def BaoDownRunEventV1AddNodeId(builder: flatbuffers.Builder, nodeId: uoffset) -> None: ...
def BaoDownRunEventV1AddPayloadType(builder: flatbuffers.Builder, payloadType: typing.Literal[BaoDownPayloadUnion.NONE, BaoDownPayloadUnion.LogPayload, BaoDownPayloadUnion.NodeOutputPayload, BaoDownPayloadUnion.RunMetadataPayload]) -> None: ...
def BaoDownRunEventV1AddPayload(builder: flatbuffers.Builder, payload: uoffset) -> None: ...
def BaoDownRunEventV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

