from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class LogPayload(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> LogPayload: ...
  @classmethod
  def GetRootAsLogPayload(cls, buf: bytes, offset: int) -> LogPayload: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Level(self) -> str | None: ...
  def Message(self) -> str | None: ...
def LogPayloadStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def LogPayloadAddLevel(builder: flatbuffers.Builder, level: uoffset) -> None: ...
def LogPayloadAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def LogPayloadEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

