# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

# Node output for NODE_COMPLETED events.
class NodeOutputPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NodeOutputPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNodeOutputPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # NodeOutputPayload
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NodeOutputPayload
    def OutputJson(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def NodeOutputPayloadStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    NodeOutputPayloadStart(builder)

def NodeOutputPayloadAddOutputJson(builder: flatbuffers.Builder, outputJson: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(outputJson), 0)

def AddOutputJson(builder: flatbuffers.Builder, outputJson: int):
    NodeOutputPayloadAddOutputJson(builder, outputJson)

def NodeOutputPayloadEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return NodeOutputPayloadEnd(builder)
