from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class NodeOutputPayload(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> NodeOutputPayload: ...
  @classmethod
  def GetRootAsNodeOutputPayload(cls, buf: bytes, offset: int) -> NodeOutputPayload: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def OutputJson(self) -> str | None: ...
def NodeOutputPayloadStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def NodeOutputPayloadAddOutputJson(builder: flatbuffers.Builder, outputJson: uoffset) -> None: ...
def NodeOutputPayloadEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

