# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

# Run-level metadata for RUN_STARTED, RUN_COMPLETED, RUN_FAILED, RUN_CANCELLED.
class RunMetadataPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RunMetadataPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRunMetadataPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RunMetadataPayload
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RunMetadataPayload
    def Code(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunMetadataPayload
    def Message(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunMetadataPayload
    def DetailsJson(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def RunMetadataPayloadStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    RunMetadataPayloadStart(builder)

def RunMetadataPayloadAddCode(builder: flatbuffers.Builder, code: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(code), 0)

def AddCode(builder: flatbuffers.Builder, code: int):
    RunMetadataPayloadAddCode(builder, code)

def RunMetadataPayloadAddMessage(builder: flatbuffers.Builder, message: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder: flatbuffers.Builder, message: int):
    RunMetadataPayloadAddMessage(builder, message)

def RunMetadataPayloadAddDetailsJson(builder: flatbuffers.Builder, detailsJson: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(detailsJson), 0)

def AddDetailsJson(builder: flatbuffers.Builder, detailsJson: int):
    RunMetadataPayloadAddDetailsJson(builder, detailsJson)

def RunMetadataPayloadEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return RunMetadataPayloadEnd(builder)
