from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RunMetadataPayload(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RunMetadataPayload: ...
  @classmethod
  def GetRootAsRunMetadataPayload(cls, buf: bytes, offset: int) -> RunMetadataPayload: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Code(self) -> str | None: ...
  def Message(self) -> str | None: ...
  def DetailsJson(self) -> str | None: ...
def RunMetadataPayloadStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RunMetadataPayloadAddCode(builder: flatbuffers.Builder, code: uoffset) -> None: ...
def RunMetadataPayloadAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def RunMetadataPayloadAddDetailsJson(builder: flatbuffers.Builder, detailsJson: uoffset) -> None: ...
def RunMetadataPayloadEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

