from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.baoinstall.v1.DependencyEdgeV1 import DependencyEdgeV1
from baohaus.baoinstall.v1.DependencyNodeV1 import DependencyNodeV1

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class BaoDependencyGraphV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> BaoDependencyGraphV1: ...
  @classmethod
  def GetRootAsBaoDependencyGraphV1(cls, buf: bytes, offset: int) -> BaoDependencyGraphV1: ...
  @classmethod
  def BaoDependencyGraphV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def ManifestName(self) -> str | None: ...
  def ManifestVersion(self) -> str | None: ...
  def Nodes(self, i: int) -> DependencyNodeV1 | None: ...
  def NodesLength(self) -> int: ...
  def NodesIsNone(self) -> bool: ...
  def Edges(self, i: int) -> DependencyEdgeV1 | None: ...
  def EdgesLength(self) -> int: ...
  def EdgesIsNone(self) -> bool: ...
  def TotalNodes(self) -> int: ...
  def ResolvedNodes(self) -> int: ...
  def ErrorNodes(self) -> int: ...
  def FullyResolved(self) -> bool: ...
  def TotalEstimatedDurationMs(self) -> int: ...
  def CorrelationId(self) -> str | None: ...
  def ErrorSummary(self) -> str | None: ...
def BaoDependencyGraphV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def BaoDependencyGraphV1AddManifestName(builder: flatbuffers.Builder, manifestName: uoffset) -> None: ...
def BaoDependencyGraphV1AddManifestVersion(builder: flatbuffers.Builder, manifestVersion: uoffset) -> None: ...
def BaoDependencyGraphV1AddNodes(builder: flatbuffers.Builder, nodes: uoffset) -> None: ...
def BaoDependencyGraphV1StartNodesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartNodesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def BaoDependencyGraphV1AddEdges(builder: flatbuffers.Builder, edges: uoffset) -> None: ...
def BaoDependencyGraphV1StartEdgesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartEdgesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def BaoDependencyGraphV1AddTotalNodes(builder: flatbuffers.Builder, totalNodes: int) -> None: ...
def BaoDependencyGraphV1AddResolvedNodes(builder: flatbuffers.Builder, resolvedNodes: int) -> None: ...
def BaoDependencyGraphV1AddErrorNodes(builder: flatbuffers.Builder, errorNodes: int) -> None: ...
def BaoDependencyGraphV1AddFullyResolved(builder: flatbuffers.Builder, fullyResolved: bool) -> None: ...
def BaoDependencyGraphV1AddTotalEstimatedDurationMs(builder: flatbuffers.Builder, totalEstimatedDurationMs: int) -> None: ...
def BaoDependencyGraphV1AddCorrelationId(builder: flatbuffers.Builder, correlationId: uoffset) -> None: ...
def BaoDependencyGraphV1AddErrorSummary(builder: flatbuffers.Builder, errorSummary: uoffset) -> None: ...
def BaoDependencyGraphV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

