# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
from baohaus.baoinstall.v1.DependencyEdgeV1 import DependencyEdgeV1
from baohaus.baoinstall.v1.DependencyNodeV1 import DependencyNodeV1
np = import_numpy()

# Complete dependency graph for a .bao manifest install plan.
class BaoDependencyGraphV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BaoDependencyGraphV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBaoDependencyGraphV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BaoDependencyGraphV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x42\x44\x47\x31", size_prefixed=size_prefixed)

    # BaoDependencyGraphV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Manifest name being resolved.
    # BaoDependencyGraphV1
    def ManifestName(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Manifest version.
    # BaoDependencyGraphV1
    def ManifestVersion(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # All dependency nodes.
    # BaoDependencyGraphV1
    def Nodes(self, j: int) -> Optional[DependencyNodeV1]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = DependencyNodeV1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BaoDependencyGraphV1
    def NodesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BaoDependencyGraphV1
    def NodesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # All dependency edges (DAG relationships).
    # BaoDependencyGraphV1
    def Edges(self, j: int) -> Optional[DependencyEdgeV1]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = DependencyEdgeV1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BaoDependencyGraphV1
    def EdgesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BaoDependencyGraphV1
    def EdgesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Total node count.
    # BaoDependencyGraphV1
    def TotalNodes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Number of resolved nodes.
    # BaoDependencyGraphV1
    def ResolvedNodes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Number of conflict/missing/circular nodes.
    # BaoDependencyGraphV1
    def ErrorNodes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Whether the entire graph is fully resolved.
    # BaoDependencyGraphV1
    def FullyResolved(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Total estimated install duration in milliseconds.
    # BaoDependencyGraphV1
    def TotalEstimatedDurationMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Graph resolution correlation ID.
    # BaoDependencyGraphV1
    def CorrelationId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Error summary when not fully resolved.
    # BaoDependencyGraphV1
    def ErrorSummary(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def BaoDependencyGraphV1Start(builder: flatbuffers.Builder):
    builder.StartObject(11)

def Start(builder: flatbuffers.Builder):
    BaoDependencyGraphV1Start(builder)

def BaoDependencyGraphV1AddManifestName(builder: flatbuffers.Builder, manifestName: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(manifestName), 0)

def AddManifestName(builder: flatbuffers.Builder, manifestName: int):
    BaoDependencyGraphV1AddManifestName(builder, manifestName)

def BaoDependencyGraphV1AddManifestVersion(builder: flatbuffers.Builder, manifestVersion: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(manifestVersion), 0)

def AddManifestVersion(builder: flatbuffers.Builder, manifestVersion: int):
    BaoDependencyGraphV1AddManifestVersion(builder, manifestVersion)

def BaoDependencyGraphV1AddNodes(builder: flatbuffers.Builder, nodes: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(nodes), 0)

def AddNodes(builder: flatbuffers.Builder, nodes: int):
    BaoDependencyGraphV1AddNodes(builder, nodes)

def BaoDependencyGraphV1StartNodesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartNodesVector(builder, numElems: int) -> int:
    return BaoDependencyGraphV1StartNodesVector(builder, numElems)

def BaoDependencyGraphV1AddEdges(builder: flatbuffers.Builder, edges: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(edges), 0)

def AddEdges(builder: flatbuffers.Builder, edges: int):
    BaoDependencyGraphV1AddEdges(builder, edges)

def BaoDependencyGraphV1StartEdgesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartEdgesVector(builder, numElems: int) -> int:
    return BaoDependencyGraphV1StartEdgesVector(builder, numElems)

def BaoDependencyGraphV1AddTotalNodes(builder: flatbuffers.Builder, totalNodes: int):
    builder.PrependUint16Slot(4, totalNodes, 0)

def AddTotalNodes(builder: flatbuffers.Builder, totalNodes: int):
    BaoDependencyGraphV1AddTotalNodes(builder, totalNodes)

def BaoDependencyGraphV1AddResolvedNodes(builder: flatbuffers.Builder, resolvedNodes: int):
    builder.PrependUint16Slot(5, resolvedNodes, 0)

def AddResolvedNodes(builder: flatbuffers.Builder, resolvedNodes: int):
    BaoDependencyGraphV1AddResolvedNodes(builder, resolvedNodes)

def BaoDependencyGraphV1AddErrorNodes(builder: flatbuffers.Builder, errorNodes: int):
    builder.PrependUint16Slot(6, errorNodes, 0)

def AddErrorNodes(builder: flatbuffers.Builder, errorNodes: int):
    BaoDependencyGraphV1AddErrorNodes(builder, errorNodes)

def BaoDependencyGraphV1AddFullyResolved(builder: flatbuffers.Builder, fullyResolved: bool):
    builder.PrependBoolSlot(7, fullyResolved, 0)

def AddFullyResolved(builder: flatbuffers.Builder, fullyResolved: bool):
    BaoDependencyGraphV1AddFullyResolved(builder, fullyResolved)

def BaoDependencyGraphV1AddTotalEstimatedDurationMs(builder: flatbuffers.Builder, totalEstimatedDurationMs: int):
    builder.PrependUint32Slot(8, totalEstimatedDurationMs, 0)

def AddTotalEstimatedDurationMs(builder: flatbuffers.Builder, totalEstimatedDurationMs: int):
    BaoDependencyGraphV1AddTotalEstimatedDurationMs(builder, totalEstimatedDurationMs)

def BaoDependencyGraphV1AddCorrelationId(builder: flatbuffers.Builder, correlationId: int):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(correlationId), 0)

def AddCorrelationId(builder: flatbuffers.Builder, correlationId: int):
    BaoDependencyGraphV1AddCorrelationId(builder, correlationId)

def BaoDependencyGraphV1AddErrorSummary(builder: flatbuffers.Builder, errorSummary: int):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(errorSummary), 0)

def AddErrorSummary(builder: flatbuffers.Builder, errorSummary: int):
    BaoDependencyGraphV1AddErrorSummary(builder, errorSummary)

def BaoDependencyGraphV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return BaoDependencyGraphV1End(builder)
