# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

# Single hardware requirement declaration for a .bao manifest.
class BaoHardwareRequirementV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BaoHardwareRequirementV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBaoHardwareRequirementV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BaoHardwareRequirementV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x42\x49\x4D\x31", size_prefixed=size_prefixed)

    # BaoHardwareRequirementV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BaoHardwareRequirementV1
    def DeviceKind(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoHardwareRequirementV1
    def VendorId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoHardwareRequirementV1
    def ProductId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoHardwareRequirementV1
    def MinMemoryMb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # BaoHardwareRequirementV1
    def Driver(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoHardwareRequirementV1
    def Optional(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def BaoHardwareRequirementV1Start(builder: flatbuffers.Builder):
    builder.StartObject(6)

def Start(builder: flatbuffers.Builder):
    BaoHardwareRequirementV1Start(builder)

def BaoHardwareRequirementV1AddDeviceKind(builder: flatbuffers.Builder, deviceKind: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(deviceKind), 0)

def AddDeviceKind(builder: flatbuffers.Builder, deviceKind: int):
    BaoHardwareRequirementV1AddDeviceKind(builder, deviceKind)

def BaoHardwareRequirementV1AddVendorId(builder: flatbuffers.Builder, vendorId: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(vendorId), 0)

def AddVendorId(builder: flatbuffers.Builder, vendorId: int):
    BaoHardwareRequirementV1AddVendorId(builder, vendorId)

def BaoHardwareRequirementV1AddProductId(builder: flatbuffers.Builder, productId: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(productId), 0)

def AddProductId(builder: flatbuffers.Builder, productId: int):
    BaoHardwareRequirementV1AddProductId(builder, productId)

def BaoHardwareRequirementV1AddMinMemoryMb(builder: flatbuffers.Builder, minMemoryMb: int):
    builder.PrependUint32Slot(3, minMemoryMb, 0)

def AddMinMemoryMb(builder: flatbuffers.Builder, minMemoryMb: int):
    BaoHardwareRequirementV1AddMinMemoryMb(builder, minMemoryMb)

def BaoHardwareRequirementV1AddDriver(builder: flatbuffers.Builder, driver: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(driver), 0)

def AddDriver(builder: flatbuffers.Builder, driver: int):
    BaoHardwareRequirementV1AddDriver(builder, driver)

def BaoHardwareRequirementV1AddOptional(builder: flatbuffers.Builder, optional: bool):
    builder.PrependBoolSlot(5, optional, 0)

def AddOptional(builder: flatbuffers.Builder, optional: bool):
    BaoHardwareRequirementV1AddOptional(builder, optional)

def BaoHardwareRequirementV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return BaoHardwareRequirementV1End(builder)
