from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class BaoHardwareRequirementV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> BaoHardwareRequirementV1: ...
  @classmethod
  def GetRootAsBaoHardwareRequirementV1(cls, buf: bytes, offset: int) -> BaoHardwareRequirementV1: ...
  @classmethod
  def BaoHardwareRequirementV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def DeviceKind(self) -> str | None: ...
  def VendorId(self) -> str | None: ...
  def ProductId(self) -> str | None: ...
  def MinMemoryMb(self) -> int: ...
  def Driver(self) -> str | None: ...
  def Optional(self) -> bool: ...
def BaoHardwareRequirementV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def BaoHardwareRequirementV1AddDeviceKind(builder: flatbuffers.Builder, deviceKind: uoffset) -> None: ...
def BaoHardwareRequirementV1AddVendorId(builder: flatbuffers.Builder, vendorId: uoffset) -> None: ...
def BaoHardwareRequirementV1AddProductId(builder: flatbuffers.Builder, productId: uoffset) -> None: ...
def BaoHardwareRequirementV1AddMinMemoryMb(builder: flatbuffers.Builder, minMemoryMb: int) -> None: ...
def BaoHardwareRequirementV1AddDriver(builder: flatbuffers.Builder, driver: uoffset) -> None: ...
def BaoHardwareRequirementV1AddOptional(builder: flatbuffers.Builder, optional: bool) -> None: ...
def BaoHardwareRequirementV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

