from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.baoinstall.v1.BaoHardwareRequirementV1 import BaoHardwareRequirementV1
from baohaus.baoinstall.v1.BaoInstallTargetV1 import BaoInstallTargetV1
from baohaus.baoinstall.v1.BaoLifecycleHooksV1 import BaoLifecycleHooksV1
from baohaus.baoinstall.v1.BaoPermissionV1 import BaoPermissionV1

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class BaoInstallManifestV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> BaoInstallManifestV1: ...
  @classmethod
  def GetRootAsBaoInstallManifestV1(cls, buf: bytes, offset: int) -> BaoInstallManifestV1: ...
  @classmethod
  def BaoInstallManifestV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Name(self) -> str | None: ...
  def Version(self) -> str | None: ...
  def Description(self) -> str | None: ...
  def Targets(self, i: int) -> BaoInstallTargetV1 | None: ...
  def TargetsLength(self) -> int: ...
  def TargetsIsNone(self) -> bool: ...
  def MetadataJson(self) -> str | None: ...
  def CreatedAt(self) -> str | None: ...
  def Hardware(self, i: int) -> BaoHardwareRequirementV1 | None: ...
  def HardwareLength(self) -> int: ...
  def HardwareIsNone(self) -> bool: ...
  def RuntimeConstraints(self, i: int) -> str: ...
  def RuntimeConstraintsLength(self) -> int: ...
  def RuntimeConstraintsIsNone(self) -> bool: ...
  def Permissions(self, i: int) -> BaoPermissionV1 | None: ...
  def PermissionsLength(self) -> int: ...
  def PermissionsIsNone(self) -> bool: ...
  def Hooks(self) -> BaoLifecycleHooksV1 | None: ...
  def ChecksumSha256(self) -> str | None: ...
  def Signature(self) -> str | None: ...
def BaoInstallManifestV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def BaoInstallManifestV1AddName(builder: flatbuffers.Builder, name: uoffset) -> None: ...
def BaoInstallManifestV1AddVersion(builder: flatbuffers.Builder, version: uoffset) -> None: ...
def BaoInstallManifestV1AddDescription(builder: flatbuffers.Builder, description: uoffset) -> None: ...
def BaoInstallManifestV1AddTargets(builder: flatbuffers.Builder, targets: uoffset) -> None: ...
def BaoInstallManifestV1StartTargetsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartTargetsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def BaoInstallManifestV1AddMetadataJson(builder: flatbuffers.Builder, metadataJson: uoffset) -> None: ...
def BaoInstallManifestV1AddCreatedAt(builder: flatbuffers.Builder, createdAt: uoffset) -> None: ...
def BaoInstallManifestV1AddHardware(builder: flatbuffers.Builder, hardware: uoffset) -> None: ...
def BaoInstallManifestV1StartHardwareVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartHardwareVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def BaoInstallManifestV1AddRuntimeConstraints(builder: flatbuffers.Builder, runtimeConstraints: uoffset) -> None: ...
def BaoInstallManifestV1StartRuntimeConstraintsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartRuntimeConstraintsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def BaoInstallManifestV1AddPermissions(builder: flatbuffers.Builder, permissions: uoffset) -> None: ...
def BaoInstallManifestV1StartPermissionsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartPermissionsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def BaoInstallManifestV1AddHooks(builder: flatbuffers.Builder, hooks: uoffset) -> None: ...
def BaoInstallManifestV1AddChecksumSha256(builder: flatbuffers.Builder, checksumSha256: uoffset) -> None: ...
def BaoInstallManifestV1AddSignature(builder: flatbuffers.Builder, signature: uoffset) -> None: ...
def BaoInstallManifestV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

