# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
from baohaus.baoinstall.v1.BaoHardwareRequirementV1 import BaoHardwareRequirementV1
from baohaus.baoinstall.v1.BaoInstallTargetV1 import BaoInstallTargetV1
from baohaus.baoinstall.v1.BaoLifecycleHooksV1 import BaoLifecycleHooksV1
from baohaus.baoinstall.v1.BaoPermissionV1 import BaoPermissionV1
np = import_numpy()

# Binary-encoded .bao install manifest (v1 schema).
class BaoInstallManifestV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BaoInstallManifestV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBaoInstallManifestV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BaoInstallManifestV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x42\x49\x4D\x31", size_prefixed=size_prefixed)

    # BaoInstallManifestV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BaoInstallManifestV1
    def Name(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoInstallManifestV1
    def Version(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoInstallManifestV1
    def Description(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoInstallManifestV1
    def Targets(self, j: int) -> Optional[BaoInstallTargetV1]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = BaoInstallTargetV1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BaoInstallManifestV1
    def TargetsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BaoInstallManifestV1
    def TargetsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # BaoInstallManifestV1
    def MetadataJson(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoInstallManifestV1
    def CreatedAt(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoInstallManifestV1
    def Hardware(self, j: int) -> Optional[BaoHardwareRequirementV1]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = BaoHardwareRequirementV1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BaoInstallManifestV1
    def HardwareLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BaoInstallManifestV1
    def HardwareIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # BaoInstallManifestV1
    def RuntimeConstraints(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # BaoInstallManifestV1
    def RuntimeConstraintsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BaoInstallManifestV1
    def RuntimeConstraintsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # BaoInstallManifestV1
    def Permissions(self, j: int) -> Optional[BaoPermissionV1]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = BaoPermissionV1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BaoInstallManifestV1
    def PermissionsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BaoInstallManifestV1
    def PermissionsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # BaoInstallManifestV1
    def Hooks(self) -> Optional[BaoLifecycleHooksV1]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = BaoLifecycleHooksV1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BaoInstallManifestV1
    def ChecksumSha256(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoInstallManifestV1
    def Signature(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def BaoInstallManifestV1Start(builder: flatbuffers.Builder):
    builder.StartObject(12)

def Start(builder: flatbuffers.Builder):
    BaoInstallManifestV1Start(builder)

def BaoInstallManifestV1AddName(builder: flatbuffers.Builder, name: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder: flatbuffers.Builder, name: int):
    BaoInstallManifestV1AddName(builder, name)

def BaoInstallManifestV1AddVersion(builder: flatbuffers.Builder, version: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(version), 0)

def AddVersion(builder: flatbuffers.Builder, version: int):
    BaoInstallManifestV1AddVersion(builder, version)

def BaoInstallManifestV1AddDescription(builder: flatbuffers.Builder, description: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(description), 0)

def AddDescription(builder: flatbuffers.Builder, description: int):
    BaoInstallManifestV1AddDescription(builder, description)

def BaoInstallManifestV1AddTargets(builder: flatbuffers.Builder, targets: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(targets), 0)

def AddTargets(builder: flatbuffers.Builder, targets: int):
    BaoInstallManifestV1AddTargets(builder, targets)

def BaoInstallManifestV1StartTargetsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartTargetsVector(builder, numElems: int) -> int:
    return BaoInstallManifestV1StartTargetsVector(builder, numElems)

def BaoInstallManifestV1AddMetadataJson(builder: flatbuffers.Builder, metadataJson: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(metadataJson), 0)

def AddMetadataJson(builder: flatbuffers.Builder, metadataJson: int):
    BaoInstallManifestV1AddMetadataJson(builder, metadataJson)

def BaoInstallManifestV1AddCreatedAt(builder: flatbuffers.Builder, createdAt: int):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(createdAt), 0)

def AddCreatedAt(builder: flatbuffers.Builder, createdAt: int):
    BaoInstallManifestV1AddCreatedAt(builder, createdAt)

def BaoInstallManifestV1AddHardware(builder: flatbuffers.Builder, hardware: int):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(hardware), 0)

def AddHardware(builder: flatbuffers.Builder, hardware: int):
    BaoInstallManifestV1AddHardware(builder, hardware)

def BaoInstallManifestV1StartHardwareVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartHardwareVector(builder, numElems: int) -> int:
    return BaoInstallManifestV1StartHardwareVector(builder, numElems)

def BaoInstallManifestV1AddRuntimeConstraints(builder: flatbuffers.Builder, runtimeConstraints: int):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(runtimeConstraints), 0)

def AddRuntimeConstraints(builder: flatbuffers.Builder, runtimeConstraints: int):
    BaoInstallManifestV1AddRuntimeConstraints(builder, runtimeConstraints)

def BaoInstallManifestV1StartRuntimeConstraintsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartRuntimeConstraintsVector(builder, numElems: int) -> int:
    return BaoInstallManifestV1StartRuntimeConstraintsVector(builder, numElems)

def BaoInstallManifestV1AddPermissions(builder: flatbuffers.Builder, permissions: int):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(permissions), 0)

def AddPermissions(builder: flatbuffers.Builder, permissions: int):
    BaoInstallManifestV1AddPermissions(builder, permissions)

def BaoInstallManifestV1StartPermissionsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartPermissionsVector(builder, numElems: int) -> int:
    return BaoInstallManifestV1StartPermissionsVector(builder, numElems)

def BaoInstallManifestV1AddHooks(builder: flatbuffers.Builder, hooks: int):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(hooks), 0)

def AddHooks(builder: flatbuffers.Builder, hooks: int):
    BaoInstallManifestV1AddHooks(builder, hooks)

def BaoInstallManifestV1AddChecksumSha256(builder: flatbuffers.Builder, checksumSha256: int):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(checksumSha256), 0)

def AddChecksumSha256(builder: flatbuffers.Builder, checksumSha256: int):
    BaoInstallManifestV1AddChecksumSha256(builder, checksumSha256)

def BaoInstallManifestV1AddSignature(builder: flatbuffers.Builder, signature: int):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(signature), 0)

def AddSignature(builder: flatbuffers.Builder, signature: int):
    BaoInstallManifestV1AddSignature(builder, signature)

def BaoInstallManifestV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return BaoInstallManifestV1End(builder)
