# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

# Single install target within a manifest.
class BaoInstallTargetV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BaoInstallTargetV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBaoInstallTargetV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BaoInstallTargetV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x42\x49\x4D\x31", size_prefixed=size_prefixed)

    # BaoInstallTargetV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BaoInstallTargetV1
    def Kind(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoInstallTargetV1
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoInstallTargetV1
    def ModuleId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoInstallTargetV1
    def ConfigJson(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def BaoInstallTargetV1Start(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    BaoInstallTargetV1Start(builder)

def BaoInstallTargetV1AddKind(builder: flatbuffers.Builder, kind: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(kind), 0)

def AddKind(builder: flatbuffers.Builder, kind: int):
    BaoInstallTargetV1AddKind(builder, kind)

def BaoInstallTargetV1AddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    BaoInstallTargetV1AddId(builder, id)

def BaoInstallTargetV1AddModuleId(builder: flatbuffers.Builder, moduleId: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(moduleId), 0)

def AddModuleId(builder: flatbuffers.Builder, moduleId: int):
    BaoInstallTargetV1AddModuleId(builder, moduleId)

def BaoInstallTargetV1AddConfigJson(builder: flatbuffers.Builder, configJson: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(configJson), 0)

def AddConfigJson(builder: flatbuffers.Builder, configJson: int):
    BaoInstallTargetV1AddConfigJson(builder, configJson)

def BaoInstallTargetV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return BaoInstallTargetV1End(builder)
