from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class BaoInstallTargetV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> BaoInstallTargetV1: ...
  @classmethod
  def GetRootAsBaoInstallTargetV1(cls, buf: bytes, offset: int) -> BaoInstallTargetV1: ...
  @classmethod
  def BaoInstallTargetV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Kind(self) -> str | None: ...
  def Id(self) -> str | None: ...
  def ModuleId(self) -> str | None: ...
  def ConfigJson(self) -> str | None: ...
def BaoInstallTargetV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def BaoInstallTargetV1AddKind(builder: flatbuffers.Builder, kind: uoffset) -> None: ...
def BaoInstallTargetV1AddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def BaoInstallTargetV1AddModuleId(builder: flatbuffers.Builder, moduleId: uoffset) -> None: ...
def BaoInstallTargetV1AddConfigJson(builder: flatbuffers.Builder, configJson: uoffset) -> None: ...
def BaoInstallTargetV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

