# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

# Lifecycle hook declarations for pre/post install/uninstall phases.
class BaoLifecycleHooksV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BaoLifecycleHooksV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBaoLifecycleHooksV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BaoLifecycleHooksV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x42\x49\x4D\x31", size_prefixed=size_prefixed)

    # BaoLifecycleHooksV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BaoLifecycleHooksV1
    def PreInstall(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoLifecycleHooksV1
    def PostInstall(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoLifecycleHooksV1
    def PreUninstall(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoLifecycleHooksV1
    def PostUninstall(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoLifecycleHooksV1
    def HealthCheck(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def BaoLifecycleHooksV1Start(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    BaoLifecycleHooksV1Start(builder)

def BaoLifecycleHooksV1AddPreInstall(builder: flatbuffers.Builder, preInstall: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(preInstall), 0)

def AddPreInstall(builder: flatbuffers.Builder, preInstall: int):
    BaoLifecycleHooksV1AddPreInstall(builder, preInstall)

def BaoLifecycleHooksV1AddPostInstall(builder: flatbuffers.Builder, postInstall: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(postInstall), 0)

def AddPostInstall(builder: flatbuffers.Builder, postInstall: int):
    BaoLifecycleHooksV1AddPostInstall(builder, postInstall)

def BaoLifecycleHooksV1AddPreUninstall(builder: flatbuffers.Builder, preUninstall: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(preUninstall), 0)

def AddPreUninstall(builder: flatbuffers.Builder, preUninstall: int):
    BaoLifecycleHooksV1AddPreUninstall(builder, preUninstall)

def BaoLifecycleHooksV1AddPostUninstall(builder: flatbuffers.Builder, postUninstall: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(postUninstall), 0)

def AddPostUninstall(builder: flatbuffers.Builder, postUninstall: int):
    BaoLifecycleHooksV1AddPostUninstall(builder, postUninstall)

def BaoLifecycleHooksV1AddHealthCheck(builder: flatbuffers.Builder, healthCheck: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(healthCheck), 0)

def AddHealthCheck(builder: flatbuffers.Builder, healthCheck: int):
    BaoLifecycleHooksV1AddHealthCheck(builder, healthCheck)

def BaoLifecycleHooksV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return BaoLifecycleHooksV1End(builder)
