from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class BaoLifecycleHooksV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> BaoLifecycleHooksV1: ...
  @classmethod
  def GetRootAsBaoLifecycleHooksV1(cls, buf: bytes, offset: int) -> BaoLifecycleHooksV1: ...
  @classmethod
  def BaoLifecycleHooksV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def PreInstall(self) -> str | None: ...
  def PostInstall(self) -> str | None: ...
  def PreUninstall(self) -> str | None: ...
  def PostUninstall(self) -> str | None: ...
  def HealthCheck(self) -> str | None: ...
def BaoLifecycleHooksV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def BaoLifecycleHooksV1AddPreInstall(builder: flatbuffers.Builder, preInstall: uoffset) -> None: ...
def BaoLifecycleHooksV1AddPostInstall(builder: flatbuffers.Builder, postInstall: uoffset) -> None: ...
def BaoLifecycleHooksV1AddPreUninstall(builder: flatbuffers.Builder, preUninstall: uoffset) -> None: ...
def BaoLifecycleHooksV1AddPostUninstall(builder: flatbuffers.Builder, postUninstall: uoffset) -> None: ...
def BaoLifecycleHooksV1AddHealthCheck(builder: flatbuffers.Builder, healthCheck: uoffset) -> None: ...
def BaoLifecycleHooksV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

