# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

# Permission declaration for a .bao manifest target or manifest-level scope.
class BaoPermissionV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BaoPermissionV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBaoPermissionV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BaoPermissionV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x42\x49\x4D\x31", size_prefixed=size_prefixed)

    # BaoPermissionV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BaoPermissionV1
    def Scope(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # BaoPermissionV1
    def Resource(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BaoPermissionV1
    def Reason(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def BaoPermissionV1Start(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    BaoPermissionV1Start(builder)

def BaoPermissionV1AddScope(builder: flatbuffers.Builder, scope: int):
    builder.PrependInt8Slot(0, scope, 0)

def AddScope(builder: flatbuffers.Builder, scope: int):
    BaoPermissionV1AddScope(builder, scope)

def BaoPermissionV1AddResource(builder: flatbuffers.Builder, resource: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(resource), 0)

def AddResource(builder: flatbuffers.Builder, resource: int):
    BaoPermissionV1AddResource(builder, resource)

def BaoPermissionV1AddReason(builder: flatbuffers.Builder, reason: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(reason), 0)

def AddReason(builder: flatbuffers.Builder, reason: int):
    BaoPermissionV1AddReason(builder, reason)

def BaoPermissionV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return BaoPermissionV1End(builder)
