from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.baoinstall.v1.BaoPermissionScope import BaoPermissionScope

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class BaoPermissionV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> BaoPermissionV1: ...
  @classmethod
  def GetRootAsBaoPermissionV1(cls, buf: bytes, offset: int) -> BaoPermissionV1: ...
  @classmethod
  def BaoPermissionV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Scope(self) -> typing.Literal[BaoPermissionScope.Read, BaoPermissionScope.Write, BaoPermissionScope.Execute, BaoPermissionScope.Admin, BaoPermissionScope.Network, BaoPermissionScope.Hardware]: ...
  def Resource(self) -> str | None: ...
  def Reason(self) -> str | None: ...
def BaoPermissionV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def BaoPermissionV1AddScope(builder: flatbuffers.Builder, scope: typing.Literal[BaoPermissionScope.Read, BaoPermissionScope.Write, BaoPermissionScope.Execute, BaoPermissionScope.Admin, BaoPermissionScope.Network, BaoPermissionScope.Hardware]) -> None: ...
def BaoPermissionV1AddResource(builder: flatbuffers.Builder, resource: uoffset) -> None: ...
def BaoPermissionV1AddReason(builder: flatbuffers.Builder, reason: uoffset) -> None: ...
def BaoPermissionV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

