# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

# Dependency type (what kind of dependency edge).
class DependencyTypeV1(object):
    REQUIRED = 0
    OPTIONAL = 1
    PEER = 2
    DEV = 3
