# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

# A directed edge between two nodes (dependency relationship).
class DependencyEdgeV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DependencyEdgeV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDependencyEdgeV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DependencyEdgeV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x42\x44\x47\x31", size_prefixed=size_prefixed)

    # DependencyEdgeV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Source node ID (dependent).
    # DependencyEdgeV1
    def FromId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Target node ID (dependency).
    # DependencyEdgeV1
    def ToId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Dependency type.
    # DependencyEdgeV1
    def DepType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Version constraint string (e.g., ">=1.2.0 <2.0.0").
    # DependencyEdgeV1
    def VersionConstraint(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Whether this edge was satisfied.
    # DependencyEdgeV1
    def Satisfied(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def DependencyEdgeV1Start(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    DependencyEdgeV1Start(builder)

def DependencyEdgeV1AddFromId(builder: flatbuffers.Builder, fromId: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(fromId), 0)

def AddFromId(builder: flatbuffers.Builder, fromId: int):
    DependencyEdgeV1AddFromId(builder, fromId)

def DependencyEdgeV1AddToId(builder: flatbuffers.Builder, toId: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(toId), 0)

def AddToId(builder: flatbuffers.Builder, toId: int):
    DependencyEdgeV1AddToId(builder, toId)

def DependencyEdgeV1AddDepType(builder: flatbuffers.Builder, depType: int):
    builder.PrependUint8Slot(2, depType, 0)

def AddDepType(builder: flatbuffers.Builder, depType: int):
    DependencyEdgeV1AddDepType(builder, depType)

def DependencyEdgeV1AddVersionConstraint(builder: flatbuffers.Builder, versionConstraint: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(versionConstraint), 0)

def AddVersionConstraint(builder: flatbuffers.Builder, versionConstraint: int):
    DependencyEdgeV1AddVersionConstraint(builder, versionConstraint)

def DependencyEdgeV1AddSatisfied(builder: flatbuffers.Builder, satisfied: bool):
    builder.PrependBoolSlot(4, satisfied, 0)

def AddSatisfied(builder: flatbuffers.Builder, satisfied: bool):
    DependencyEdgeV1AddSatisfied(builder, satisfied)

def DependencyEdgeV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return DependencyEdgeV1End(builder)
