# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

# Dependency resolution status.
class DependencyStatusV1(object):
    UNRESOLVED = 0
    RESOLVED = 1
    CONFLICT = 2
    MISSING = 3
    CIRCULAR = 4
