# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

# A single node in the dependency graph (one .bao target).
class DependencyNodeV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DependencyNodeV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDependencyNodeV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DependencyNodeV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x42\x44\x47\x31", size_prefixed=size_prefixed)

    # DependencyNodeV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Unique node identifier (target name).
    # DependencyNodeV1
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Human-readable display name.
    # DependencyNodeV1
    def Name(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Semantic version string.
    # DependencyNodeV1
    def Version(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Resolution status for this node.
    # DependencyNodeV1
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Number of direct dependencies.
    # DependencyNodeV1
    def DependencyCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Install order (topological sort index).
    # DependencyNodeV1
    def InstallOrder(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Estimated install duration in milliseconds.
    # DependencyNodeV1
    def EstimatedDurationMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Error message when status is CONFLICT, MISSING, or CIRCULAR.
    # DependencyNodeV1
    def Error(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def DependencyNodeV1Start(builder: flatbuffers.Builder):
    builder.StartObject(8)

def Start(builder: flatbuffers.Builder):
    DependencyNodeV1Start(builder)

def DependencyNodeV1AddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    DependencyNodeV1AddId(builder, id)

def DependencyNodeV1AddName(builder: flatbuffers.Builder, name: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder: flatbuffers.Builder, name: int):
    DependencyNodeV1AddName(builder, name)

def DependencyNodeV1AddVersion(builder: flatbuffers.Builder, version: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(version), 0)

def AddVersion(builder: flatbuffers.Builder, version: int):
    DependencyNodeV1AddVersion(builder, version)

def DependencyNodeV1AddStatus(builder: flatbuffers.Builder, status: int):
    builder.PrependUint8Slot(3, status, 0)

def AddStatus(builder: flatbuffers.Builder, status: int):
    DependencyNodeV1AddStatus(builder, status)

def DependencyNodeV1AddDependencyCount(builder: flatbuffers.Builder, dependencyCount: int):
    builder.PrependUint16Slot(4, dependencyCount, 0)

def AddDependencyCount(builder: flatbuffers.Builder, dependencyCount: int):
    DependencyNodeV1AddDependencyCount(builder, dependencyCount)

def DependencyNodeV1AddInstallOrder(builder: flatbuffers.Builder, installOrder: int):
    builder.PrependUint16Slot(5, installOrder, 0)

def AddInstallOrder(builder: flatbuffers.Builder, installOrder: int):
    DependencyNodeV1AddInstallOrder(builder, installOrder)

def DependencyNodeV1AddEstimatedDurationMs(builder: flatbuffers.Builder, estimatedDurationMs: int):
    builder.PrependUint32Slot(6, estimatedDurationMs, 0)

def AddEstimatedDurationMs(builder: flatbuffers.Builder, estimatedDurationMs: int):
    DependencyNodeV1AddEstimatedDurationMs(builder, estimatedDurationMs)

def DependencyNodeV1AddError(builder: flatbuffers.Builder, error: int):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)

def AddError(builder: flatbuffers.Builder, error: int):
    DependencyNodeV1AddError(builder, error)

def DependencyNodeV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return DependencyNodeV1End(builder)
