from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.baoinstall.v1.DependencyTypeV1 import DependencyTypeV1

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class DependencyEdgeV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> DependencyEdgeV1: ...
  @classmethod
  def GetRootAsDependencyEdgeV1(cls, buf: bytes, offset: int) -> DependencyEdgeV1: ...
  @classmethod
  def DependencyEdgeV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def FromId(self) -> str | None: ...
  def ToId(self) -> str | None: ...
  def DepType(self) -> typing.Literal[DependencyTypeV1.REQUIRED, DependencyTypeV1.OPTIONAL, DependencyTypeV1.PEER, DependencyTypeV1.DEV]: ...
  def VersionConstraint(self) -> str | None: ...
  def Satisfied(self) -> bool: ...
def DependencyEdgeV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def DependencyEdgeV1AddFromId(builder: flatbuffers.Builder, fromId: uoffset) -> None: ...
def DependencyEdgeV1AddToId(builder: flatbuffers.Builder, toId: uoffset) -> None: ...
def DependencyEdgeV1AddDepType(builder: flatbuffers.Builder, depType: typing.Literal[DependencyTypeV1.REQUIRED, DependencyTypeV1.OPTIONAL, DependencyTypeV1.PEER, DependencyTypeV1.DEV]) -> None: ...
def DependencyEdgeV1AddVersionConstraint(builder: flatbuffers.Builder, versionConstraint: uoffset) -> None: ...
def DependencyEdgeV1AddSatisfied(builder: flatbuffers.Builder, satisfied: bool) -> None: ...
def DependencyEdgeV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

