from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from baohaus.baoinstall.v1.DependencyStatusV1 import DependencyStatusV1

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class DependencyNodeV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> DependencyNodeV1: ...
  @classmethod
  def GetRootAsDependencyNodeV1(cls, buf: bytes, offset: int) -> DependencyNodeV1: ...
  @classmethod
  def DependencyNodeV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Name(self) -> str | None: ...
  def Version(self) -> str | None: ...
  def Status(self) -> typing.Literal[DependencyStatusV1.UNRESOLVED, DependencyStatusV1.RESOLVED, DependencyStatusV1.CONFLICT, DependencyStatusV1.MISSING, DependencyStatusV1.CIRCULAR]: ...
  def DependencyCount(self) -> int: ...
  def InstallOrder(self) -> int: ...
  def EstimatedDurationMs(self) -> int: ...
  def Error(self) -> str | None: ...
def DependencyNodeV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def DependencyNodeV1AddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def DependencyNodeV1AddName(builder: flatbuffers.Builder, name: uoffset) -> None: ...
def DependencyNodeV1AddVersion(builder: flatbuffers.Builder, version: uoffset) -> None: ...
def DependencyNodeV1AddStatus(builder: flatbuffers.Builder, status: typing.Literal[DependencyStatusV1.UNRESOLVED, DependencyStatusV1.RESOLVED, DependencyStatusV1.CONFLICT, DependencyStatusV1.MISSING, DependencyStatusV1.CIRCULAR]) -> None: ...
def DependencyNodeV1AddDependencyCount(builder: flatbuffers.Builder, dependencyCount: int) -> None: ...
def DependencyNodeV1AddInstallOrder(builder: flatbuffers.Builder, installOrder: int) -> None: ...
def DependencyNodeV1AddEstimatedDurationMs(builder: flatbuffers.Builder, estimatedDurationMs: int) -> None: ...
def DependencyNodeV1AddError(builder: flatbuffers.Builder, error: uoffset) -> None: ...
def DependencyNodeV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

