/**
 * Env keys used by BaoControlPlane rollout-gate option resolution.
 */
export const BAO_CONTROL_PLANE_GATE_ENV_KEYS = {
  forceSkip: "BAO_CONTROL_PLANE_GATE_FORCE_SKIP",
  origin: "BAO_CONTROL_PLANE_GATE_ORIGIN",
  portForwardAttachMs: "BAO_CONTROL_PLANE_GATE_PORT_FORWARD_ATTACH_MS",
  waitMs: "BAO_CONTROL_PLANE_GATE_WAIT_MS",
  pollMs: "BAO_CONTROL_PLANE_GATE_POLL_MS",
  requestTimeoutMs: "BAO_CONTROL_PLANE_GATE_REQUEST_TIMEOUT_MS",
  requestTimeoutBufferMs: "BAO_CONTROL_PLANE_GATE_REQUEST_TIMEOUT_BUFFER_MS",
  secretsRootDir: "BAO_CONTROL_PLANE_GATE_SECRETS_ROOT_DIR",
  secretsMaxLeakWarnings: "BAO_CONTROL_PLANE_GATE_SECRETS_MAX_LEAK_WARNINGS",
  requireSecretsConfigured: "BAO_CONTROL_PLANE_GATE_REQUIRE_SECRETS_CONFIGURED",
  requireInternalApiAuthForGuardedChecks:
    "BAO_CONTROL_PLANE_GATE_REQUIRE_INTERNAL_API_AUTH_FOR_GUARDED_CHECKS",
  requireSystemHealthAggregate: "BAO_CONTROL_PLANE_GATE_REQUIRE_SYSTEM_HEALTH_AGGREGATE",
  allowDegradedSystemHealth: "BAO_CONTROL_PLANE_GATE_ALLOW_DEGRADED_SYSTEM_HEALTH",
  requireGitOpsConverged: "BAO_CONTROL_PLANE_GATE_REQUIRE_GITOPS_CONVERGED",
  requirePackageInstalled: "BAO_CONTROL_PLANE_GATE_REQUIRE_PACKAGE_INSTALLED",
  requireBunbuddyFleetReady: "BAO_CONTROL_PLANE_GATE_REQUIRE_BUNBUDDY_FLEET_READY",
} as const;

/**
 * Canonical local gate-port env precedence for setup/verify flows.
 */
export const SETUP_WIZARD_BAO_CONTROL_PLANE_GATE_LOCAL_PORT_ENV_KEYS: readonly [
  "SETUP_WIZARD_AUTO_BAO_CONTROL_PLANE_GATE_PORT",
  "BAO_CONTROL_PLANE_GATE_LOCAL_PORT",
  "BAO_CONTROL_PLANE_LOCAL_GATE_PORT",
] = [
  "SETUP_WIZARD_AUTO_BAO_CONTROL_PLANE_GATE_PORT",
  "BAO_CONTROL_PLANE_GATE_LOCAL_PORT",
  "BAO_CONTROL_PLANE_LOCAL_GATE_PORT",
] as const;
