from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class MeshV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> MeshV1: ...
  @classmethod
  def GetRootAsMeshV1(cls, buf: bytes, offset: int) -> MeshV1: ...
  @classmethod
  def MeshV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def VertexCount(self) -> int: ...
  def FaceCount(self) -> int: ...
  def Vertices(self, i: int) -> typing.List[float]: ...
  def VerticesAsNumpy(self) -> np.ndarray: ...
  def VerticesLength(self) -> int: ...
  def VerticesIsNone(self) -> bool: ...
  def Faces(self, i: int) -> typing.List[int]: ...
  def FacesAsNumpy(self) -> np.ndarray: ...
  def FacesLength(self) -> int: ...
  def FacesIsNone(self) -> bool: ...
def MeshV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def MeshV1AddVertexCount(builder: flatbuffers.Builder, vertexCount: int) -> None: ...
def MeshV1AddFaceCount(builder: flatbuffers.Builder, faceCount: int) -> None: ...
def MeshV1AddVertices(builder: flatbuffers.Builder, vertices: uoffset) -> None: ...
def MeshV1StartVerticesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartVerticesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def MeshV1AddFaces(builder: flatbuffers.Builder, faces: uoffset) -> None: ...
def MeshV1StartFacesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartFacesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def MeshV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

