# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class MeshV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MeshV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMeshV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def MeshV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x53\x56\x31", size_prefixed=size_prefixed)

    # MeshV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MeshV1
    def VertexCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MeshV1
    def FaceCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MeshV1
    def Vertices(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # MeshV1
    def VerticesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # MeshV1
    def VerticesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MeshV1
    def VerticesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # MeshV1
    def Faces(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # MeshV1
    def FacesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # MeshV1
    def FacesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MeshV1
    def FacesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def MeshV1Start(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    MeshV1Start(builder)

def MeshV1AddVertexCount(builder: flatbuffers.Builder, vertexCount: int):
    builder.PrependUint32Slot(0, vertexCount, 0)

def AddVertexCount(builder: flatbuffers.Builder, vertexCount: int):
    MeshV1AddVertexCount(builder, vertexCount)

def MeshV1AddFaceCount(builder: flatbuffers.Builder, faceCount: int):
    builder.PrependUint32Slot(1, faceCount, 0)

def AddFaceCount(builder: flatbuffers.Builder, faceCount: int):
    MeshV1AddFaceCount(builder, faceCount)

def MeshV1AddVertices(builder: flatbuffers.Builder, vertices: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(vertices), 0)

def AddVertices(builder: flatbuffers.Builder, vertices: int):
    MeshV1AddVertices(builder, vertices)

def MeshV1StartVerticesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartVerticesVector(builder, numElems: int) -> int:
    return MeshV1StartVerticesVector(builder, numElems)

def MeshV1AddFaces(builder: flatbuffers.Builder, faces: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(faces), 0)

def AddFaces(builder: flatbuffers.Builder, faces: int):
    MeshV1AddFaces(builder, faces)

def MeshV1StartFacesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartFacesVector(builder, numElems: int) -> int:
    return MeshV1StartFacesVector(builder, numElems)

def MeshV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return MeshV1End(builder)
