from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class PointCloudV1(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> PointCloudV1: ...
  @classmethod
  def GetRootAsPointCloudV1(cls, buf: bytes, offset: int) -> PointCloudV1: ...
  @classmethod
  def PointCloudV1BufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def VertexCount(self) -> int: ...
  def Points(self, i: int) -> typing.List[float]: ...
  def PointsAsNumpy(self) -> np.ndarray: ...
  def PointsLength(self) -> int: ...
  def PointsIsNone(self) -> bool: ...
def PointCloudV1Start(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def PointCloudV1AddVertexCount(builder: flatbuffers.Builder, vertexCount: int) -> None: ...
def PointCloudV1AddPoints(builder: flatbuffers.Builder, points: uoffset) -> None: ...
def PointCloudV1StartPointsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartPointsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def PointCloudV1End(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

