# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class PointCloudV1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PointCloudV1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPointCloudV1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def PointCloudV1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x50\x43\x56\x31", size_prefixed=size_prefixed)

    # PointCloudV1
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PointCloudV1
    def VertexCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PointCloudV1
    def Points(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # PointCloudV1
    def PointsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # PointCloudV1
    def PointsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PointCloudV1
    def PointsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def PointCloudV1Start(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    PointCloudV1Start(builder)

def PointCloudV1AddVertexCount(builder: flatbuffers.Builder, vertexCount: int):
    builder.PrependUint32Slot(0, vertexCount, 0)

def AddVertexCount(builder: flatbuffers.Builder, vertexCount: int):
    PointCloudV1AddVertexCount(builder, vertexCount)

def PointCloudV1AddPoints(builder: flatbuffers.Builder, points: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(points), 0)

def AddPoints(builder: flatbuffers.Builder, points: int):
    PointCloudV1AddPoints(builder, points)

def PointCloudV1StartPointsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartPointsVector(builder, numElems: int) -> int:
    return PointCloudV1StartPointsVector(builder, numElems)

def PointCloudV1End(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return PointCloudV1End(builder)
