import {
  Code,
  Compile,
  CompileCached,
  CompileFromArtifact,
  type CompileOptions,
  Validator,
  type ValidatorArtifact,
} from "./compile/index.js";
import { Errors } from "./error/errors.js";
import { Script, ScriptWithDefinitions } from "./script/index.js";
import type {
  TIdentifier,
  TInterface,
  TNonNullable,
  TOptions,
  TParameter,
  TReadonlyType,
  TThis,
} from "./type/actions.js";
import * as Actions from "./type/actions.js";
import type { TKind, TSchema } from "./type/base-types.js";
import type { TBigIntCodec, TDateCodec, TURLCodec, URLLike } from "./type/codec-builtins.js";
import * as CodecBuiltins from "./type/codec-builtins.js";
import * as CombinatorCore from "./type/combinator-core.js";
import * as CombinatorFunctions from "./type/combinator-functions.js";
import * as CombinatorObjects from "./type/combinator-objects.js";
import type {
  TEnum,
  TIntersect,
  TOptional,
  TReadonly,
  TRecursive,
  TRef,
  TUnion,
} from "./type/composite-types.js";
import * as Containers from "./type/containers.js";
import type {
  InferOptionalKeys,
  InferRequiredKeys,
  TArray,
  TObject,
  TRecord,
  TTuple,
} from "./type/containers-types.js";
import type { TExtends, TExtendsResult } from "./type/extends.js";
import * as ExtendsExports from "./type/extends.js";
import type {
  TCall,
  TCodec,
  TCyclic,
  TGeneric,
  TImmutable,
  TInfer,
  TRefinement,
} from "./type/extensions.js";
import * as Extensions from "./type/extensions.js";
import * as Guards from "./type/guards.js";
import type {
  TAsyncIterator,
  TAwaited,
  TConstructor,
  TConstructorParameters,
  TDecode,
  TEncode,
  TFunction,
  TInstanceType,
  TIterator,
  TModule,
  TParameters,
  TPromise,
  TRegExpInstance,
  TReturnType,
  TUint8Array,
} from "./type/higher-order-types.js";
import type { TInstantiate, TProperties } from "./type/instantiation.js";
import * as Instantiation from "./type/instantiation.js";
import type { TExclude, TExtract, TTemplateLiteral, TUnsafe } from "./type/narrow-types.js";
import * as Primitives from "./type/primitives.js";
import type {
  TAny,
  TBigInt,
  TBoolean,
  TDate,
  TInteger,
  TLiteral,
  TNever,
  TNull,
  TNumber,
  TString,
  TSymbol,
  TUndefined,
  TUnknown,
  TVoid,
} from "./type/primitives-types.js";
import type {
  TOptionalAddAction,
  TOptionalRemoveAction,
  TReadonlyAddAction,
  TReadonlyRemoveAction,
} from "./type/root-constants.js";
import type { TDeferred, TInterfaceDeferred } from "./type/root-deferred.js";
import type {
  TArrayOptions,
  TEnumValue,
  TFormat,
  TIntersectOptions,
  TLiteralValue,
  TNumberOptions,
  TObjectOptions,
  TProperties as TPropertiesRecord,
  TSchemaOptions,
  TStringOptions,
  TTupleOptions,
} from "./type/schema-options.js";
import type { Static, StaticDecode, StaticEncode, StaticParse } from "./type/static-types.js";
import type {
  TCapitalize,
  TLowercase,
  TRest,
  TUncapitalize,
  TUppercase,
} from "./type/string-action-types.js";
import type {
  TConditional,
  TIfThenElse,
  TIndex,
  TKeyOf,
  TMapped,
  TNot,
  TOmit,
  TPartial,
  TPick,
  TRequired,
} from "./type/transform-types.js";
import * as Uint8ArrayCodecExports from "./type/uint8array-codec.js";
import { Value } from "./value/index.js";

const Type = {
  ...Actions,
  ...CodecBuiltins,
  ...CombinatorCore,
  ...CombinatorFunctions,
  ...CombinatorObjects,
  ...Containers,
  ...ExtendsExports,
  ...Extensions,
  ...Guards,
  ...Instantiation,
  ...Primitives,
  ...Uint8ArrayCodecExports,
  Script,
  ScriptWithDefinitions,
};

export default Type;
export {
  Capitalize,
  Clone,
  Composite,
  ExpandTupleRest,
  Identifier,
  Import,
  Interface,
  Lowercase,
  NonNullable,
  Options,
  Parameter,
  ReadonlyType,
  Rest,
  This,
  Uncapitalize,
  Uppercase,
} from "./type/actions.js";
export { BigIntCodec, DateCodec, URLCodec } from "./type/codec-builtins.js";
export {
  Enum,
  Evaluate,
  Intersect,
  Readonly,
  Recursive,
  Ref,
  Union,
} from "./type/combinator-core.js";
export {
  Awaited,
  ConstructorParameters,
  InstanceType,
  Module,
  Parameters,
  ReturnType,
} from "./type/combinator-functions.js";
export {
  Conditional,
  Exclude,
  Extract,
  IfThenElse,
  Index,
  KeyOf,
  Mapped,
  Not,
  Omit,
  Partial,
  Pick,
  Required,
  Unsafe,
} from "./type/combinator-objects.js";
export {
  Array,
  Object,
  Record,
  RecordKey,
  RecordKeyAsPattern,
  RecordValue,
  Tuple,
} from "./type/containers.js";
export { Extends, ExtendsResult } from "./type/extends.js";
export {
  Base,
  Call,
  Codec,
  Cyclic,
  DecodeBuilder,
  EncodeBuilder,
  Generic,
  Immutable,
  Infer,
  Refine,
} from "./type/extensions.js";
export {
  IsAny,
  IsArray,
  IsAsyncIterator,
  IsAwaited,
  IsBase,
  IsBigInt,
  IsBoolean,
  IsCall,
  IsCapitalize,
  IsCodec,
  IsConditional,
  IsConstructor,
  IsConstructorParameters,
  IsCyclic,
  IsDate,
  IsDecode,
  IsEncode,
  IsEnum,
  IsExclude,
  IsExtract,
  IsFunction,
  IsGeneric,
  IsIdentifier,
  IsIfThenElse,
  IsImmutable,
  IsIndex,
  IsInfer,
  IsInstanceType,
  IsInteger,
  IsInterface,
  IsIntersect,
  IsIterator,
  IsKeyOf,
  IsKind,
  IsLiteral,
  IsLowercase,
  IsMapped,
  IsModule,
  IsNever,
  IsNonNullable,
  IsNot,
  IsNull,
  IsNumber,
  IsObject,
  IsOmit,
  IsOptional,
  IsOptions,
  IsParameter,
  IsParameters,
  IsPartial,
  IsPick,
  IsPromise,
  IsReadonly,
  IsReadonlyType,
  IsRecord,
  IsRecursive,
  IsRef,
  IsRefine,
  IsRegExpInstance,
  IsRequired,
  IsRest,
  IsReturnType,
  IsSchema,
  IsString,
  IsSymbol,
  IsTemplateLiteral,
  IsThis,
  IsTuple,
  IsUint8Array,
  IsUncapitalize,
  IsUndefined,
  IsUnion,
  IsUnknown,
  IsUnsafe,
  IsUppercase,
  IsVoid,
} from "./type/guards.js";
export { Instantiate } from "./type/instantiation.js";
export {
  Any,
  AsyncIterator,
  Base64,
  BigInt,
  Boolean,
  Constructor,
  CreditCard,
  Date,
  DateFormat,
  DateTime,
  Decode,
  Duration,
  Email,
  Encode,
  Function,
  Hex,
  HexColor,
  Hostname,
  Integer,
  Ip,
  Iterator,
  Json,
  Literal,
  Never,
  Null,
  Number,
  Promise,
  RegExp,
  RegExpInstance,
  String,
  Symbol,
  TemplateLiteral,
  Time,
  Uint8Array,
  Undefined,
  Unknown,
  Uri,
  Uuid,
  Void,
} from "./type/primitives.js";
export { Uint8ArrayCodec } from "./type/uint8array-codec.js";
export type {
  CompileOptions,
  InferOptionalKeys,
  InferRequiredKeys,
  Static,
  StaticDecode,
  StaticEncode,
  StaticParse,
  TAny,
  TArray,
  TArrayOptions,
  TAsyncIterator,
  TAwaited,
  TBigInt,
  TBigIntCodec,
  TBoolean,
  TCall,
  TCapitalize,
  TCodec,
  TConditional,
  TConstructor,
  TConstructorParameters,
  TCyclic,
  TDate,
  TDateCodec,
  TDecode,
  TDeferred,
  TEncode,
  TEnum,
  TEnumValue,
  TExclude,
  TExtends,
  TExtendsResult,
  TExtract,
  TFormat,
  TFunction,
  TGeneric,
  TIdentifier,
  TIfThenElse,
  TImmutable,
  TIndex,
  TInfer,
  TInstanceType,
  TInstantiate,
  TInteger,
  TInterface,
  TInterfaceDeferred,
  TIntersect,
  TIntersectOptions,
  TIterator,
  TKeyOf,
  TKind,
  TLiteral,
  TLiteralValue,
  TLowercase,
  TMapped,
  TModule,
  TNever,
  TNonNullable,
  TNot,
  TNull,
  TNumber,
  TNumberOptions,
  TObject,
  TObjectOptions,
  TOmit,
  TOptional,
  TOptionalAddAction,
  TOptionalRemoveAction,
  TOptions,
  TParameter,
  TParameters,
  TPartial,
  TPick,
  TPromise,
  TProperties,
  TPropertiesRecord,
  TReadonly,
  TReadonlyAddAction,
  TReadonlyRemoveAction,
  TReadonlyType,
  TRecord,
  TRecursive,
  TRef,
  TRefinement,
  TRegExpInstance,
  TRequired,
  TRest,
  TReturnType,
  TSchema,
  TSchemaOptions,
  TString,
  TStringOptions,
  TSymbol,
  TTemplateLiteral,
  TThis,
  TTuple,
  TTupleOptions,
  TUint8Array,
  TUncapitalize,
  TUndefined,
  TUnion,
  TUnknown,
  TUnsafe,
  TUppercase,
  TURLCodec,
  TVoid,
  URLLike,
  ValidatorArtifact,
};
export {
  Code,
  Compile,
  CompileCached,
  CompileFromArtifact,
  Errors,
  Script,
  ScriptWithDefinitions,
  Type,
  Validator,
  Value,
};
