import {
  PAGE_HEADING_CLASS,
  SECTION_HEADING_CLASS,
  SORT_INDICATOR_CLASS,
  TABLE_CELL_META_CLASS,
  TABLE_CELL_MONO_CLASS,
  TABLE_SORT_HEADER_LINK_CLASS,
  TEXT_HINT_CLASS,
  UI_CAPTION_CLASS,
  UI_EMPHASIS_SM_CLASS,
  UI_EMPHASIS_XS_CLASS,
  UI_META_SECONDARY_CLASS,
} from "@baohaus/soy-view-kit/templates/design-tokens";

export {
  PAGE_HEADING_CLASS,
  SECTION_HEADING_CLASS,
  SORT_INDICATOR_CLASS,
  TABLE_CELL_META_CLASS,
  TABLE_CELL_MONO_CLASS,
  TABLE_SORT_HEADER_LINK_CLASS,
  TEXT_HINT_CLASS,
  UI_CAPTION_CLASS,
  UI_EMPHASIS_SM_CLASS,
  UI_EMPHASIS_XS_CLASS,
  UI_META_SECONDARY_CLASS,
};

/** Docs list page title — handwriting brand, shared size token. */
export const PAGE_HEADING_HANDWRITING_CLASS = `gw-handwriting ${PAGE_HEADING_CLASS}`;
